### ISSUE TITLE
(5) Develop workflow/requirements for QC of audio files post-ingest

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#10]
### Descriptive Summary

Create a workflow for reviewing audio files post ingest and a guideline for the people who will be reviewing the work. 

### Background 

This is a part of a larger AV digital workflow. 

At one point, UCSC was utilizing the Hyrax workflow feature but that has since been abandoned. We should determine what our new workflow requirements are so that they can be implemented and tested as a apart of testing the CMF Pilot #28  

### Acceptance Criteria

This is what done looks like

* [ ] Determine what an adequate review for audio and image looks like  
* [ ] Create a guideline for the people who will be reviewing this work 
* [ ] Create tickets for next steps for QA of collections.  

### Related Work 

#28 QA on CMF Pilot

**Comment by rmjaffe** [comment]
Just a note that one of the likely tickets that will come up with this is setting up Hyrax accounts for the students who will be doing the QA work.

**Comment by chesleyperry** [comment]
Draft QA spreadsheet is online here: [https://docs.google.com/spreadsheets/d/1qa-z830T7qBpOUg2A0aCrXBc47fx-toGQA8zEaRraLo/edit#gid=282589566](https://docs.google.com/spreadsheets/d/1qa-z830T7qBpOUg2A0aCrXBc47fx-toGQA8zEaRraLo/edit#gid=282589566)
Instructions for testers are in the readme tab.  I will populate it with titles and URLs once the collection is fully ingested.
