### ISSUE TITLE
() Update the OAI feed for MS20 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#100]

**Comment by NedHenry** [comment]
I think this issue needs some more details. MS20 is the collection that we are structuring into complex objects, correct? How should the OAI feed reflect the complex object structure we're implementing? In this case, should we simply omit the parent works from the OAI feed, so each child work gets an entry and there is no redundancy? Should this be the general rule for nested works?

**Comment by kellyChex** [comment]
This will come after the Virtual Reading Room Epic

**Comment by rmjaffe** [comment]
Closing this stub ticket.  A new ticket better describing this work in relationship to Calisphere/SILS can be recreated after we've had a conversation with CDL about harvesting/reharvesting our collections to Calisphere:  Have conversations with CDL & Metadata Services about sharing/harvesting to Primo & Calisphere #90
