### ISSUE TITLE
(1) Reach out to UCSD re: their VRR

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#102]
### Descriptive Summary

As the DAMS team works towards creating a VRR locally, it would be helpful to reach out to folks at UCSD to gather more information about their virtual reading room.

### Background 

UCSD's VRR is now in production. We may want to start doing some preliminary research on how feasible it would be/how much effort would it require to adapt their code.  Looking at UCSD's VRR set up and workflow may inform our conversations with Special Collections as we work with them to develop functional requirements.

### Acceptance Criteria

This is what done looks like

* [ ] Contact Matt Peters about doing a demo of their VRR set up for Special Collections
* [ ] Contact UCSD developers

### Related Work 

#2 Determine functional requirements for VRR

**Comment by kellyChex** [comment]
I've sent an email to Heather Smedberg and Matt Peters requesting a Demo of their Virtual Reading Room and CC Kate Dundon, Teresa Mora, Rachel, and Sue in hope to coordinate something after Thanksgiving week.
