### ISSUE TITLE
(1) Create ingest spreadsheet for dummy records

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#105]
### Descriptive Summary

As a UI/UX librarian, I want to see what metadata is appearing to patrons by default and how ti it is being labeled. I also want to see what metadata is being harvested and how it is being labeled in Calisphere and Primo.

As a metadata librarian, I want to confirm that our complex object metadata inheritance rules are working as expected.

### Acceptance Criteria

This is what done looks like

* [x] Spreadsheet that accounts for all the descriptive metadata properties in our data dictionary
* [x] Spreadsheet includes a simple and a complex object (parent-children) examples

### Related Work 

#100 Update OAI feeds for MS20

**Comment by kellyChex** [comment]
Dummy Records:
[fwddummyrecords.zip](https://github.com/UCSCLibrary/dams_project_mgmt/files/3786281/fwddummyrecords.zip)
