### ISSUE TITLE
(5) Move structural metadata 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#106]
### Descriptive Summary

Currently, structural metadata like 'In Collection' and In Administrative Set' are displaying below the Show More button. 

### Expected Behavior:

Structural metadata like 'In Collection' and 'In Administrative Set' should display above the Show More button in both Admin and Non Admin views. 

![Screen Shot 2019-10-29 at 1 07 05 PM](https://user-images.githubusercontent.com/9621070/67804917-2d3e6380-fa4d-11e9-84cb-5a1e56284096.png)

**Comment by NedHenry** [comment]
The "show more" button displays more metadata fields in the same format as the existing block of metadata - with alternating shading and bold for the headings. The structural metadata displays in a different block, with no shading and a vertical offset between the header and the value. If we put this block above the "show more" button, should the "show more" metadata still display in the same style as the above metadata, with structural metadata breaking it up in between? Should we format the structural metadata to be displayed along with the descriptive metadata in the same type of block?

**Comment by kellyChex** [comment]
Good point. If places above the Show more is should match the descriptive metadata style. 

We should consider this a bit more @JessWaggs. Perhaps we can keep it below the Show More but it would be easier to comprehend the difference if we specifically categorized that under a heading Structural Metadata in addition to including more padding around it so it looks like it's own section.

**Comment by kellyChex** [comment]
We agreed in our planning meeting that we would style the structural metadata as the descriptive metadata is styled.

**Comment by kellyChex** [comment]
Closing as this will be addressed in new UI/UX Overhaul ticket: https://github.com/UCSCLibrary/dams_project_mgmt/issues/130
