### ISSUE TITLE
UA50 broken images

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#107]
These items are displaying generic work icons instead of thumbnails on the collection browse pages.  Clicking on the item show pages returns the error 
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

http://digitalcollections.library.ucsc.edu/concern/works/vd66w142b?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/z890rv657?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/73666605j?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/k3569575s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/d504rm71s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/2z10wr70t?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/3484zj350?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/4f16c4273?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/sx61dn73x?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/qz20sv06n?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/6969z216t?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/qj72p8636?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/cf95jc91c?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/7w62f959q?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/6d56zx896?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/8910jv84z?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/xp68kh576?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/tx31qk27p?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/nc580p05j?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/k3569562q?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/5q47rp946?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/ht24wk814?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/zw12z6715?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/05741t100?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/79407z407?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/db78td201?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/k930bz108?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/6t053h46s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/z603qz45j?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/4m90dw321?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/h128nf791?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/0c483k26f?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/qz20st543?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/mw22v616b?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/dr26xz215?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/3197xm968?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/cj82k818m?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/td96k329x?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/k643b199d?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/vm40xs440?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/bz60cx00c?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/7h149q498?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/k3569513s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/n009w3175?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/4f16c3595?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/g732d972q?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/00000077m?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/rj4305363?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/5138jf68r?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/5h73pw803?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/1c18dg459?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/x346d491q?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/t148fh80p?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/9w032371f?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/rf55z846z?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/j6731456z?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/2n49t2601?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/q811kk25t?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/6q182k894?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/hh63sw636?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/6h440t315?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/5m60qs76r?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/c247ds869?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/9880vr67x?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/ff365608s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/ht24wk34r?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/kp78gh09s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/pz50gw99k?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/vm40xs38v?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/r781wg81s?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/6t053g86j?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/7h149q47q?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/c534fp71x?locale=en
http://digitalcollections.library.ucsc.edu/concern/works/5t34sk33q?locale=en

**Comment by kellyChex** [comment]
![Screen Shot 2019-11-04 at 1 24 15 PM](https://user-images.githubusercontent.com/9621070/68159332-6f145180-ff06-11e9-90aa-e677742a5c36.png)

**Comment by NedHenry** [comment]
I think the only problem is that the publication of this collection (Issue 101) was incomplete. Some works and some filesets were not yet published. I took down the collection from the homepage while the publication tasks complete. I am closing this issue to merge it with 101.

**Comment by NedHenry** [comment]
The collection is now fully published.
