### ISSUE TITLE
(1) UA50 images with "Do not upload" in title

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#108]
These are images that say "Do not upload" in the title.  It looks like we don't have accurate metadata for them.  Should they be unpublished?
http://digitalcollections.library.ucsc.edu/collections/jd472x03h?utf8=%E2%9C%93&sort=score+desc%2C+system_create_dtsi+desc&per_page=10&cq=do+not+upload&locale=en

**DECISION:**  Delete these images from the collection.

### Acceptance Criteria

- [ ] Images in the 'Do not upload' set have been removed from the collection

**Comment by kellyChex** [comment]
@chesleyperry Are they supposed to say "Not AA award winner?"

**Comment by kellyChex** [comment]
I'll pull into the backlog so we can discuss bringing this into the sprint tomorrow.

**Comment by rmjaffe** [comment]
@tmariamora Can we ask you and @katedundon to make a decision on these?  Do we want to ask Frank to ID these folks, leave them as unidentifiend, or do we want to remove the images?

**Comment by katedundon** [comment]
My hunch is to delete, but I defer to @tmariamora

**Comment by tmariamora** [comment]
I agree. Let's just delete. Thanks!

**Comment by rmjaffe** [comment]
Great, thank you both!
