### ISSUE TITLE
(5) Set up JPEG-2000 derivative encoding & decoding

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#109]
### Descriptive Summary
When we upload an image into the DAMS, we want our system to automatically generate a JPEG-2000 derivative file. 
When the image is requested from the image server, it should load the JPEG2000 derivative from the shared derivatives drive instead of the original file from Fedora.

### Background 

Large TIF files in Fedora take a lot of computing power to process, which makes our image server slow at creating derivative images. The JPEG-2000 format was designed for this purpose. 
As a test, I converted the Porter college scrapbook to all JPEG2000 images before importing it, so that the JPEG2000 format could be tested for speed. As expected, the Universal Viewer performed far, far better on the JPEG2000 images than on the large TIF files. 
I plan to use Kakadu as our JPEG2000 encoding and decoding software, because it has performed the best is several side by side evaluations against other leading jpeg2000 software. 

### Acceptance Criteria

* [ ] Any imported image has valid, reasonably sized jpeg2000 derivative automatically created
* [ ] Any request from our image server accesses the JPEG2000 derivative instead of the original TIF file
* [ ] I added some custom indexing in Solr to give the image server the information it needs to pull the image files from Fedora. This should be removed once the image server is no longer pulling images from Fedora.

**Comment by NedHenry** [comment]
This issue came out of issue #36 about the Universal Viewer performance

**Comment by kellyChex** [comment]
Ned to get in touch with Kevin Clark at UCLA to discuss Kakadu and their licensing agreements.
