### ISSUE TITLE
(1) Thumbnails are not displaying for the Oriental Collection 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#11]
### Expected Behavior

There is a default microphone what should be showing instead of the question mark 

Firefox screenshot:
![Firefox](https://user-images.githubusercontent.com/32003407/66346899-05555780-e908-11e9-9bec-235cf65faa7f.png)

Safari screenshot:
![Safari](https://user-images.githubusercontent.com/32003407/66346920-130add00-e908-11e9-8f66-9819edeb17ae.png)

**Comment by NedHenry** [comment]
I have a workaround that will fix the problem, at least for now (0b4a9c049fcaf3705f7666b43c8787b6a833957f). 
The default images for the work types are included in Hyrax, and therefore they should be part of the Rails asset pipeline. Blacklight calls "image_tag" on this link ([https://github.com/projectblacklight/blacklight/blob/master/app/presenters/blacklight/thumbnail_presenter.rb](https://github.com/projectblacklight/blacklight/blob/master/app/presenters/blacklight/thumbnail_presenter.rb) line 51), which should find these images in the asset pipeline and create an appropriate link to them there. Rails apparently can't find the images in the pipeline and renders a bare link to '/images/work.png'. 
My workaround is simply to copy the hyrax default images into the app's public folder, which is published outside of the asset pipeline. This will work for now but creates inconsistency and could allow hotlinking to our icons. It would be a neater solution to find out why these images are failing to load through the pipeline and address that problem.

**Comment by kellyChex** [comment]
#99, implement a better solution, placed in backlog as tech debt
