### ISSUE TITLE
(2) Get UA50 into Primo via OAI Feed 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#111]
As #101 is complete, Jess will get the UA50 into Primo via the OAI Feed. 

**Implementation:**
Set up an import profile in Primo (where it originates) and tell it how to identify where the thumbnail is using regular expressions.

**Comment by kellyChex** [comment]
Only a third of the collection is harvesting so Jess opened a support ticket with the vendor.

**Comment by JessWaggs** [comment]
This collection has now been imported into our [Primo Sandbox](https://ucsc-psb.primo.exlibrisgroup.com/discovery/search?query=any,contains,ucsc%20photography%20services&tab=Everything&search_scope=MyInst_and_CI&vid=01CDL_SCR_INST:USCS&offset=0)

A couple of notes/oddities:
- Primo aggregates / FRBRizes objects with matching key metadata elements
example of a FRBRized set of DAMS objects:
![Screen Shot 2019-12-04 at 11 38 23 AM](https://user-images.githubusercontent.com/6412857/70174913-a3f10100-168a-11ea-9691-d07608354fcd.png)

- Primo sees records with breaks in the title as having multiple title elements and it is only displaying the first title
example of object where the title has a break (not sure what creates this in the spreadsheet):
![Screen Shot 2019-12-04 at 11 40 32 AM](https://user-images.githubusercontent.com/6412857/70175086-e74b6f80-168a-11ea-9870-d8da0b5cc5b8.png)

- Some thumbnails didn't come through even though the image is in the DAMS; I'll investigate this further

**Comment by kellyChex** [comment]
@JessWaggs Do we need to make fixes on our end so those oddities don't show up in Primo?

**Comment by JessWaggs** [comment]
The FRBRizing is an FYI.

I've created ticket #141 to address the slashes issue.

Possibly for the thumbnails - still investigating.

**Comment by JessWaggs** [comment]
Thumbnail issue has resolved spontaneously.

**Comment by rmjaffe** [comment]
Closing this ticket.  In light of SILS, this work of getting our collections up in our local Primo instance is moot.  More than likely our digital collection content will be shared to the SILS Primo layer via Calisphere.
