### ISSUE TITLE
(3) Display rights statement with associated icons under Download option 

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#117]
### Descriptive Summary

Under the Download Button modal, as a user, I can see the Rights Statement with it's associated icons so that:
- I can quickly determine the reuse options for an item.
- I am provided permissions information beside my download options.

### Mock Up Example 

![Screen Shot 2019-11-20 at 2 24 34 PM](https://user-images.githubusercontent.com/9621070/69283571-83f91200-0ba1-11ea-8bc4-210705842378.png)

### Background 

These are the list of Rights Statements available for a user to select: 
![Screen Shot 2019-11-20 at 11 33 19 AM](https://user-images.githubusercontent.com/9621070/69271383-9404f780-0b89-11ea-8354-6cd19cf06305.png)
@NedHenry ^ Jess and I weren't able to see this drop down of options of Rights Statements like I'm used to seeing in other Hyrax applications. Do you know if your DAMS Hyrax application has the same ones?  

@JessWaggs Will then attach an icon library to associate to the available Rights Statements. 

### Acceptance Criteria

This is what done looks like: 

- [ ] Use title Rights Statement and not Rights Information as what's shown in the mock up.  

In Download modal under Rights Statement:

* [ ] When ______________ statement is attached to work, _________ icon shows 
* [ ] When ______________ statement is attached to work, _________ icon shows 
* [ ] When ______________ statement is attached to work, _________ icon shows

**Comment by kellyChex** [comment]
When ready, mocks ups would be good here too

**Comment by kellyChex** [comment]
@rmjaffe to reach out to Special Collections and get list of Rights Statements and confirm keeping free text rights statement and having rightstatement.org statements be separate.  

1. Free text rights statement
2. Right Statement.org statements - this is the one we're thinking will show up when one tries to download.

**Comment by rmjaffe** [comment]
Just head from Kate:  She and Teresa have supplied rightsStatements.org values for the collections represented on the first 5 sheets of the [collection tracking document](https://docs.google.com/spreadsheets/d/1nqcU2CO-3YzzLZzZzmDuNDbXwVT3zlZ53m83G_PZ490/edit#gid=434473815).  The rightsStatements.orgs are in Column Q.

For the pre-ingest collections, I'll add these values to the metadata ingest spreadsheets in a new rightsStatus metadata property.

**Comment by kellyChex** [comment]
Not sure if any work needs to be done here but I assume this is the copyright free text: 
![Screen Shot 2020-01-23 at 2 11 19 PM](https://user-images.githubusercontent.com/9621070/73028409-52433800-3dea-11ea-8239-24d3c4a707a5.png)

@NedHenry Does the application currently support creating and showing this?

**Comment by rmjaffe** [comment]
@kellyChex Yes, those are the free-text statements (Column M).  I think it is fine for those to appear only as part of the metadata records.  Unless I'm mistaken, what should pop-up upon download is the rightsStatements.org logo/label (Column Q).

![Screen Shot 2020-01-23 at 2 34 36 PM](https://user-images.githubusercontent.com/32003407/73030053-a4d22380-3ded-11ea-9d93-dc3b6f969496.png)

I'm going to make a ticket for myself to add rightsStatus to our metadata scheme (it is not presently a metadata property we use) and add the appropriate rightsStatements.org values/URIs to the ingest spreadsheets for each of the pre-ingest collections.

**Comment by rmjaffe** [comment]
@JessWaggs This card requires more research and/or likely a better needs assessment.
