### ISSUE TITLE
(5) Finish updating filenames and fixing issues with combined campus collections

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#12]
Finish updating Visual Resource Collection's filenames and fixing issues with combined campus collections

### Acceptance Criteria

- [x] Filename issues resolved

### Related Work

Ticket has been created for ingest of combined campus history collections: #41

**Comment by kellyChex** [comment]
Changed points from 2 to 5 as it was cleared up that this ticket involves making the appropriate fixes to the collection.

**Comment by rmjaffe** [comment]
This work is complete and the ingest spreadsheet has been checked over.  Metadata and files are ready for ingest.

Spreadsheet is here: smb://artifacts.library.ucsc.edu/DOMTP/Pre_Ingest/CampusHistoryCollections_Ingest

Files are on dams_ingest in Combined_Campus_History.  Ticket has been created for ingest.
