### ISSUE TITLE
(5) Post-Ingest Campus History Photograph Collections Cdm Takedown: UA 50, campus maps, & combined campus history

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#120]
## Collection Information

* Formal collection title: UC Santa Cruz Photography Services Photographs; everything on Combined Campus History spreadsheet
* Collection number: UA 50; everything else in the Cdm Campus History Bucket

### Communication

* [x] Spec Coll notified that collection(s) have been published

### CONTENTdm collection removal 

* [x] "About the collections" description on CONTENTdm homepage updated with link to DAMS
* [x] Remove or update links from Library resources (catalog, finding aid, library website, digital collections LibGuide)
* [x] Google search console report for links to CONTENTdm, submit link removal to Google
* [x] Google Analytics search for most popular links, send update to external linkers
* [x] ARKS’s updated. Notify Kate Dundon of new ARK.

### Related Work 

#101 Publish UA 50; #111 Get UA 50 into Primo

**Comment by rmjaffe** [comment]
In discussion with SCA, we've decided to not worry about grouping the images at present.  It may be something we will want to consider in the distant future.

**Comment by rmjaffe** [comment]
Post-ingest work on Ansel Adams is split between this and card #289.  #289 covers the tasks required to remove the collection from CONTENTdm; harvest of the collection to Calisphere & Primo will be addressed a part of this larger harvest.

**Comment by rmjaffe** [comment]
@chesleyperry Just deleted the UCSC Public Information Office Photographs, UCSC Photography Services Photographs, and UCSC Campus History - Photographs and Maps buckets from Cdm.

**Comment by chesleyperry** [comment]
Google search console and Google Analytics work will be done after CONTENTdm comes down and we can control the digitalcollections.ucsc.edu domain name.
