### ISSUE TITLE
(5) License and install full version of Kakadu

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#121]
### Descriptive Summary

We are currently using the demo version of Kakadu for encoding and decoding our jpeg2000 images for our image server. This performs well for uncompressed TIF files, but does not support compressed TIF files. Currently we can un-compress these TIFF files as part of the conversion process for these files only, but this adds extra hassle to our ingest workflow. We need license Kakadu and install the full version that supports compressed TIFFs.

### Background 

Quickly and efficiently compressing and decompressing image files is the primary function of our image server, and is very important to the performance of our whole site. The JPEG2000 format is well suited to our needs in this case. Several pieces of software exist to do the low level compression and decompression of the JPEG2000 images, and they have a wide range of performance. Based on my research so far, it looks like Kakadu is by far the fastest and tied most efficient, and is also the most used within the Samvera community. It seems like the clear choice to me. It should cost around a few hundred dollars a year to license, but we need to look into that. It is worth asking other Samvera institutions about their licensing experiences with Kakadu.

### Acceptance Criteria

This is what done looks like

* [x] We have a license for the full version of Kakadu
* [x] We have re-compiled the utilities kdu_compress and kdu_decompress to support compressed tiff files
* [] All of our image files process successfully into JPEG2000 images

**Comment by kellyChex** [comment]
@NedHenry @chesleyperry When we ask other institutions about their licensing experiences are we looking for suggestions on cheaper options? Else, what are we hoping to learn from them. Was UCSD an institution we should reach out to?

**Comment by chesleyperry** [comment]
Can we use just a Single Named User Licence or do we need the Speed Pack?  I will get a quote and start the purchase process - I just need to make sure I get the right license from [their options](https://kakadusoftware.com/licence/).  @NedHenry can you take a look?

**Comment by NedHenry** [comment]
There are two new developments on this issue.

1. The Kakadu sales rep Graham Morton (graham@kakadusoftware.com) sent me an order form for a free 6 month evaluation license for the full software. This will let us get up and running with the full version of Kakadu in the next couple of weeks, and we check whether the full version works well with our images on the next few ingests.
2. I heard from Kevin Clarke at UCLA that they are paying $5k per year for a public service license (the cheap ones). That's a lot more than I had assumed. Presumably we would pay less as a smaller institution, but it would still be a significant line item. I recommend we use their software for the next few months, see what kind of a price we can haggle with them for the future, and if they’re asking too much then we can then suck it up and implement a slower open source alternative (e.g. OpenJPEG).

**Comment by NedHenry** [comment]
Also, I propose we limit the scope of this ticket to acquiring the free 6-month evaluation license and using it to implement Kakadu on a temporary basis. Then we can create a new ticket for pricing out the long term license, evaluating the free alternatives, and deciding whether or not to pay for Kakadu.

**Comment by NedHenry** [comment]
I spoke with the Kakadu representative today, and he seemed confident that they could work with us on whatever budget we have. They don't publicize their prices because they try to charge the big universities with big budgets more, so that they can accommodate smaller universities with budget issues. I explained that although UCSC is not small, our library web development team is. He seemed on board with charging no more than we can pay, since we will be using the software to publish things for the public good. He asked that we come back to him a number for what our budget could accommodate.
That is encouraging enough that I think we should go ahead and implement the full Kakadu version using the evaluation license, with the expectation that we will probably be able to obtain a long term license for this software. Switching to OpenJPEG is still a viable free option, although it would mean some extra work and losing some speed on our image server.

**Comment by NedHenry** [comment]
We now have the full version of Kakadu installed using a six month evaluation license, and it is successfully (and quickly) decoding our jpeg2000 images. I will close this ticket and create new ones for following up on a long term license with kakadu, and for testing the encoding capabilities of the full kakadu software on our larger and weirder tiff files (some of which the demo version couldn't handle until they were pre-processed).
