### ISSUE TITLE
Environmental scan & determine search facets requirements 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#123]
### Descriptive Summary

Mocks ups were created for what the new look and feel of the DAMS site will be:

![Screen Shot 2019-11-18 at 4 39 57 PM](https://user-images.githubusercontent.com/9621070/69106095-33a77600-0a22-11ea-91ab-eb935d736265.png)

We need to determine what the search facet needs and requirements are as mentioned in #25

For inspiration sake, here is UCLA's Oral History's search facets:

![Screen Shot 2019-11-18 at 4 43 02 PM](https://user-images.githubusercontent.com/9621070/69106206-81bc7980-0a22-11ea-853d-9500cfa865d7.png)

### Acceptance Criteria

- [ ] Environmental scan of facet options
- [ ] Determine needs/functional requirements of faceting; interview member of SC&A (general collections) and Sue (cartographic collections)
- [ ] Formulate recommendation for how metadata properties will be labeled
- [ ] Formulate recommendations which facets to display and how they will be labeled

**Comment by rmjaffe** [comment]
This should probably be hold until we resolve #137 Reconcile config file.

**Comment by rmjaffe** [comment]
@JessWaggs I just updated the acceptance criteria on this card adding labeling of metadata properties (as discussed over email) as a criterion and specifying who should be interview as part or the needs assessment/reqs gathering process.

**Comment by JessWaggs** [comment]
[Report of Recommendations](https://docs.google.com/document/d/1C8cPz63rAnCRcOnhY7qYIhGOg5vkeoyy8MA6kf_nrz8/edit#) submitted 11/19 and approved 11/30
