### ISSUE TITLE
(1) Download small 250px link in modal 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#126]
### Descriptive Summary

In the Download modal, as a user, when I click 'Download Small (250px)' link, I am able to download the object file at 250px. 

### Background 

Originated from Journey Map: Serena from Home
(If a user forgets to copy the citation when they download the desired file, they sometimes cannot remember the origin of the file and then are unable to use it.)

### Mock Up: 

<img width="993" alt="Screen Shot 2019-11-27 at 11 56 24 AM" src="https://user-images.githubusercontent.com/9621070/69764585-efe4f880-1114-11ea-867b-0ee6d43246e4.png">

**Comment by rschwab** [comment]
@NedHenry How does this potential solution look? It adds the download sizes to the list the image server caches, then adds a parameter for size to the display_image_url method (800 was already defined as a default in app/models/solr_document.rb).
`diff --git a/app/models/file_set.rb b/app/models/file_set.rb
index d211c7a..151e76d 100644
--- a/app/models/file_set.rb
+++ b/app/models/file_set.rb
@@ -47,8 +47,10 @@ class FileSet < ActiveFedora::Base
   def image_server_derivative_sizes
     ['90,',
      '!200,150',
+     '250,',
      '!300,300',
-     '800,']
+     '800,',
+     '1000,']
   end
 
   def image_server_cache_derivatives
diff --git a/app/presenters/ucsc/work_show_presenter.rb b/app/presenters/ucsc/work_show_presenter.rb
index 34fccbd..61b207a 100644
--- a/app/presenters/ucsc/work_show_presenter.rb
+++ b/app/presenters/ucsc/work_show_presenter.rb
@@ -18,14 +18,14 @@ module Ucsc
     end
 
     # We should delegate this to the solrDocument, which should have it already indexed (for works at least).
-    def display_image_url
+    def display_image_url(size)
       if representative_id
         return nil unless current_ability.can?(:read, representative_id)
         representative_image = SolrDocument.find(representative_id)
         return nil unless representative_image.image?
-        representative_image.display_image_url
+        representative_image.display_image_url(size: size)
       elsif solr_document.image?
-        solr_document.display_image_url
+        solr_document.display_image_url(size: size)
       end
     end
 
diff --git a/app/views/hyrax/base/_modals.html.erb b/app/views/hyrax/base/_modals.html.erb
index 0311e31..27f9d86 100644
--- a/app/views/hyrax/base/_modals.html.erb
+++ b/app/views/hyrax/base/_modals.html.erb
@@ -8,8 +8,8 @@
         <h5>Rights Information:</h5>
         <p>I'm a test, please don't copy me.</p>
         <ul>
-          <li><a href="">Download Small (250px)</a></li>
-          <li><a href="">Download Large (1000px)</a></li>
+          <li><%= link_to('Download Small (250px)',@presenter.display_image_url("250")) %></li>
+          <li><%= link_to('Download Small (1000px)',@presenter.display_image_url("1000")) %></li>
           <li><a href="">Download Small (250px) + Citation (Zip File)</a></li>
           <li><a href="">Download Large (1000px) + Citation (Zip File)</a></li>
         </ul>`

**Comment by NedHenry** [comment]
@rschwab That approach looks good. 
The only important note is that we shouldn't add a required argument to an existing method, or all calls to that method would break. There are a bunch of view partials that call WorkShowPresenter.display_image_url without arguments, and we still want all of those to default to the right thing. 
We could either define the default size there in the presenter (`def display_image_url(size="800,")`), or give it a nil default and get the SolrDocument to use its in that case (`def display_image_url(size=nil)`). 
Also (just a thought) we might want to consider not creating the 1000 px cached derivative files for all of our images. Most of them will never be downloaded this way, so we'd save some resources by creating these on the fly when requested. The image server can create these derivatives in a few seconds at most, and this delay is probably acceptable for a download request.

**Comment by rschwab** [comment]
Here's the [pull request](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/111).

Screenshot:
![Firefox_Screenshot_2020-02-20T21-58-44 635Z](https://user-images.githubusercontent.com/515412/74983128-51ea8c80-53ea-11ea-8332-97b8e8f77c2a.png)

@NedHenry I ended up setting the default size in the presenter and removing the 1000 width size from caching.

**Comment by chesleyperry** [comment]
Tested:
Windows 10/Chrome
Windows 10/Firefox
Mac OS 10.14/Chrome
Mac OS 10/14/Safari
Mac OS 10.14/Firefox
iOS/Chrome

All re-displayed the image at 250pixels but did not display it.  I think this is acceptable.
