### ISSUE TITLE
(1) Download large 1000px link in modal 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#127]
### Descriptive Summary

In the Download modal, as a user, when I click 'Download Large (1000px)' link, I am able to download the object file at 1000px. 

### Background 

Originated from Journey Map: Serena from Home
(If a user forgets to copy the citation when they download the desired file, they sometimes cannot remember the origin of the file and then are unable to use it.)

### Mock Up: 

<img width="993" alt="Screen Shot 2019-11-27 at 11 56 24 AM" src="https://user-images.githubusercontent.com/9621070/69764634-21f65a80-1115-11ea-8ee9-2f4f5f552213.png">

### Implementation Steps:
- What is involved with making the file come in at 1000px?

**Comment by rschwab** [comment]
Here's the [pull request](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/111).

Screenshot:
![Firefox_Screenshot_2020-02-20T21-58-44 635Z](https://user-images.githubusercontent.com/515412/74983229-7cd4e080-53ea-11ea-93f9-c24ca80bdef0.png)

**Comment by chesleyperry** [comment]
I've QA'd this and I believe it works as intended.  When the user clicks on the download button, the system displays the image at 1000px.  It's up to the user to know how to right-click or use the browser menu to download the image because there's no instruction.  @JessWaggs - is that what you intended?

**Comment by JessWaggs** [comment]
I was picturing that a click would initiate a download, not display the image in the browser. Is this possible?

**Comment by rschwab** [comment]
I don't believe there is a way to direct the browser to download an image - that's a setting in the users browser. The only way I can think of around it would be to zip the image in order to force a download.

**Comment by rschwab** [comment]
Oh, there is a download directive in HTML5 we could try. It might not have support in all browsers, but most should support. https://stackoverflow.com/questions/17527713/force-browser-to-download-image-files-on-click

**Comment by rschwab** [comment]
@NedHenry If you're already working on removing the citations link from the download modal, could you add a "download" parameter to the download links?

**Comment by chesleyperry** [comment]
Tested:
Windows 10/Chrome
Windows 10/Firefox
Mac OS 10.14/Chrome
Mac OS 10/14/Safari
Mac OS 10.14/Firefox
iOS/Chrome

All re-displayed the image at 1000px, did not actually download it.  I think this is acceptable.
