### ISSUE TITLE
(5) Implement new metadata display 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#130]
### Acceptance Criteria

This is what done looks like

* [ ] About This Item header  
* [ ] Metadata is organized and styled according to the mock up 
* [ ] Note, the mock ups are for the non admin view.
* [ ] Ensure metadata is accessible in the html version of this page even though the 'More information' hasn't been clicked to expand the rest of the information. 
* [ ] Admin view will have Structural Metadata like 'In Collection' and 'In Administrative Set' and this should display above the More Information button in both Admin and Non Admin views and styled like description metadata for Admin View only. 

### Expected Look 

![Screen Shot 2019-11-20 at 6 20 33 PM](https://user-images.githubusercontent.com/9621070/69298405-98013b80-0bc2-11ea-8516-27793d3a9ae2.png)

<img width="712" alt="Screen Shot 2019-11-27 at 7 11 08 AM" src="https://user-images.githubusercontent.com/9621070/69744911-2d319200-10e5-11ea-99d3-b1d606532c13.png">

### Current Look

Media Player Example:
![Screen Shot 2019-11-20 at 6 22 23 PM](https://user-images.githubusercontent.com/9621070/69298441-b7986400-0bc2-11ea-8e8a-3eec53cfe4e5.png)

Single Image Example:
<img width="956" alt="Screen Shot 2019-11-26 at 12 55 58 PM" src="https://user-images.githubusercontent.com/9621070/69680297-a3cf8080-104e-11ea-90da-843e94b9ceb9.png">

### Style Guide:
Fonts:
Sizes:
Colors: 
Icons:

**Comment by JessWaggs** [comment]
I think we only want "In Administrative Set" to display to Admin users. Unless there is a reason end users would need this?

**Comment by kellyChex** [comment]
@JessWaggs I cleaned up the acceptance criteria to make note of the difference between the admin and non admin view. If there's time, we can attach the mock ups here and consider breaking this ticket down into admin view vs non admin view.

**Comment by rschwab** [comment]
Here's how it looks now:

![Firefox_Screenshot_2020-01-10T21-53-48 144Z](https://user-images.githubusercontent.com/515412/72189241-3636a400-33b1-11ea-93fa-e2651487a5f8.png)

**Comment by kellyChex** [comment]
@JessWaggs To take a look

**Comment by JessWaggs** [comment]
This is looking good!

Sorry I didn't see the style guide needs earlier. Eventually, I would like to create a real style guide - maybe I'll put a ticket for that in the backlog.

Color Palette:
Gray Font Color: #757575
Link color - unselected: #02779e
Link on hover: #23527c and underline
Gold: #FFCC33
Navy blue: #00457C

Fonts:
Family: Roboto
Title (h1): 36px
Sections Headers (h2): 20px
Body: 16px
Link font weight: 500
 -- though we may want to only employ this for links other than metadata elements for the DAMS


We are so far from being standardized on icon use, so I'll leave that for the future style guide : )  
The ones Ryan selected look great

**Comment by kellyChex** [comment]
@JessWaggs Will you add a ticket for this and include the link here for record's sake.

**Comment by kellyChex** [comment]
Tested on production and this new section looks good!
