### ISSUE TITLE
(5) Add About the Collection section 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#131]
### Acceptance Criteria
- [x] Make the About the collection section look like the mock up 
* [x] Collection Guide link goes to the finding aid - related resource property in the metadata  
* [x] Ignore Exhibit and Link in mock up 

### Expected Look

![Screen Shot 2019-11-20 at 7 41 10 PM](https://user-images.githubusercontent.com/9621070/69302205-bf113a80-0bcd-11ea-902f-923252b03c99.png)

### Current Look 
![Screen Shot 2019-11-20 at 7 38 21 PM](https://user-images.githubusercontent.com/9621070/69302226-c89aa280-0bcd-11ea-994e-c502f5f0ea6e.png)

**Comment by JessWaggs** [comment]
This will help contextualize the item within the larger collection - we saw a strong desire for context come out of the user interviews and that is also reflected in the journey maps.

To some degree it is repetitive of the breadcrumbs - once this is in place, it would be reasonable to ask if we still want/need breadcrumbs.

Would it help to articulate what elements will display in the About the Collection box from a metadata perspective?

**Comment by kellyChex** [comment]
@JessWaggs Ok, thank for that explanation. From the Hyrax users I've spoken with, they find the breadcrumbs useful for backtracking as well as understanding the nested relationships. Currently, the breadcrumbs only display partial titles. I wonder if this could be adding to their confusion. 

By articulating what elements will display do you mean giving an example of the parent child relationship and how that will look?

**Comment by kellyChex** [comment]
@JessWaggs to indicate what links are being listed, where the icons are coming from, etc. then rachel to add what metadata this matches with.

**Comment by JessWaggs** [comment]
Metadata (and logic) for the About the Collections box:

Child objects: 
Collection (title from collection record) - Parent (title from parent record) - Child/Item being viewed (title from child record)

Parent objects with series: 
Collection (title from collection record) - Series (series from parent record) - Parent/object being viewed (title from parent record)

Parent objects without a series: 
Collection (title from collection record) - Parent/object being viewed (title from parent record)

Simple object with series: 
Collection (title from collection record) - Series (from object metadata record) - object being viewed (title from object record)

Simple object without a series: 
Collection (title from collection record) - Object being viewed (title from object record)

**Comment by rmjaffe** [comment]
For reference, the ingest spreadsheet for the CMF collection is on dams_ingest.  It is formatted per the current collection-level metadata spec.

**Comment by rmjaffe** [comment]
@rschwab If you have the capacity to pick this ticket up, let me know and I'll move it into the sprint.

**Comment by rschwab** [comment]
Code and screenshots for this can be found at the pull request link directly above this comment.

**Comment by rschwab** [comment]
I was unable to test the Collection Guide link locally, so please pay special attention to that while doing QA.

**Comment by NedHenry** [comment]
This is now deployed to the staging server and is ready for QA. Sample url: 
[Staging Work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/x633f103b?locale=en)

**Comment by JessWaggs** [comment]
This is looking good! I looked at a few items with no series and one with a series, and they worked as expected.

I noticed that the connector icon between the collection/series/item was missing.
