### ISSUE TITLE
Discuss what to remove for new style 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#132]
### Current Look
![Screen Shot 2019-11-20 at 7 47 37 PM](https://user-images.githubusercontent.com/9621070/69302464-a0f80a00-0bce-11ea-9e39-f8c16d76b22b.png)

### To Discuss: 
- Any changes to how items are displayed below the metadata? 
- Ensure Analytics, Link Text, Social Media buttons, and Permanent Link are removed from the Work's page?

**Comment by JessWaggs** [comment]
The items would be listed as a Track List, displaying only the title.
![AVObject-items](https://user-images.githubusercontent.com/6412857/69663471-2a7a6280-103b-11ea-9158-75cbd7359cce.png)

**Comment by JessWaggs** [comment]
Analytics should appear in the Admin view only.

Link text, social media buttons, and Permanent Link should all be removed from the main page.
(Social media buttons and permalink will appear on SHARE modal.)
![ShareModal](https://user-images.githubusercontent.com/6412857/69663632-7c22ed00-103b-11ea-9fb4-50759c7c88e3.png)

**Comment by kellyChex** [comment]
@JessWaggs So we'll be hiding the Items section? Will this be the same for all the different types of collections i.e., single images, video, etc.?

We may want to save this task for the end to ensure all information is newly displaying properly first.

**Comment by JessWaggs** [comment]
I can't think of a case where we would want the image list displaying. Hiding across the board sounds right.

**Comment by rmjaffe** [comment]
@JessWaggs @kellyChex Is this ticket still live or has this issue been addressed?

**Comment by JessWaggs** [comment]
I think this is covered in #129 and this ticket can be closed.
