### ISSUE TITLE
Create more UI/UX Overhaul stories 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#133]
Link to mock ups: https://drive.google.com/drive/u/1/folders/1Ypcd3SdjRgZlzsiRzmwn3Kzc1kSxhK5O 

- Create stories for Set Item Pages  
- Determine mobile design priority.   
- Create mocks ups for admin view then create those stories

**Comment by JessWaggs** [comment]
@rmjaffe I think we can close this one - it was a very early days placeholder ticket
