### ISSUE TITLE
(2) Discuss collection level metadata and collection groups

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#139]
### Descriptive Summary

We need to decide how to manage collection-level metadata and collection groups (such as campus history), and how to incorporate them into the ingest workflow.

Discussion questions and user stories are in the [Google Doc](https://docs.google.com/document/d/10S4IZ3f6nvRhz1LsAcBJrtNgP6GaByyArOf0v_oAPPI/).

### Background 

We want to be able to display collection contextual information on item show pages, and on collection landing pages. We also have CONTENTdm "buckets" and they need to be moved into the DAMS that are essentially collections of collections.   The Samvera site has [documentation](https://samvera.github.io/admin-sets-as-collections-faq.html) about collections and administrative sets.

### Acceptance Criteria

This is what done looks like

* [ ] We have a clear understanding of how to include collection metadata in the ingest process
* [ ] We have a meeting to discuss strategy for grouping collections together.

### Related Work 

Combined campus history collections #41 are a good test of this strategy.

**Comment by NedHenry** [comment]
I noticed that Rachel wrote up some of the questions around this really clearly in [a Google Doc](https://docs.google.com/document/d/10S4IZ3f6nvRhz1LsAcBJrtNgP6GaByyArOf0v_oAPPI/edit?usp=sharing). I went ahead and added my 2 cents to a bunch of the questions, giving background on how much work is needed to implement each of these desired features (not too much).
I think the hardest part will be the front-end work to get a good UI for discovery and display of the grouped collections, no matter how we end up implementing them. Under the hood I think it will be nearly identical to what we've already done for nested works (fingers crossed).
