### ISSUE TITLE
Prepare UCSC Faculty Lectures collection for publication

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#140]
### Descriptive Summary

Before we publish the UCSC Faculty Lectures (Hitchcock and Holmes), we need to tweak the public display

Consider using the User Story format:

Users can easily browse an audio collection from the home page and understand the works they are listening to

### Background 

Additional information about the reason for the feature or story. 

### Acceptance Criteria

This is what done looks like

* [ ] Representative image displays on the home page
* [ ] Works have unique titles (History of Western Civilization 1970-71 and History of Western Civilization 1976-77) 
* [x] Audio Playlist is hidden from the parent work view

**Comment by kellyChex** [comment]
Not relevant anymore.
