### ISSUE TITLE
(2) Mock-up for Image Objects on Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#144]
### Descriptive Summary

Create mock-ups for image objects on mobile

### Acceptance Criteria

This is what done looks like

* [x] Mock-up for single image on mobile
* [x] Mock-up for image set / complex object on mobile

**Comment by JessWaggs** [comment]
Single image on mobile:

![Screen Shot 2020-02-25 at 9 48 44 AM](https://user-images.githubusercontent.com/6412857/75273074-1964fd00-57b4-11ea-976b-fbf96aebb679.png)

Gray text is #575757
Blue link text is standard blue
First image shows where "fold" wold be on an iPhone 11
Second image shows popover that displays after user clicks the 3 vertical dot menu

**Comment by JessWaggs** [comment]
Image set on mobile
![Screen Shot 2020-02-25 at 10 23 00 AM](https://user-images.githubusercontent.com/6412857/75275422-5b447200-57b9-11ea-97e5-6652988385d1.png)

**Comment by chesleyperry** [comment]
This looks good to me. No suggestions for changes.
Just to further document the hex codes for the colors:  blue link text should be #006aad to match the campus.  
Both the gray and the blue meet the contrast requirements for accessibility.  
The linked blue text also needs a visual cue when users point to the link with their mouse or move keyboard focus to the link. Underlining the link or making it bold are both acceptable.
