### ISSUE TITLE
(3) Mock-ups for homepage

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#146]
### Descriptive Summary

Create mock-ups for homepage for both desktop and mobile screens

### Acceptance Criteria

This is what done looks like

* [x] Mock-up for homepage for desktop
* [x] Mock-up for homepage for mobile

**Comment by JessWaggs** [comment]
Homepage desktop:

![Screen Shot 2020-03-06 at 2 31 31 PM](https://user-images.githubusercontent.com/6412857/76127728-48028500-5fb7-11ea-856a-a8884be6d642.png)

Colors used:
Med. Blue background: #02779E at 75% opacity
Dark gray background: #575757 at  75% opacity
Text over both: #FFFFFF

**Comment by JessWaggs** [comment]
Mobile: 
![Screen Shot 2020-03-06 at 2 44 59 PM](https://user-images.githubusercontent.com/6412857/76128446-35894b00-5fb9-11ea-8107-e0a17a32c0fa.png)

**Comment by rmjaffe** [comment]
@JessWaggs I think these look fantastic! I hope we stick with that reader on the Squiggle photo for the background.

I have a couple questions/comments:

1. Would "featured" collections feature only collections, or collections and collections of collections (presumably if we featured a collection of collections, we would not want to also separately feature constituent collections)?
2. Browse collections:  Same question, would this be an A-Z list of all our collections, or a mix of collections and collections of collections?
3. Digital Collections login:  Just double checking at this point, were not expecting anyone other than library staff to be creating accounts, right?  They can, but they're not having to for any functional reason (VRR, other).  If that's the case, if makes sense to have the login tucked in the footer, but if there does become a need for users to create accounts, we may want to consider relocating.

**Comment by JessWaggs** [comment]
@rmjaffe  Great questions! : )

1) I think this could be flexible, including collections of collections makes sense to me. I would see this as quick/easy access to our highly used collections (or collection groups / collections  of collections)
2) As soon as I put that button in the mock up, I found myself thinking "Well, this will require another mock up..."  Yes - I'm thinking it would be an A-Z list of all of our collections, and makes sense to include groups here as well
3) Yes, at this point only staff will be logging in. I agree - if/when non-staff need to log in, we will need to think about access points and increasing log in visibility

**Comment by kellyChex** [comment]
@JessWaggs Can you create another ticket for adding the A-Z component. I think we can consider that a separate add on task.
