### ISSUE TITLE
(2) Mock-ups for Search and Browse screens in mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#147]
### Descriptive Summary

Create mock-ups for search and browse screens for mobile

### Acceptance Criteria

This is what done looks like

* [x] Mock-up for search results screen in mobile
* [x] Mock-up for collection browse screen in mobile

**Comment by JessWaggs** [comment]
Search results in mobile:

![Screen Shot 2020-01-28 at 10 42 58 AM](https://user-images.githubusercontent.com/6412857/73294719-34dfe680-41bb-11ea-9ac6-cfe0d134ee49.png)

When users selects "Show Filters":

![Screen Shot 2020-01-28 at 10 42 47 AM](https://user-images.githubusercontent.com/6412857/73294745-3dd0b800-41bb-11ea-9857-8a767c0880b4.png)

**Comment by JessWaggs** [comment]
Collection Landing page (Browse):

<img width="341" alt="Screen Shot 2020-01-28 at 4 03 05 PM" src="https://user-images.githubusercontent.com/6412857/73316434-b3527d80-41e7-11ea-81aa-88e21a55e022.png">

**Comment by JessWaggs** [comment]
@chesleyperry @rmjaffe

**Comment by rmjaffe** [comment]
@JessWaggs These look great -- one question:  The "visit the collection guide" link on the collection landing page (last image), that's a link to the finding aid, correct?

**Comment by chesleyperry** [comment]
Agreed.  This looks great.  At what point do we start listing out the sort options and facets?

**Comment by JessWaggs** [comment]
@rmjaffe  Yes, that would point to the finding aid. I think "Collection guide" is their new preferred term? (Or, at least, it's what we use in Primo)

@chesleyperry I can make some tickets for outlining what should be included in sort options and facets. I imagine sort options will be pretty quick/easy. Facets I imagine will be a bit stickier/require more conversation.

**Comment by kellyChex** [comment]
Yes, there is a ticket to remind us to determine what should be in the facets, https://github.com/UCSCLibrary/dams_project_mgmt/issues/123

You can use that one Jess.

**Comment by JessWaggs** [comment]
Subsequent ticket for Search results mobile: #225
