### ISSUE TITLE
(3) Purchase long term license for full version of Kakadu

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#149]
### Descriptive Summary

We want to purchase a long term license for the JPEG2000 image processing utility Kakadu, which we are currently using in an evaluation capacity. 

### Background 

To serve large images, our server encodes the large TIF files as JPEG2000s, which are faster to read and process when you want to view a small version or a zoomed in corner. The trick is to make the JPEG2000 as fast to process as possible without losing detail from the original TIF. Kakadu is considered the fastest and best JPEG2000 processing library out there, and it was developed for library applications like ours. We want to use it if we can. There is a viable free alternative, OpenJPEG, which we could also use if we need to. It does a solid job but isn't nearly as fast as Kakadu. This would slow some parts of our image interface down. 
In #121 we installed the full version of kakadu with a free six month evaluation license. We are in contact with Graham Morton (graham@kakadusoftware.com), the kakadu sales rep, who has assured us that they will work within our budget and is waiting for us to tell him what that budget looks like for this. 
We heard from UCLA that they pay $5k per year for this service. That sounds a lot higher than would probably be worth it for us, and I was encouraging a much low offer. There is no point comparing this to the price of ContentDM, which is a whole DAMS; this is an image processing utility. It is an important part of our site that will improve the user experience, but it isn't vital to anything at the top of our list of priorities. Don't break the bank for it if they aren't asking us to.

### Acceptance Criteria

This is what done looks like

* [x]  We have negotiated a price with kakadu
* [x]  Contact Kakadu and get quote for license
* [x]   Inform senior management about cost
* [ ]   Process payment
* [ ]  We have obtained a long term license for the kakadu software

### Related Work 
#121 #36

**Comment by kellyChex** [comment]
@chesleyperry To take this ticket on as she needs to look into licensing.

**Comment by chesleyperry** [comment]
Kerry and John have approved a three-year license for the software. 
Kakadu has provided a quote and sent the paperwork to get added to the UCSC Cruzbuy vendor database.
I've accepted the quote.  Kakadu still isn't showing up in Cruzbuy so I've contacted library purchasing to followup.
