### ISSUE TITLE
Determine next steps for UA50 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#15]
**Notes:** 
UA50: schedule meeting with K, T and others to present remodel issues and discuss next steps.  Following their decision, either ask NH to publish collection as is, or continue with remodeling work.  Either way look into developing guidelines for identifying/creating images sets as part of metadata creation workflow.

**Comment by rmjaffe** [comment]
This work has been completed.

**Comment by kellyChex** [comment]
Ok, I moved from Planning to Done.
