### ISSUE TITLE
Evaluate kakadu performance on encoding our large TIF collections

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#150]
### Descriptive Summary

Our next large image ingest will be the first time we are encoding JPEG2000 derivatives using the full kakadu software after we upgraded from the demo (#121). We should plan to set aside time to evaluate and handle any issues this software encounters during our next large image ingest. 

### Background 

We recently upgraded from the demo version of Kakadu (our JPEG2000 image processing software) to the full version. When processing our current collection, the demo version of Kakadu handled the vast majority of the images perfectly, but a small percentage of the tif files required pre-processing before they could be handled properly by the kakadu demo processor. The error messages indicated that this issue would likely be resolved with the full version, so hopefully all of our TIFs can be processed into JPEG2000s successfully. 

### Acceptance Criteria

* [ ] 1000+ large TIF images have been processed using our current version of Kakadu
* [ ] We have made a plan to address any errors that we encountered, and created tickets for implementing that plan

**Comment by kellyChex** [comment]
@chesleyperry To take this ticket on as she needs to look into licensing.

**Comment by rmjaffe** [comment]
@NedHenry If we move forward with licensing Kakadu longer term, would the combined campus history collection ingest be suitable for this evaluation work?  Or put the other way, would it make sense to evaluate Kakadu's performance as a part of the combined campus history ingest work?

**Comment by rmjaffe** [comment]
Based on yesterday's conversation (that we're moving forward with getting a quote and the fact that it is checked as being done on the Kakadu epic card), can I assume that this evaluative work has been done?  Can we close this card? @chesleyperry @NedHenry

**Comment by NedHenry** [comment]
I'm happy with closing this card if everyone is on board with licensing Kakadu, which sounded like the case in our last discussion. There's no point putting aside time for an evaluation if we've already made the decision. 
It does seem like Kakadu is the best & easiest solution, assuming we can get the license relatively cheaply (which sounded likely).

**Comment by rmjaffe** [comment]
I'm gonna close it.  Thanks!

**Comment by NedHenry** [comment]
The other part of the work on this card involves tracking bugs that may come up during future ingest, based on the version of Kakadu we have currently compiled. We may still need to set aside time for theosr tasks, but it probably makes sense to make tickets if/when those problems arise. This ticket can close and act a reference if need be.

**Comment by rmjaffe** [comment]
OK, I think this is covered by #186 Fix ingest of compressed tiffs & jpegs.  You've already added a reference on that card to this one 🥇
