### ISSUE TITLE
Create tickets for collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#151]
### Descriptive Summary

Create and populate tickets for each collection using the collection pre- and post-ingest issue template.

### Background 

Template has been created.  Goals are 1) to transfer information about collections from the collection tracking spreadsheet and other documents into the new tickets; 2) use the collection tickets to track our work going forward and eventually deprecate the tracking spreadsheet and other documents.

### Acceptance Criteria

This is what done looks like

* [ ] Each collection has a ticket
* [ ] Relevant information about each collection has been added to each ticket
* [ ] Create a label, "collection tracking" or something, for these tickets and label them

### Related Work 

#142 Create templates for collection tickets

**Comment by rmjaffe** [comment]
Here is the list of collections needing tickets: https://docs.google.com/document/d/17t_xZkkV_aBU5SBaDJec68fyvrvu5ACxOW61aOAXdvQ/edit

**Comment by kellyChex** [comment]
@rmjaffe To create a final ticket to address second Cabrillo Music Festival collection.
