### ISSUE TITLE
(5) Mock up for collection of collection (groupings) and collection landing pages 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#153]
- Use the Combined Campus Collections as a use case  
- Mock up of collection of collection (groupings) landing page that will link to collection landing pages 
- Mock up of collection landing pages

**Comment by JessWaggs** [comment]
[Group landing page for desktop and mobile in Google Drive](https://drive.google.com/open?id=1SIwKCdk6aNnh_oTidf1jneuiPcYvUmAV)

Goals around this design:
- indicate to user that they can search/browse within the larger group of collections
- expose collections included within the group and provide access points to those collections
- prioritize actionable content (eg. links, search boxes, etc.) on mobile

**Comment by JessWaggs** [comment]
![Screen Shot 2020-01-13 at 12 59 03 PM](https://user-images.githubusercontent.com/6412857/72291584-822d5700-3604-11ea-9f75-7b305be031cd.png)

**Comment by JessWaggs** [comment]
For collection level pages, do we want/need anything beyond what we're already considering for the [Browse page](https://drive.google.com/open?id=1exvHY4OEmMTyDMz0jygeTzsv948aipRc)?

![Screen Shot 2020-01-13 at 3 12 59 PM](https://user-images.githubusercontent.com/6412857/72299947-389a3780-3617-11ea-860f-2b369d6753dd.png)

**Comment by JessWaggs** [comment]
Here's another option that is basically a more robust version of the above Browse. Can go over questions and issues at the mtg tomorrow.

![Screen Shot 2020-01-14 at 10 57 50 AM](https://user-images.githubusercontent.com/6412857/72373359-f62b3600-36bc-11ea-936a-d663ae7455f2.png)

**Comment by JessWaggs** [comment]
Mock up of collection landing page:

![Screen Shot 2020-01-23 at 2 48 31 PM](https://user-images.githubusercontent.com/6412857/73030937-97b63400-3def-11ea-892c-92e5d898108b.png)

**Comment by JessWaggs** [comment]
@chesleyperry @rmjaffe 
Can you take a look at this updated collection landing mock-up?

**Comment by kellyChex** [comment]
@JessWess Would you be able to create stories for these? 

Here's a shell for the Collection Page: https://github.com/UCSCLibrary/dams_project_mgmt/issues/176

**Comment by JessWaggs** [comment]
Sure

**Comment by JessWaggs** [comment]
Subsequent ticket: #231
