### ISSUE TITLE
(5) Customize collection level metadata schema to match work level schema

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#154]
### Descriptive Summary

We want collections to support the same metadata schema as works, defined by our metadata.yml file through ScoobySnacks. Initially, everything will work the same for collection level metadata and work level metadata, including inheritance and indexing. 

### User Story 

As a metadata person, I want to be able to record collection level metadata on the ingest spreadsheet.

### Background 

We extensively customize our work metadata schema, and we keep it up to date using our custom gem ScoobySnacks. Currently, collections have only basic metadata fields attached. We want to alter collections to accommodate our full metadata schema.

The [ingest spec](https://docs.google.com/document/d/1bExRPrnt-9mZvqqssadOxhj7pSnS-9aAUCXbXixipfY/edit#heading=h.xwxemhn3e720) already allows spreadsheet creators to indicate the type of work that is being ingested using the work type column.

### Acceptance Criteria

This is what done looks like

* [ ] Collections can be assigned metadata from our custom schema
* [ ] Works that are members of a collection may inherit collection level metadata when appropriate
* [ ] Collection level metadata is indexed appropriately in Solr for search and display
* [ ] The ingest spec includes a work type "collection" for collection level metadata
* [ ] Metadata entered for a collection appears on the collection landing page within the system
* [ ] Ingest spec doc updated

**Comment by kellyChex** [comment]
We need to determine how long this will take before prioritizing.

**Comment by rmjaffe** [comment]
Just looking over our board -- it looks like this issue and #103 are related, if not two part of the whole.
