### ISSUE TITLE
(8) Pre-Ingest Branson DeCou (MS 38)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#158]
## Collection Information

* Formal collection title: Branson DeCou Archive
* Collection number: MS 38

### Objects

* Type of content (images, audio, albums, etc.): 3,175 images
* Single objects / compound: single
* Special requirements / issues: none noted on collection tracking spreadsheet

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Spreadsheet filename: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/MS_38_DeCou_20201209.xlsx
* Special requirements / issues: Metadata will need to be finalized and (possibly reformatted per the addition of collection-level to the data model & ingest spec) before it is moved to dams_ingest.  

### File Assessment / Technical Processing 

* [x] Files assessed for readiness to move
* [x] Files moved to dams_ingest

* Directory name: dams_ingest/ms0038_decou/
* Special requirements / issues:

### Pre-Ingest

* [x] Metadata spreadsheet(s) moved to dams_ingest: dams_ingest/ms0038_decou/MS_38_DeCou_20201209.xlsx
* [ ] Ned notified; tickets created for collection ingest, QA work, and publication

**Comment by chesleyperry** [comment]
This looks good - I have no changes to the template.  I'll start checking boxes.

**Comment by rmjaffe** [comment]
Cool.  I start making more collection tickets.  I created a [list of collections needing tickets](https://docs.google.com/document/d/17t_xZkkV_aBU5SBaDJec68fyvrvu5ACxOW61aOAXdvQ/edit) in Drive and blued-out the one I did.

**Comment by rmjaffe** [comment]
Student assistant in SC&A is working with Luisa to enhance the metadata for this collection by adding more specific Geonames.  This works should be completed by 12/1/20.

**Comment by rmjaffe** [comment]
Deadline for Geonames enhancement has been extended to 12/3/20.

**Comment by rmjaffe** [comment]
@chesleyperry Ingest metadata is ready to go.
