### ISSUE TITLE
Refactor relationships in BulkOps

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#163]
### Descriptive Summary

We need to make the parent/child relationships in BulkOps associated with the parent work proxy instead of the child proxy. This way, the editing of the parent's list of children can happen only once in the operation instead of each time a child finishes updating/ingesting. 

### Background 

#160 

### Acceptance Criteria

* [ Each parent record is indexed no more than once per operation to re-order its children ]
* [ Ingests or updates including complex objects with tens or hundreds of children can run successfully]

**Comment by NedHenry** [comment]
This issue is part of finishing the problematic parts of #92 and #160

**Comment by NedHenry** [comment]
These changes have been implemented in the "sandbox" staging site. I should prepare and run a simple test operation there before attempting to implement these changes on production.

**Comment by NedHenry** [comment]
I am going to just test the deployment and basic functionality of the site in the sandbox environment right now, then go ahead and deploy this code to production. 
It would take a fair amount of effort to create a representative test operation in the sandbox environment to test whether these changes fix the types of failures we were seeing on the last attempted operation. Also, because the last operation left the collection in a bad state in the production environment, I don't feel the need to be as careful about the possibility of creating a bad state. It would be good to fix it as quickly as possible.

**Comment by NedHenry** [comment]
The changes to the BulkOps code are now live on the production site and ingest server. I am working on testing them with a small portion of the failed MS0020 collection. If it works well, I will use it to automatically re-process all of the MS0020 records which had issues last time around. There may be a little bit of patching and debugging still necessary, but hopefully not very much.

**Comment by kellyChex** [comment]
@NedHenry If there's a way we can help test this please let us know. Else, we can defer to your testing check off and close.
