### ISSUE TITLE
(2) Footer: Desktop

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#165]
### Descriptive Summary

Redesign site footer to match:
![DAMS_Footer_v1](https://user-images.githubusercontent.com/6412857/72830915-9b528b00-3c36-11ea-9e4d-55a599f7d696.png)

Color Palette:
Text & Links: #FFFFFF
Link on hover: underline
Navy blue: #00457C

Fonts:
Family: Roboto
Size: 16px

Links in footer:
Feedback - opens modal containing [LibAnswers widget](https://answers.library.ucsc.edu/admin/product?m=widgets&widget_id=6282)
Accessibility Policy: https://guides.library.ucsc.edu/digitalcollections/policies#Accessibility
Takedown Policy: https://guides.library.ucsc.edu/digitalcollections/policies
Reproduction & Use: https://guides.library.ucsc.edu/speccoll/reproduction-publication
About the UCSC Digital Collections: https://guides.library.ucsc.edu/digitalcollections
UCSC Library GitHub: https://github.com/UCSCLibrary
Digital Collections Login:  http://digitalcollections.library.ucsc.edu/users/sign_in?locale=en

### Background 

Current footer:
![Screen Shot 2020-01-21 at 10 20 52 AM](https://user-images.githubusercontent.com/6412857/72831438-ba055180-3c37-11ea-8b51-d8ff01126c14.png)

### Acceptance Criteria

This is what done looks like

* [x] Footer matches appearance of new design when viewed on desktop display
* [x] Feedback modal opens and behaves as expected
* [x] Links in footer open as expected

### Related Work 

#145 #166

**Comment by rschwab** [comment]
[Pull Request here](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/109)

Screenshots: 
![Firefox_Screenshot_2020-02-06T00-30-21 148Z](https://user-images.githubusercontent.com/515412/73896391-c2fd4200-4837-11ea-9c54-c0d08c2b9830.png)
![Firefox_Screenshot_2020-02-06T00-30-37 655Z](https://user-images.githubusercontent.com/515412/73896401-c85a8c80-4837-11ea-85bf-df87c12a5025.png)

**Comment by NedHenry** [comment]
Ready for QA on the [staging server](http://digitalcollections.library.ucsc.edu)

**Comment by chesleyperry** [comment]
Browser tested on Mac OS Mojave in Chrome, Firefox and Safari.  Can't check in Lambatest until moved to production server.
Meets all acceptance criteria.

**Comment by NedHenry** [comment]
On the staging site where this is deployed, when I load any page that includes the libanswers javascript, I see the following error in Firefox or Chrome's javascript console:

> TypeError: document.addEventListener(...) is not a function
application-be31a7ccdd0607759e76951fd96004a594c3edd5f861145428ff7c85e11c8c2e.js:46:6064
    http://digitalcollections-staging.library.ucsc.edu/assets/application-be31a7ccdd0607759e76951fd96004a594c3edd5f861145428ff7c85e11c8c2e.js:46

**Comment by NedHenry** [comment]
Looks to me like the libanswers.js script (which is now included in our compiled application-XXX.js bundle) expects to be run after the DOM loads, and is trying to access DOM elements, but it's failing because it is currently loaded in the page header.

**Comment by NedHenry** [comment]
Or maybe it was just a few extra parentheses left at the end of the libanswers.js file by mistake

**Comment by NedHenry** [comment]
I removed a pair of apparently extraneous parentheses from the end libanswers.js, and the javascript error I was seeing was resolved. I pushed this change into staging for QA, and it appears to have solved the problem there too. This is ready to push to production AFAIC
