### ISSUE TITLE
(2) Footer: Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#166]
### Descriptive Summary

Redesign footer viewed on mobile to match:
![Screen Shot 2020-01-21 at 10 26 52 AM](https://user-images.githubusercontent.com/6412857/72831880-97c00380-3c38-11ea-852b-88b29d7d0171.png)

Color Palette:
Text & Links: #FFFFFF
Link on hover: underline
Navy blue: #00457C

Fonts:
Family: Roboto
Size: 16px

Links in footer:
Feedback - opens modal containing LibAnswers widget
Accessibility Policy: https://guides.library.ucsc.edu/digitalcollections/policies#Accessibility
Takedown Policy: https://guides.library.ucsc.edu/digitalcollections/policies
Reproduction & Use: https://guides.library.ucsc.edu/speccoll/reproduction-publication
About the UCSC Digital Collections: https://guides.library.ucsc.edu/digitalcollections
UCSC Library GitHub: https://github.com/UCSCLibrary
Digital Collections Login: http://digitalcollections.library.ucsc.edu/users/sign_in?locale=en

### Background 

Current footer on mobile:
![Screen Shot 2020-01-21 at 10 25 26 AM](https://user-images.githubusercontent.com/6412857/72831771-5f202a00-3c38-11ea-9f2b-2eae66220cf5.png)

### Acceptance Criteria

This is what done looks like

* [ ] Footer matches appearance of new design when viewed on mobile device
* [ ] Feedback modal opens and behaves as expected
* [ ] Links in footer open as expected

### Related Work 

#145 #165

**Comment by rschwab** [comment]
[Pull Request here](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/109)

Screenshots: 
![Firefox_Screenshot_2020-02-06T00-31-57 352Z](https://user-images.githubusercontent.com/515412/73896368-a6f9a080-4837-11ea-9fc3-fd1011bf8251.png)
![Firefox_Screenshot_2020-02-06T00-32-09 090Z](https://user-images.githubusercontent.com/515412/73896375-ac56eb00-4837-11ea-91ae-bf770b01c98b.png)

**Comment by NedHenry** [comment]
Ready for QA on the staging server

**Comment by chesleyperry** [comment]
Browser tested all links on iPhone 8, ios 13.3.1  - can't test in Lambatest right now because the staging server is limited to campus ethernet and VPN.  

All links working.  Let's deploy to production!
