### ISSUE TITLE
(2) Header: Desktop

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#167]
### Descriptive Summary

Redesign header on desktop to match:

![Screen Shot 2020-01-21 at 10 29 44 AM](https://user-images.githubusercontent.com/6412857/72832071-f5ece680-3c38-11ea-95e8-633f2e9945a2.png)

Color Palette:
Gray Font Color (search box placeholder text): #757575
Link color: #FFFFFF
Link on hover: underline
Gold (dot between menu items): #FFCC33
Navy blue: #00457C
Lighter blue: #02779E

Fonts:
Family: Roboto
UNIVERSITY LIBRARY: 30 + bold
DIGITAL COLLECTIONS: 42 + bold
Menu items: 16 + bold
Placeholder: 18

UCSC logo source: https://communications.ucsc.edu/visual-design/logos-imagery/

Links:
UCSC logo: ucsc.edu
UNIVERSITY LIBRARY: https://library.ucsc.edu/
DIGITAL COLLECTIONS: http://digitalcollections.library.ucsc.edu/
Browse Collections: http://digitalcollections.library.ucsc.edu/
Contact Us: opens same modal as "Feedback" in footer (#165 )

Search box: match behavior of current site search box

### Background 

Current header on desktop:
![Screen Shot 2020-01-21 at 10 47 52 AM](https://user-images.githubusercontent.com/6412857/72833564-e91dc200-3c3b-11ea-91c3-55e2639e2bfe.png)

### Acceptance Criteria

This is what done looks like

* [x] Header appearance on desktop matches mock-up
* [x] Contact Us link opens modal box showing LibAnswers widget
* [x] Search box behaves as expected (matching current site)
* [x] Other links in header open as expected

### Related Work 

#145

**Comment by kellyChex** [comment]
Added UI/UX overhaul label and moved to backlog - For future reference, this is done under Milestone and Projects.

**Comment by rschwab** [comment]
[Pull Request](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/116)

Screenshots:
![Firefox_Screenshot_2020-03-04T18-15-12 513Z](https://user-images.githubusercontent.com/515412/75910886-7f303500-5e03-11ea-82c2-7fbff78e0b93.png)

**Comment by rschwab** [comment]
Note the UCSC logo has more padding than in the mockup. The logo from the PR dept includes this padding to enforce their usage policies. Let me know if you want to override that and have me crop it closer as per the mockup. I also left the search submit button in place, for usability, but put the label itself in screen-reader only mode.

**Comment by rschwab** [comment]
Oops one more note. I used the font sizes as described for full size, and scaled them as needed on smaller screens. On full size they look different than the mockup - I don't know why there is that discrepancy.

**Comment by NedHenry** [comment]
@chesleyperry This and #172 should be ready for QA in staging if you have the chance (no hurry)
.

**Comment by chesleyperry** [comment]
I checked Mac Safari, Chrome, and Firefox.  No issues and looks great.  I think it can be deployed to production
