### ISSUE TITLE
(2) Mock ups for initiating requests to aeon 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#171]
# User Story: 
As a UCSC user, I can make a request to view the Cabrillo Music Festival collection through the Collection landing page and work page (Admins will not see these request buttons) 

# Acceptance Criteria: 
- [ ] Check with Jess if we should mock this

**Potential scenarios:** 
1. Initiate request from work page:
![Screen Shot 2020-02-03 at 10 34 58 AM](https://user-images.githubusercontent.com/9621070/73680324-e4600180-4670-11ea-8a6e-9bf11e26385b.png)
2. Initiate request from collections landing page: 
![Screen Shot 2020-02-03 at 10 37 21 AM](https://user-images.githubusercontent.com/9621070/73680622-6f40fc00-4671-11ea-8929-e5e9c0fd9966.png)

UCSC Demo Screenshots: 
![Screen Shot 2020-01-22 at 5 00 35 PM](https://user-images.githubusercontent.com/9621070/72948093-02f0ff00-3d39-11ea-99e7-99c97f83632d.png)
^ Do we want this same modal form so users are able to make a special request, ask a question, etc. or do we bypass this?

**Comment by JessWaggs** [comment]
Mock up showing Request button placement for collection landing page in new UI:

![Screen Shot 2020-02-03 at 3 53 38 PM](https://user-images.githubusercontent.com/6412857/73701206-9dd4cc00-469d-11ea-9f88-7da1790d6b92.png)

**Comment by JessWaggs** [comment]
Mock up showing Request button placement for A/V object pages in new UI:

![Screen Shot 2020-02-03 at 4 08 40 PM](https://user-images.githubusercontent.com/6412857/73701807-944c6380-469f-11ea-8ad4-ccba5efa83b5.png)

**Comment by JessWaggs** [comment]
Mobile A/V object page in new UI:

![Screen Shot 2020-02-03 at 4 14 37 PM](https://user-images.githubusercontent.com/6412857/73702054-5996fb00-46a0-11ea-9616-ad479c3af126.png)

**Comment by rmjaffe** [comment]
@kellyChex @JessWaggs NIce work!  I think the position of the buttons on both the current displays and the on the overhaul mock-ups, looks good.  On the first image, the current work page display, I really like the idea of the child work link being the request link.

**Comment by kellyChex** [comment]
@JessWaggs Awesome!! I've changed the title to mock ups for Aeon request and moved to Done so that we get credit for this.
