### ISSUE TITLE
(2) Header: Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#172]
### Descriptive Summary

Redesign header on mobile to match:

![Screen Shot 2020-01-23 at 2 21 40 PM](https://user-images.githubusercontent.com/6412857/73029168-e9f55600-3deb-11ea-8ccd-58364133d5be.png)

1) header in its default state
2) header when user clicks "Search" - displays search box below text in light blue portion of header
3) header when user clicks the hamburger menu in the upper left - displays vertical list of menu options (currently just Contact Us and Browse Collections)

See color palette and links in #167  

### Background 

Current header in mobile:

![Screen Shot 2020-01-23 at 2 26 21 PM](https://user-images.githubusercontent.com/6412857/73029443-5f612680-3dec-11ea-9e47-8032936926fa.png)

### Acceptance Criteria

This is what done looks like

* [x] Header appearance on mobile matches mock-up
* [ ] Clicking "Search" opens search box
* [x] Clicking hamburger menu displays menu links
* [x] Contact Us link opens modal box showing LibAnswers widget
* [x] Search box behaves as expected (matching current site)
* [x] Links in hamburger menu open as expected

### Related Work 

#145 #167

**Comment by rschwab** [comment]
[Pull request](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/116)

Screenshots:
![Firefox_Screenshot_2020-03-04T18-15-30 819Z](https://user-images.githubusercontent.com/515412/75910806-5f990c80-5e03-11ea-8343-17d96d284eae.png)
![Firefox_Screenshot_2020-03-04T18-15-43 226Z](https://user-images.githubusercontent.com/515412/75910814-61fb6680-5e03-11ea-8296-075f848f5611.png)

**Comment by chesleyperry** [comment]
I checked iOS Safari and Chrome on both iPhone and iPad mini.  Looks and functions as expected.  I think it can be deployed to production.
