### ISSUE TITLE
(1) Public Hitchcock and Holmes Collection

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#174]

**Comment by kellyChex** [comment]
@chesleyperry to do final QA

**Comment by chesleyperry** [comment]
Browser test:  
No problems playing audio files or displaying records.
All parent and child work links function.
All sound files play well.
Links in metadata record are not working on mobile.  I just realized this is the case for all collections on mobile so I'm opening another ticket with screenshots.  I think we can consider this closed.
