### ISSUE TITLE
(5) Apply new Collection landing page design: Desktop - Deadline 10/15/20

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#176]
### Descriptive Summary

As an end user, I want to view all items within a collection so that I can browse and search for items within that single collection.

Redesign collections page to match in Desktop:

<img width="659" alt="Screen Shot 2020-05-18 at 3 03 06 PM" src="https://user-images.githubusercontent.com/6412857/82265096-11cc7480-991b-11ea-9e52-77289526d129.png">

Styles:
Square Thumbnails: 150px x 150px

### Background 

Current collections page:

<img width="1036" alt="Screen Shot 2020-02-14 at 5 10 54 PM" src="https://user-images.githubusercontent.com/6412857/74579441-57aa2300-4f4f-11ea-82b6-64b4830b59a6.png">

### Acceptance Criteria

This is what done looks like

* [x] Display facets for collection level pages
* [x] Move collection search box to be above the exposed facets
* [x] Remove breadcrumbs, "Collection details" box, item count and update date below title
* [x]  Move and restyle relevance, results, and display option buttons (and eliminate Masonry option?)
* [x] Re-style pagination to match mock up

### Related work

Collection description box: #222 
Collection landing page for mobile: #276 
Original mock up ticket: #153 
[Mock up in Google Drive](https://drive.google.com/open?id=1G0pN__RJ4f6OPUYDLuqh2zlHhqplPtPU)

**Comment by rschwab** [comment]
Which facets should be included on this page?

**Comment by JessWaggs** [comment]
@rschwab I think including the facets that are displayed in a keyword search results set are fine.

![Screen Shot 2020-07-08 at 11 38 04 AM](https://user-images.githubusercontent.com/6412857/86957524-b5622600-c10f-11ea-8011-e7634c8c343c.png)

Long term, #195 will determine facets and labels; but that is still in planning.

**Comment by rschwab** [comment]
Pull request linked above. Note: The masonry option still exists - I wasn't able to find where to remove it and the instructions here are a little ambiguous. Please let me know if it should indeed be removed and I'll work on an update to do so. This pull request also does not address the resizing of thumbnails in the search results.

**Comment by chesleyperry** [comment]
Bug report based on QA notes on draft page:

In the facets, if you click "more>>".  You get a "network error" pop-up system message. 

Because of this error, we have hidden that facets panel.

**Comment by chesleyperry** [comment]
Issue report:
For previously published collections that have the new landing page design added to them, the dimensions of some thumbnails are off and the photo looks squished.  Here's an example from UCSC Photography Services Photos:
<img width="252" alt="Screen Shot 2020-10-06 at 11 40 30 AM" src="https://user-images.githubusercontent.com/18403313/95246177-fd551f80-07c8-11eb-8982-9b7ba1051d73.png">
