### ISSUE TITLE
Apply Search Screen: Mobile (placeholder)

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#187]
### Descriptive Summary

A short description of the feature, including wireframes, screenshots, or videos if available.

Consider using the User Story format:

As a < type of user >, I want < some goal > so that < some reason >.

### Background 

Additional information about the reason for the feature or story. 

### Acceptance Criteria

This is what done looks like

* [ ] I see these views
* [ ] When a user does this, that happens

### Expected Behavior 

Helpful when reporting bugs to explain the expected behavior 

### Actual Behavior

Helpful when reporting bugs to explain the actual behavior 

### Steps to reproduce 

Please list the steps to reproduce the issue.

### Related Work 

Mention any other tickets that are related to this issue or story.

**Comment by rmjaffe** [comment]
@JessWaggs This looks like a placeholder for #225 Apply new search result: mobile.  Can this ticket be closed out and moved to done?

**Comment by JessWaggs** [comment]
Yep! Thanks : )
