### ISSUE TITLE
Add metadata property rightsStatus; retroactively add rightsStatement.org values to works that have been ingested

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#188]
### Descriptive Summary

We decided to add rightsStatement.org graphics/values to the download popups without investigating the metadata impacts or whether or not we had this data for each work/collection.  SCA has assigned values for each collection; now they need to be included in the metadata records for the works that have already been ingested.

### Acceptance Criteria

* [ ] Add a new metadata property, rightsStatus (http://purl.org/dc/terms/license), to the metadata schema. 

Retroactively add rightsStatus to metadata for works that have already been ingested. Apply the following:
* [ ] UA 50: http://rightsstatements.org/vocab/InC/1.0/
* [ ] MS 20: http://rightsstatements.org/vocab/InC/1.0/
* [ ] Harry Mayo: http://rightsstatements.org/vocab/InC/1.0/
* [ ] Santa Cruz County History: http://rightsstatements.org/vocab/NKC/1.0/
* [ ] Cabrillo: http://rightsstatements.org/vocab/InC/1.0/
* [ ] Hitchcock & Holmes: http://rightsstatements.org/vocab/InC-RUU/1.0/
* [ ] Porter College: http://rightsstatements.org/vocab/UND/1.0/
* [ ] Shakespeare SC: http://rightsstatements.org/vocab/InC/1.0/

### Related Work 

#175 Adding this metadata property/values to spreadsheets for pre-ingest collections.

**Comment by NedHenry** [comment]
This shouldn't be too difficult on my end, but it will require saving and re-indexing all of our records, which will take a bit of time in the background. I'll start a background script to update all of our records with this new metadata, then babysit it as it runs for a day or two. I'd probably point this at a 3. 
Also, I'd like to add as a note to myself that when updating an object's descriptive metadata only in a way that should not affect the object's parents or children at all, I can temporarily turn off "nested indexing" to save a lot of time and computing power when the object re-indexes.

**Comment by rmjaffe** [comment]
This should probably be hold until we resolve #137 Reconcile config file.

**Comment by rmjaffe** [comment]
@NedHenry Can you confirm that this was done as part of #285 Apply collection level metadata for older collections?  I forgot that this card was kicking around, but the rightsStatement.org URI were included on the collection metadata overlay spreadsheet.

**Comment by rmjaffe** [comment]
@NedHenry This was completed as part of #285 Apply collection-level metadata to older collections, correct?
