### ISSUE TITLE
Review combined campus history collections for possible remodel

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#19]
### Descriptive Summary

As a user, I don't want to have to look at 15 images of the same thing.  I would rather see one image (hopefully the "best" image), with the option of looking at the rest of the images.

### Background

Some material with in a couple of the collections represented on this spreadsheet may be worth grouping, e.g. UA 128. Before committing to this work, we want to do a feasibility scan.

### Acceptance Criteria

* [ ] Metadata spreadsheet has been reviewed to estimate number of groups and ease of grouping
* [ ] Recommendation on grouping made to DAMS team and Special Collections

### Related Work

This work will need to wait until #12 Updating filenames/fixing issues has been completed.  Can be done in parallel with #13 Move files into one directory on dams_ingest

**Comment by rmjaffe** [comment]
We've decided not to do this as it will delay publication of the collection.
