### ISSUE TITLE
(2) Mock-up for Search Results in desktop 

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#199]
### Descriptive Summary

Create mock-up for search results display in desktop

This is what done looks like

* [x] Mock-up for search results in desktop

### Related Work 

#147

**Comment by JessWaggs** [comment]
![Screen Shot 2020-02-05 at 8 54 50 AM](https://user-images.githubusercontent.com/6412857/73863733-611be880-47f5-11ea-99db-afead359b9e0.png)

**Comment by JessWaggs** [comment]
@rmjaffe @chesleyperry 

- Space under each thumbnail for about 36 characters across two lines, most of our titles would be cut off using ellipses (would be good to think about a quick interaction to see remainder of title, like a pop-up on hover? Calisphere overlays full title over thumbnail on hover)
- I removed the "search inside these results" box from the initial concept; I don't see any other Samvera DAMS offering that kind of box (and I question its utility when we have facets)
- Thumbnails are all 150px x 150px  -- do we like that size? (matches Calisphere)
- Default display grid of 24 (can be adjusted through drop-down)
- Pagination buttons at the bottom of the grid, including previous and next arrows
- Matching Collections as a slideshow, 5 up by default, clicking right arrow will expose next 5 (or less) and cause left arrow to appear

**Comment by JessWaggs** [comment]
(Showing above the fold on a typical viewport height)

![Screen Shot 2020-02-05 at 9 16 28 AM](https://user-images.githubusercontent.com/6412857/73865538-46973e80-47f8-11ea-8a91-9185549a3394.png)

**Comment by chesleyperry** [comment]
Grey text should be darker (in the "Matching Collections" and "235 search results...")  The color you're using (#919191) has a contrast ratio of 2.86:1, which is too low.  #707070 meets the 4.5:1 required ratio.
I like the idea of a hover over that gives the full title.  
I think it's fine to remove the search inside these results - agreed that facets should do the same thing.
150px x 150px thumbnails are good for me.
All other noted items are good for me.

**Comment by rmjaffe** [comment]
I'm on board with Sue's feedback.  I think these look good.  My only question is more of a metadata/indexing concern: how do we anticipate that the matching collections will be matched?  If a collection contains a work with the subject term "protest" the collection will then be a match? Is that a viable strategy? -- may want to check with Ned. Or would we need to assign broad subject terms to the collections themselves which would included in the collection metadata?

**Comment by JessWaggs** [comment]
@chesleyperry Thanks for checking the contrast! I switched both to black, for simplicity : )
@rmjaffe Good questions... [Duke](https://repository.duke.edu/dc?utf8=%E2%9C%93&q=north+carolina&search_field=all_fields) presents matching collections in their Samvera. @NedHenry Do you have an inside scoop on this? Is there a standard way for doing this?

**Comment by JessWaggs** [comment]
Updated mock-up to change gray text to black:

![Screen Shot 2020-02-05 at 1 24 50 PM](https://user-images.githubusercontent.com/6412857/73884874-9affe580-481b-11ea-99fb-098fef07423b.png)

**Comment by kellyChex** [comment]
@chesleyperry Wants to run this against an accessibility test before giving final approval.

**Comment by NedHenry** [comment]
I looked into the matching collections question, and took a quick look at how Duke is doing it. 
In response to Rachel, it **is** viable to have a collection match a search term if any of its child works have subjects that match that term. We just need to decide which metadata fields from the works will cause the collection to be matched (e.g. subject headings in this example). Also, if we do it this way we will have to re-index each collection after we change the metadata from works inside it, and this re-indexing would take some time. Still, I think that all of that is totally acceptable given our workflows, and that this is the best way to implement this functionality.

**Comment by kellyChex** [comment]
@JessWaggs To make a story for this. Please include Ned's considerations as a note for that ticket.
