### ISSUE TITLE
(5) Pre-Ingest Kofsky images (MS 312)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#201]
## Collection Information

* Formal collection title: Frank Kofsky Audio and Photography Collection of the Jazz and Rock Movement
* Collection number: MS 312

### Objects

* Type of content (images, audio, albums, etc.):  398 images
* Single objects / compound: Single
* Special requirements / issues: Nope!

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Special requirements / issues: Subject terms are mixed within a single column on the metadata spreadsheet.

### File Assessment / Technical Processing 

* [x] Files assessed for readiness to move
* [x] Exif data evaluated 
* [x] Reproduction images evaluated and replaced original image if appropriate
* [x] Files moved to dams_ingest

* Directory name: dams_ingest/ms0312
* Special requirements / issues: 

### Pre-Ingest

* [x] Metadata spreadsheet(s) moved to dams_ingest
* [ ] Ned notified; tickets created for collection ingest, QA work, and publication

**Comment by rmjaffe** [comment]
@chesleyperry @afrebert Hi, I've finished up the spreadsheet, it's in the pre-ingest folder on the DOMTP share: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/MS_312_Kofsky_Images_20201106.xlsx

**Comment by afrebert** [comment]
@rmjaffe @chesleyperry Hi! I'm done with file assessment/technical processing. Files look good and match spreadsheet. Thanks!

**Comment by chesleyperry** [comment]
I moved the spreadsheet into dams_ingest:
/dams_ingest/ms0312/MS_312_Kofsky_Images_20201106.xlsx

**Comment by rmjaffe** [comment]
Will create publication card today :)
