### ISSUE TITLE
(8) Pre-Ingest Alexander Lowry (MS 188), Vester Dick (MS 235); Chuck and Esther Abbott (MS 39)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#204]
## Collection Information

* Collection title: Alexander Lowry photographs (MS 118); Vester Dick collection (MS 235); Chuck and Esther Abbott slide collection (MS 39)

### Objects

**Lowry**
* Type of content (images, audio, albums, etc.): 35 images
* Single objects / compound: Single
* Special requirements / issues: Following files are in the files directory but not listed on the unremediated metadata spreadsheet: ms0188_pho_0025.tif
ms0188_pho_0026.tif
ms0188_pho_0027.tif
ms0188_pho_0028.tif
ms0188_pho_0029.tif
ms0188_pho_0030.tif

We will need to decide what to do with these addition photos:  if they are to be ingested, they will need to be cataloged.

**Vester Dick**
* Type of content (images, audio, albums, etc.): 36 images
* Single objects / compound: single

**Abbott**
* Type of content (images, audio, albums, etc.): 115 images
* Single objects / compound: Simple
* Special requirements / issues: Missing TIFF files found. Related Resource metadata element contains links to oral histories in eScholarship

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Spreadsheet filename: //artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/Local_History_Collections_20201005.xlsx
* Special requirements / issues:

### File Assessment / Technical Processing 

* [x] Files assessed for readiness to move
* [x] Files moved to dams_ingest

* Directory name: //dams.library.ucsc.edu/dams_ingest/local_history_collections
* Special requirements / issues:

### Pre-Ingest

* [x] Metadata spreadsheet(s) moved to dams_ingest
* [ ] Ned notified; tickets created for collection ingest, QA work, and publication

**Comment by rmjaffe** [comment]
Combined with other local history collections into a single ingest; updated card accordingly.

**Comment by chesleyperry** [comment]
Following photos are in the diginit2/MS0188 Alexander Lowry directory but are campus photos, and not Santa Cruz County Photos.  They do not seem to be published in CONTENTdm or the DAMS campus history collection.  For now, I'll move them into a separate folder. @tmariamora, @katedundon  and @rmjaffe Do you want to eventually add them to the MS188 ditial collection or finding aid?
ms0188_pho_0025.tif
ms0188_pho_0026.tif
ms0188_pho_0027.tif
ms0188_pho_0028.tif
ms0188_pho_0029.tif
ms0188_pho_0030.tif

**Comment by tmariamora** [comment]
Hi Sue, 

If you send me the path once you've moved them I can review to try and determine if they really are from MS188.

Thanks.

Teresa

**Comment by chesleyperry** [comment]
> Hi Sue,
> 
> If you send me the path once you've moved them I can review to try and determine if they really are from MS188.
> 
> Thanks.
> 
> Teresa

Path for photos in question: //artifacts2.library.ucsc.edu/diginit2/ms0188_alexander_lowry/Campus_Photos_not_DAMS_ingested
Path for the spreadsheet that describes them:
//artifacts2.library.ucsc.edu/diginit2/ms0188_alexander_lowry/ms188_alexander_lowry_metadata.xls

**Comment by chesleyperry** [comment]
Notes on ms0039 Abbott filenaming:
the filenaming on this collection was very inconsistent (some leading zeroes, some not).  I updated the filenames to match the spreadsheet, rather than updating both to bring them into conformity with best practices.

**Comment by tmariamora** [comment]
Hi all,

I've reviewed more closely and the identified photos are indeed described in the FA. I was able to find all but one of the images in CDM; see links below. I'm not sure how we want to proceed with the one item not currently in CDM but it could certainly be added to Campus History along with the others.

ms0188_pho_0025.tif: http://digitalcollections.ucsc.edu/digital/collection/p265101coll25/id/194/rec/19
ms0188_pho_0026.tif
ms0188_pho_0027.tif: http://digitalcollections.ucsc.edu/digital/collection/p265101coll25/id/196/rec/11
ms0188_pho_0028.tif: http://digitalcollections.ucsc.edu/digital/collection/p265101coll25/id/197/rec/1
ms0188_pho_0029.tif: http://digitalcollections.ucsc.edu/digital/collection/p265101coll25/id/198/rec/13
ms0188_pho_0030.tif: http://digitalcollections.ucsc.edu/digital/collection/p265101coll25/id/193/rec/20

**Comment by rmjaffe** [comment]
Hmm.

This presents an interesting situation in which we would have one collection, MS 188, of which some images would belong to one collection of collection or supra-collection, and other images to another supra-collection.

I think before we do anything with these 5-6 images or ingest the combined SC County history collections spreadsheet, we'll want to consult with @NedHenry.  I'd like to get his take on how to best handle this.

Thanks for investigating @tmariamora!

**Comment by rmjaffe** [comment]
@chesleyperry I put the six outstanding Lowry images (those that will connected to the campus vs. the local history bucket) on a second, new spreadsheet.  It's in the DOMTP share: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/MS_188_Lowry_Campus_20210111.xlsx

There's still a few metadata pieces remaining on the spreadsheet for the rest of the material -- let me know when you and Angelika are finished with your work and I'll wrap up my work on the sheet.  I don't want to end up versioning!

**Comment by chesleyperry** [comment]
Filenames for all three collections checked against the spreadsheet - no issues with the spreadsheet but I did rename several of the Chuck and Esther Abbott images to match the spreadsheet.
Exiftool run on modified tiff directories for all three collections.  Had issues with it hanging on the Vester Dick folder until I renamed the directory and took out special characters ()?  Once this collection is ingested, we should rename the directory on diginit2 to ms0235 to make it consistent with our current practices.
Filenames for the 4th collection (Lowry Campus) checked against spreadsheet (smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/MS_188_Lowry_Campus_20210111.xlsx). 
 No issues.

**Comment by rmjaffe** [comment]
@chesleyperry Once I get the info from SC&A, I'll update the ingest spreadsheet with collections descriptions and finding aid links.  After that it should be ready to go.

@NedHenry & @chesleyperry I'm thinking it would be a good idea to create a separate ingest card for the Lowry campus stuff, i.e. the six images from MS 188 that will belong to the campus history super-collection vs. the county history one.  Would we want a second ticket to reflect the work needing to be done to associate the works in the MS 188 collection with different super-collections?  Or would it suffice to include this on the new ingest ticket?

**Comment by rmjaffe** [comment]
Spreadsheet has been updated: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/Local_History_Collections_20201005.xlsx

This should be used as the representative image for the county history collection of collections:  http://digitalcollections.ucsc.edu/digital/collection/p265101coll23/id/156/rec/41
