### ISSUE TITLE
(1) Update journey maps 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#21]
### Notes

Jess has all the data to make the changes. Need to format.

**Comment by JessWaggs** [comment]
Revised version now available in Drive: https://drive.google.com/a/ucsc.edu/file/d/1LsprSYfFj-O8oP-W0KCxXj0fg-NnOGs6/view?usp=sharing

**Comment by kellyChex** [comment]
@JessWaggs Do you think we can capture any of these feedback in stories? i.e., help users with citations, making the images larger, etc.?

**Comment by JessWaggs** [comment]
Yes - this doc attempts to show how/why specific UI/UX recommendations were made. But I'm not sure where to capture those recommendations. Should I add them to the [Epics Board](https://docs.google.com/spreadsheets/d/1BAS7e5dh1DvwJLWFOS3B8bVtUQgVOoKoeslAwC2iJFY/edit#gid=355192470)?

**Comment by kellyChex** [comment]
@JessWaggs Let's discuss when we're both back in town. I created #95 to give it the attention it deserves ;)
