### ISSUE TITLE
Links under "About this item" on work display page not working on phone browsers

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#218]
### Descriptive Summary

Links under "About this item" on the work display page do not work in phone browsers. Tablets and desktop browsers are not affected by this bug. Nothing happens when a user clicks on "More information" or Linked titles, creators, etc.

### Background 

Browsers and devices checked:
iOS and Safari (iphone 8)
iOSand Chrome (iphone 8)
iOS and Chrome (ipad)
Android 9 and Chrome (Google Pixel 3A)
Samsung Galaxy S10

### Acceptance Criteria

This is what done looks like

* [ ] All links on the page function from any mobile device

### Actual Behavior

See this screenshot:
![mobile_screenshot](https://user-images.githubusercontent.com/18403313/74291049-88d4ea00-4ce8-11ea-913e-87fbe7fd6b30.png)

**Comment by rschwab** [comment]
Here's the [pull request to fix this one](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/113).
