### ISSUE TITLE
(3) Mock ups for collection landing pages 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#22]
### Acceptance Criteria:

Create 2 Mocks Ups from the following collection pages: 

* [ ] Harry Mayo Surfing Photography Collection 
* [ ] Shakespeare Cruz records 
* [ ] Ruth-Marion Baruch and Pirkle Jones Photographs
* [ ] UC Santa Cruz Photography Services Photographs
* [ ] Santa Cruz County historic photograph collection 
 * [ ] Porter College dedication photographs

### Notes

- Need to determine if this is necessary. How much effort will it be to implement this? Who will do the CSS implementation. 
- Determine what collection-level metadata we want to display on that page/bring into the system
- Then, how to we bring that metadata in (likely by including it on the metadata ingest spreadsheets, which would require that we update the ingest spec to accommodate collection-level metadata).
- Most of the collection-level contextual metadata would be sourced from the related finding aids.  For example, here's the finding aid for Harry Mayo: https://oac.cdlib.org/findaid/ark:/13030/c85q4zgp/

**Comment by kellyChex** [comment]
- [ ]

**Comment by rmjaffe** [comment]
@kellyChex @JessWaggs If I'm not mistaken, I think this work was done as part of #153 Mock up for collection of collection and collection landing pages.  I'm going to close this ticket and move it to done; however, it is is still active, please re-open it.
