### ISSUE TITLE
(2) Create Collection Landing Page Description Box - Deadline 10/15/20

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#222]
### Descriptive Summary

As an end user, I can see all items from a collection displayed under a box that describes the collection.

The Description Box is the part outlined in red:

<img width="909" alt="CollectionBox" src="https://user-images.githubusercontent.com/6412857/74579237-09485480-4f4e-11ea-8de6-323c0481277b.png">

All content in the box comes from the Collection level metadata.
Collection Title: [element]
Thumbnail: [element]
Collection Description/Summary: [element]
Collection Guide Link: [element]

Styling:
Gray box background: #F7F7F7

### Background 

Current collection landing page:
<img width="1036" alt="Screen Shot 2020-02-14 at 5 10 54 PM" src="https://user-images.githubusercontent.com/6412857/74579065-fd0fc780-4f4c-11ea-96fb-654a101ac302.png">

### Acceptance Criteria

This is what done looks like

* [ ] Collection Description Box appears on collections pages
* [ ] Collection Description Box displays appropriate thumbnail
* [ ] Collection Description Box displays appropriate title
* [ ] Collection Description Box displays appropriate summary/description
* [ ] Collection Description Box displays working link to finding aid in OAC

### Related Work

#176

**Comment by kellyChex** [comment]
This ticket is waiting on the second CMF collection to be completed:  https://github.com/UCSCLibrary/dams_project_mgmt/issues/242

**Comment by rschwab** [comment]
Pull request linked above.

Screenshot:
![Firefox_Screenshot_2020-09-17T23-37-21 861Z](https://user-images.githubusercontent.com/515412/93538960-4c174400-f904-11ea-894b-8317c60e08f0.png)
