### ISSUE TITLE
(3) Apply new search results page: Desktop

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#223]
### Descriptive Summary

Style the portion of the search results page in the red box to match the mock-up on desktop:

![SearchResults](https://user-images.githubusercontent.com/6412857/76568430-103f8580-646e-11ea-9818-6387a6b38724.png)

Styles:
Light gray (button/drop-down menus): #F7F7F7
Square Thumbnails: 150px x 150px
Dark gray (pagination): #757575

### Background 

Current search results page:

<img width="992" alt="Screen Shot 2020-02-14 at 5 34 26 PM" src="https://user-images.githubusercontent.com/6412857/74579721-9d67eb00-4f51-11ea-8099-38d62e892ec9.png">

### Acceptance Criteria

This is what done looks like

* [ ] Default to displaying 24 items per page (or 20 would be fine if that's easier)
* [ ] Remove "filtering by" box
* [ ] Display square thumbnails: 150px x 150px 
* [ ] Move pagination buttons to bottom of the grid and restyle
* [ ]  Restyle Sort by / View # / View type buttons
* [ ] The user's search term is displayed in both the header search box (pink box in mock-up) and next to the number of results

### Related Work 

Styling of titles: #249
Matching Collections Box: #224 
Search results on mobile: #225 
Facet styling: #200

**Comment by kellyChex** [comment]
@JessWaggs to consider the following
- Flesh the acceptance criteria for this ticket out 
- Consider writing a ticket for this index section:
![Screen Shot 2020-03-11 at 4 33 01 PM](https://user-images.githubusercontent.com/9621070/76473561-12dea400-63b6-11ea-81cc-314ffee41863.png)
- Consider where these tickets fit in to all this: https://github.com/UCSCLibrary/dams_project_mgmt/issues/123 (Determine search facets requirements) and https://github.com/UCSCLibrary/dams_project_mgmt/issues/200 (mock up of search facet) You might find you can close some of these tickets.

**Comment by JessWaggs** [comment]
@rschwab The 150x150 was just what I did for the mock up. Feel free to change the size, so long as it's square : )

**Comment by rschwab** [comment]
Pull request linked above.

Screenshots:
![Firefox_Screenshot_2020-11-17T23-55-22 347Z](https://user-images.githubusercontent.com/515412/99464815-d91f4f00-28ed-11eb-80ca-4a0fc6427055.png)

**Comment by JessWaggs** [comment]
This looks really good!

Is it possible to change the default results retrieved to 20 rather than 10? Or is that more of a system-wide change that would be better in a separate ticket?

**Comment by rschwab** [comment]
One notable difference is that with the thumbnail size, the container size, and the padding, only 4 fit on a line. I can change the 'justify content' rule from start to space between, if you'd prefer them spaced out evenly instead of left-aligned.

**Comment by rschwab** [comment]
@JessWaggs That's a mistake I made when creating the screenshot. The default is set at 24 now, but I had switched it at some point to make sure I didn't break it.

**Comment by JessWaggs** [comment]
I think 4 per row is fine. Even spacing might look nice though, I like that idea to try.

Great about the 24 per page! I think users will really like have more results on each page.

**Comment by rschwab** [comment]
@JessWaggs Here is space evenly (I used 10 per page again to show what an incomplete line looks like):
![Firefox_Screenshot_2020-11-18T00-52-33 577Z](https://user-images.githubusercontent.com/515412/99468437-6f0aa800-28f5-11eb-8157-fadc33b68a4a.png)


And here is centered:
![Firefox_Screenshot_2020-11-18T00-53-06 065Z](https://user-images.githubusercontent.com/515412/99468482-89dd1c80-28f5-11eb-887e-143860bab700.png)

**Comment by JessWaggs** [comment]
I think the evenly spaced looks good!

**Comment by NedHenry** [comment]
This is now deployed to staging for QA:
<img width="1626" alt="Screen Shot 2020-12-02 at 11 50 15 AM" src="https://user-images.githubusercontent.com/6326776/100926844-e36a4d00-3498-11eb-9bc9-6a4b390ff91f.png">

**Comment by JessWaggs** [comment]
I did a few searches and I didn't see any problems!

I look forward to when we can integrate the check boxes into the facets - I think that will make the search/browse experience even better : )

**Comment by NedHenry** [comment]
Indeed, the CSS change that Ryan implemented to make the thumbnails square also shrinks them. Good catch! It is possible to try to work around this in CSS, but my understanding is that solution is a little hack-y. 
We can generate actual square thumbs using our image server. I just need to make sure that won't be too slow; if our caching of derivative images on the image server is working correctly, this should be no problem.

**Comment by NedHenry** [comment]
It's actually a little complicated to figure out which view file to patch in order to update the html for these thumbnails. I think it's in Blacklight, but it might be in one of the other Samvera gems. Hopefully I'll sort it out soon.

**Comment by rschwab** [comment]
It's in Blacklight Gallery. I'm working on them now with the search results title ticket.

/app/views/catalog/_index_gallery.html.erb

**Comment by NedHenry** [comment]
Awesome, thanks! If it's easy for you to change the thumbnail URL at the same time, square thumbnails URLs can be generated in view scripts with the helper function: `square_thumbnail_url(document)` defined [here](https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/app/helpers/ucsc_thumbnail_helper.rb).

**Comment by rschwab** [comment]
@NedHenry I'm not sure how to pass it just the URL. This is the function its using, and it expects a document as the first parameter: https://www.rubydoc.info/github/projectblacklight/blacklight/Blacklight%2FCatalogHelperBehavior:render_thumbnail_tag

Here is the full partial:
`<div class="document col-xs-6 col-md-3">
  <div class="thumbnail">
    <%= render_thumbnail_tag(document, {'data-toggle' => 'tooltip', 'title' => document.title.first}, :counter => document_counter_with_offset(document_counter)) %>
    <div class="caption">
      <%= render_document_partials document, blacklight_config.view_config(:gallery).partials, :document_counter => document_counter %>
    </div>
  </div>
</div>`

**Comment by NedHenry** [comment]
Gotcha, yeah, I was noticing the same thing. It'll be easier to override that function and supply a custom URL. I'll write a helper to do that.

**Comment by NedHenry** [comment]
The new thumbnail code is in place. It successfully un-squishes the search result thumbnails. Please let me know if anyone notices any broken thumbnails or slow loading thumbnails anywhere on the site as a result of this change.

<img width="1407" alt="Screen Shot 2020-12-15 at 10 06 16 PM" src="https://user-images.githubusercontent.com/6326776/102311932-99667a00-3f22-11eb-9ff4-d198f18dfe27.png">
 
@rschwab Two things:
- The render_thumbnail_tag can be used as before, and that tag will now render all thumbnails using the helper method UcscThumbnailHelper.ucsc_thumbnail_tag. 
- The second argument to the render_thumbnail_tag function (a hash of image options) now accepts two more options "square: true" forces a square thumbnail, and "legacy: true" uses the old static thumbnail and ignores IIIF.

**Comment by chesleyperry** [comment]
@JessWaggs - I think this is completed but could you take a look and let me know if you agree?

**Comment by JessWaggs** [comment]
@chesleyperry Yep! This looks good!
