### ISSUE TITLE
(3) Apply new search results page: mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#225]
### Descriptive Summary

Style search results page to match mock-up on mobile:

<img width="350" alt="Screen Shot 2020-02-14 at 6 07 44 PM" src="https://user-images.githubusercontent.com/6412857/74580064-11f05900-4f55-11ea-816b-5a97ad84c2e8.png">

### Background 

Current search results page in mobile:

<img width="482" alt="Screen Shot 2020-02-14 at 6 09 41 PM" src="https://user-images.githubusercontent.com/6412857/74580095-524fd700-4f55-11ea-9711-eb8391f89c91.png">

### Acceptance Criteria

This is what done looks like

* [ ] Search results display in mobile matches mock-up
* [ ] Filters are collapsed at the top and when tapped, open to expand to show all available filters
* [ ] Matching collections box displays only linked titles (no thumbnails) in a vertical list
* [ ] Search term is displayed next to the number of results
* [ ] Sort by relevance dd menu displayed (# of items and display style menus are hidden)

### Related Work 

#223

**Comment by rschwab** [comment]
Pull request linked above. Note that the matching collections box is still under development at [#224](https://github.com/UCSCLibrary/dams_project_mgmt/issues/224).

Screenshots:
![Firefox_Screenshot_2020-11-17T23-55-46 391Z](https://user-images.githubusercontent.com/515412/99465094-6fec0b80-28ee-11eb-9b7b-f261a600b5be.png)
![Firefox_Screenshot_2020-11-17T23-55-39 436Z](https://user-images.githubusercontent.com/515412/99465100-724e6580-28ee-11eb-816a-502a6745d71c.png)

**Comment by chesleyperry** [comment]
This looks finished to me.  @JessWaggs - can you take a look and move it to done if you agree it's completed?

**Comment by JessWaggs** [comment]
@chesleyperry Yes - checked on my mobile device and this looks good!
