### ISSUE TITLE
Evaluate and find long term solution for YYYY-MM date

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#226]
### Descriptive Summary

Some of our legacy metadata contains YYYY-MM dates.  While this format is acceptable per metadata content standards, this format is not currently supported by the system.  Need to 

Consider using the User Story format:

As a user, I want the want to see an object even if the date included in the metadata is recorded in a non-standard format.
As a librarian, I want to distinguish between something that dates to December 2019 and something that dates to December 1, 2019.

### Background 

In legacy collections, dates were recorded YYYY-MM (not YYYY-MM_01) in order to differentiate them from objects that date specifically to YYYY-MM-01 not just to that month.  Need to determine how many of the YYYY-MM dates there are in our pre-ingest metadata and and for how many objects the specific YYYY-MM-01 date is actually important.  Will need to 

### Next Steps

* [ ] Survey pre-ingest metadata
* [ ] Consult with Special Collections
* [ ] Consult with developer
* [ ] Decide on and implement strategy

### Related Work 

This work is related to #217 Don't let malformed dates break site

**Comment by NedHenry** [comment]
I did a little research into exactly why the YYYY-MM format isn't supported by our system. It looks like that is something we will be able to change without too much trouble. Before doing a lot of work on changing this in all of the pre-ingest metadata, I think we should see if we can easily upgrade our system to handle a YYYY-MM date format and assume a monthly granularity. I believe I could accomplish this in a day or so of work, barring unforeseen complications.

**Comment by rmjaffe** [comment]
@NedHenry thanks for doing this research!  And apologies for the incompleteness of this ticket.  I was having some internet connection issues while creating it -- just now seeing that there are missing pieces.  I'll close this ticket and create a "upgrade our system to handle a YYYY-MM date format" ticket in its place.
