### ISSUE TITLE
(3) Create Collection Group (Collection of Collections) pages

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#231]
### Descriptive Summary

As an end user, I want groups of similar collections aggregated in one place so that I can search across the grouped collections and easily see which collections are within the group and access each one.

Group pages should match this mock up in desktop:

![Screen Shot 2020-02-26 at 9 00 21 AM](https://user-images.githubusercontent.com/6412857/75370628-3f54d500-587a-11ea-967b-24d6e0ad8afc.png)

In mobile:
![Screen Shot 2020-02-26 at 10 49 46 AM](https://user-images.githubusercontent.com/6412857/75376949-c22f5d00-5885-11ea-8be0-1cfd96b19649.png)

### Metadata Components for Page Content:

Group Components:
Group Page title (eg. UCSC Campus History Collections):
Group Representative Image:
Group description (under banner image):

Collection Components:
Collection title (eg. UCSC Photography Services Photographs):
Collection representative image:
Collection description (under Collection title):
View this collection URL:
Collection Guide URL:
 

### Background 

This page would display a "collection of collections" as specified in the ingest. 

### Acceptance Criteria

This is what done looks like

* [ ] The representative image designated for the collection group is displayed at the top, with the title inlayed in a white background
* [ ] All collections designated in the ingest are included in the group page
* [x] When a user enters a search query in the box on the page, this searches across all grouped collections
* [x] When a user clicks the "Browse all items in these collections" link, this leads them to a page showing all items across the grouped collections
* [ ] Each collection in the group displays its representative collection thumbnail image, title, description, a link to that collection's landing page, and a link to the collection's finding aid

### Related Work 

#153 
Work on #154 and #103 will need to be completed before this work can begin.

**Comment by JessWaggs** [comment]
@rmjaffe @NedHenry Would it be helpful to detail exactly which elements from the ingest generate which content on this page?

**Comment by rmjaffe** [comment]
@JessWaggs I think it would be helpful!  And I think this is something I could help with if not do.  My question is where or how would it be best to capture and communicate this information?

**Comment by JessWaggs** [comment]
@rmjaffe That sounds great! I think editing the ticket to put it in there would be a good place.

**Comment by rmjaffe** [comment]
@JessWaggs  I'll need some help in learning the appropriate terms for the different part of the webpages.  For example, I'm not sure what to call "UCSC Campus History Collections" piece.  Main title?  Page title?  I know that the value appearing here will be coming from the title property in the top-level collection metadata, but I'm not sure how to make the "this goes there" connection clear.

**Comment by JessWaggs** [comment]
@rmjaffe Good question! I'm not sure any have official names, I made an attempt at describing them adequately in the ticket in a new section titled "Metadata Components for Page Content" 

Feel free to re-label them as you see fit.

**Comment by chesleyperry** [comment]
Issue report:
In Combined Campus history collection drafts, the search box for the parent collection only searches the titles of the subcollections.  It doesn't seem to return results for the works in those subcollections.

**Comment by chesleyperry** [comment]
Functional issue:  
The collection facet box that shows on browse and search results screens displays the numeric collection names instead of the text names.  Example:
![Screen Shot 2020-11-12 at 1 23 31 PM](https://user-images.githubusercontent.com/18403313/98998124-7c392880-24ea-11eb-8f0d-808921f8b3bb.png)

**Comment by JessWaggs** [comment]
One small aesthetic issue:

Could we increase the spacing between the components of the collection blocks? (See red lines in screencap)
![Screen Shot 2020-11-13 at 4 16 37 PM](https://user-images.githubusercontent.com/6412857/99132753-4cfae800-25cc-11eb-8832-e68a04c814d3.png)

**Comment by JessWaggs** [comment]
And two questions:
1) Is it possible to show all 16 collections on this page so we don't require the pagination at the bottom?
2) Is it possible to truncate only at the end of a word? (In the screencap above, retirement is truncated at "retiremen")
