### ISSUE TITLE
(5) Update ingest spec (doc) for collection-level & collections-of-collections metadata

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#236]
### Descriptive Summary

Update [ingest spec](https://docs.google.com/document/d/1bExRPrnt-9mZvqqssadOxhj7pSnS-9aAUCXbXixipfY/edit#heading=h.xwxemhn3e720) for collection-level and collections-of-collections metadata.

As a metadata librarian, it is helpful to make reference to up-to-date documentation.

Rachel and Ned will work together on doing this.

### Acceptance Criteria

This is what done looks like

* [ ] Doc is updated

### Related Work 

#103

**Comment by rmjaffe** [comment]
Per our conversation on 7/31 ([notes](https://docs.google.com/document/d/1UazZOF8OQ3NMKsPWe55YJcjIyPiVIWW3I9iZyR0jXZQ/edit)), the scope of this ticket has been expanded to include updating for collections of collections as well as collection-level changes.

**Comment by JessWaggs** [comment]
I thought this looked great! It was very understandable, even though this was the first time I've read the ingest spec in quite a while.

I had one tiny clarifying question, but that was it. Left it as a comment in the doc.

**Comment by rmjaffe** [comment]
Link to Ned's draft: https://docs.google.com/document/d/1JglBugzxrbi4UtpOMVqq0gj13E5c6IFKB7x5EwfEZqY/edit?usp=sharing

**Comment by NedHenry** [comment]
The document linked above is now active and accurate to the best of our knowledge. We should continue to update, improve, and reference it. I am closing this issue unless anyone objects.
