### ISSUE TITLE
(5) Map out simplified request work flow

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#237]
# Acceptance Criteria 
- [x] Rachel to confirmation on holding off on needing Aeon and manual mediation
- [x] Jess interview SCA to map out new workflow 
- [x] Sue to create tickets 
- [x] Jess to potentially create mockups  
- [x] Kelly to review tickets for breakdown opportunities

**Comment by rmjaffe** [comment]
I just a had a very quick conversation with Teresa and I can confirm that any integration with Aeon will wait till a fuller, phase 2 implementation.  That said, SCA does want to include the creation of an Aeon account as a step in the simplified phase 1 workflow.  

As I understand it, members of the DAMS team don't fully understand why an Aeon account is necessary (ensure that users sign off on usage agreement, statistics gathering, etc.).  Conversely, folks in SCA don't fully understand why a DAMS account is necessary (being able to return to the DAMS and have access to the requested items without having to return to the emailed link, etc.).

It also seems unclear at this point which strategy we are pursuing for our phase 1 implementation:  1) restrict by campus IP only (does this mean that a person within the IP range wouldn't have to request access at this stage?; 2) the "temporary access token" idea; or 3) both of these?

Teresa has a clear vision of what the request & granting of access workflow would look like from SCA's perspective.  She and I agreed that it would be a good idea to have Jess (@JessWaggs if you have time) to interview her as a means of gathering that information for use in creating a workflow diagram and related tickets.

**Comment by rmjaffe** [comment]
@kellyChex @chesleyperry Just a gentle nudge on this:  Does it make sense as a next step to have Jess (if she has time) interview Teresa?

**Comment by JessWaggs** [comment]
Suggested workflows and user flows document: https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit?usp=sharing

**Comment by rmjaffe** [comment]
I updated the task list on the ticket to better match what is actually going on.
