### ISSUE TITLE
(1) Get full set of campus IP ranges

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#241]
### Descriptive Summary

Contact Daniel to get the full set of campus IP ranges.

### Background 

This is part of the first tier of our [VRR implementation plan](https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit).

### Acceptance Criteria

This is what done looks like:

* [ ] Daniel has been contacted
* [ ] We have heard back from Daniel

**Comment by rmjaffe** [comment]
@rschwab has this information; @chesleyperry has also requested it from Daniel.

**Comment by rschwab** [comment]
Here's what I have for IP ranges:

IPv4    128.114.000.000-128.114.255.255    
(this is the range of all physical addresses, plus the Campus VPN, and Off-campus Access Proxy)

IPv4    169.233.000.000-169.233.255.255 
(this is the range of all wireless addresses, including eduroam and Cruznet)

The above addresses include off-site locations like University Extension, the Scotts Valley site, and Long Marine Lab.
