### ISSUE TITLE
(1) Finalize language in request box

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#243]
### Descriptive Summary

Need to finalize the language that will appear in the yellow request box that appears in Jess' mockup [https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit](url).

### Acceptance Criteria

This is what done looks like:

* [x] Language has been finalized in consultation with SCA
* [x] New mock up depicts finalized language

### Related Work 
#237

**Comment by rmjaffe** [comment]
@JessWaggs Can you help flesh out this ticket.  I'm not clear on what related or supporting UX/UI work has been done or needs to be done around this.

**Comment by JessWaggs** [comment]
Kate and Teresa signed off on the language currently present in the tier 1 (IP restriction) and tier 2 (request access) mock ups.
