### ISSUE TITLE
(3) Create "learn more" LibGuide

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#244]
### Descriptive Summary

Create "learn more" LibGuide for non-affiliates and other users outside of the campus IP range.  When clicking on the "request" button, these users will be directed to this LibGuide.  This LibGuide will describe mode of access to the collection.

### Background 

Part of VRR tier one roll out (https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit).

### Acceptance Criteria

This is what done looks like

* [ ] SCA has created LibGuide
* [ ] Request button in DAMS links to LibGuide

**Comment by JessWaggs** [comment]
Created draft guide and sent to Teresa and Kate for feedback: https://guides.library.ucsc.edu/cabrillo-music-festival
