### ISSUE TITLE
(3) Mock up for A-Z / All Collections page

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#247]
### Descriptive Summary

Create mock ups for desktop and mobile versions of a page displaying all DAMS collections. This page will be linked to from the "VIEW ALL COLLECTIONS" button on the homepage.

### Acceptance Criteria

This is what done looks like

* [x] Desktop mock up
* [x] Mobile mock up

**Comment by JessWaggs** [comment]
Desktop mock up:

![AtoZ_desktop](https://user-images.githubusercontent.com/6412857/79625078-49a58980-80db-11ea-9012-37b5c580bc10.png)

Questions/Considerations:
Do we want to include a "Collection Guide" link after each description on this page? 
If so, two problems: 1) the link text pointing to same URL issue and 2) would want to make sure users aren't clicking Collection Guide anticipating access to digital collection - could test this pretty easily using first click tests

**Comment by JessWaggs** [comment]
Mobile mock up:

![AtoZ_Mobile](https://user-images.githubusercontent.com/6412857/79625105-87a2ad80-80db-11ea-8b1d-185650c92403.png)

**Comment by rmjaffe** [comment]
@JessWaggs These are great!  As far as your question: Do we want to include a "Collection Guide" link after each description on this page?  Assuming the collection guide is the OAC finding aid, I'd be disinclined to include links that direct users away from the DAMS on the A-Z.  If I saw a link featured here (and for some reason it seems more clickable than the linked collection titles), I'd assume I'd be delivered somewhere else in the DAMS, likely the collection landing page or to some portion of the collection landing page.  Arriving in OAC would be unexpected.

I think it make sense for the Collection Guide links to appear on the individual collection landing pages but not as part of their "directory listings" here.

**Comment by JessWaggs** [comment]
@rmjaffe Yes, the "Collection Guide" is the OAC finding aid. I agree - if it's not really needed, then we don't have to worry about the same destination or confusing the user issues. Plus, the link is at the top of the Collection Landing page, so it will readily accessible once the user clicks into the collection.

So let's not include the "Collection Guide" links on this A-Z page or on the Collection Group pages (same issue). I'll update those mock ups.

**Comment by JessWaggs** [comment]
Updated mock up (excluding Collection Guide links):
![AtoZ_Page_Page_1](https://user-images.githubusercontent.com/6412857/81118781-5f3df000-8ede-11ea-8d9d-758e7ae5539d.png)
 
[Link to file in Google Drive](https://drive.google.com/open?id=1LZCYHTut1TaeU-eGGNOHDNyGxo_BgMtm)

**Comment by JessWaggs** [comment]
Subsequent tickets: UCSCLibrary/dams_project_mgmt#277 and UCSCLibrary/ucsc-library-digital-collections#375
