### ISSUE TITLE
(2) Implement display for users NOT on Campus IP

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#248]
# User Story: 
As a User not on Campus IP addresses (determined in https://github.com/UCSCLibrary/dams_project_mgmt/issues/241) I see a message notifying me of the access restrictions 

# Acceptance Criteria:
**Steps:**
* [ ] User navigates to CMF record
* [ ] User sees message notifying them of access restrictions - Language determined in https://github.com/UCSCLibrary/dams_project_mgmt/issues/243 
* [ ] User can click “LEARN MORE” button to navigate to a LibGuides CMF page explaining access options (ie. visit the UCSC campus, use VPN, contact Spec Coll?) 
* [ ] LibGuide Page can be done in - https://github.com/UCSCLibrary/dams_project_mgmt/issues/244 @JessWaggs to provide the URL

# Mock Up: 
![Screen Shot 2020-03-11 at 11 51 50 AM](https://user-images.githubusercontent.com/9621070/76453331-e9ab1d00-638f-11ea-9fc9-dd52c4f70d4f.png)

# Other: 
**Planning Doc:** https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit

**Comment by JessWaggs** [comment]
SCA signed off on language used in this mockup 4/13/20.
LibGuide: https://guides.library.ucsc.edu/cabrillo-music-festival
