### ISSUE TITLE
(1) Style Titles for Search Results (new UI)

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#249]
### Descriptive Summary

As a user, I want to see the full title of a search result when I hover over it so I can make an informed decision before clicking on it.

Limit the length of titles that appear below thumbnail images in search results to 2 lines. Truncate after whole word using ellipses. On hover, display full title in a reduced size (12px?) using black font (see red box in mock-up).

Styles:
Right aligned
Titles below images styled/behave as links
Titles show on hover displayed in gray box (#F7F7F7) and black text in reduced font size

### Background 

Mock-up showing titles before and on hover:

![Screen Shot 2020-03-12 at 2 47 24 PM](https://user-images.githubusercontent.com/6412857/76569584-b2606d00-6470-11ea-96af-5c755c1633da.png)

### Acceptance Criteria

This is what done looks like

* [x] Titles below thumbnails span no more than 2 lines
* [x] When a user hovers over a truncated title, the entire title displays in a pop over

### Related Work 

Styling for other aspects of search results page: #200, #223, #224

**Comment by JessWaggs** [comment]
See [Calisphere](https://calisphere.org/search/?q=earthquake) for an example

**Comment by rschwab** [comment]
Pull request linked in mention above.

Screenshot:
![249-titles](https://user-images.githubusercontent.com/515412/101848489-772bc100-3b0a-11eb-9e01-c2e956a316f9.png)

**Comment by chesleyperry** [comment]
Looks like this is finished.  See https://digitalcollections.library.ucsc.edu/collections/6108vf26h?locale=en&page=19 as an example.

**Comment by rschwab** [comment]
I checked about a dozen titles that had bled over to three lines. Reducing the character limit from 40 to 35 ensures two lines on all of them. I'll check with @NedHenry about whether this should be a pull request or just a quick fix on his part.

**Comment by JessWaggs** [comment]
Looks good to me! Title pop-overs worked as expected and I didn't see any titles beyond two lines on the results pages.
