### ISSUE TITLE
(5) Create user experience requirements for the media player

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#25]
### Descriptive Summary

Create user experience requirements for the media player.

Note from Ned:   What remains is front-end work. I have not been trying to meet any specific requirements in terms of user experience or aesthetics, but have been using my own judgement and sticking close to the easiest possible solutions pending more input. 

### Background

Note from Ned:  I know we will want some look-and-feel changes needed for the player, which will likely require some styling and scripting work on the front end. I think we need to set out clear goals for this before I can dig into it. We're using MediaElement.js, which has been the leading open source A/V player online for many years. Probably customizing this software will be the focus of near term future A/V work.

### Acceptance Criteria

This is what done looks like

- [x] Determine what look-and-feel changes are needed for our audio player in different contexts
- [x] Create list of UI/UX changes and additions
- [ ] Tickets created for next steps (either mockups or implementation)

### Related Work 

#32 Find existing plugins for MediaElement.js (TBD)

### Notes 

- The playlist in the Hitchcock collection for instance could use further thought it how it displays
- Links in the child work seem redundant. Maybe just play the audio? Need to determine how it should work.  
- Consider displaying transcripts. See Sue's note in #32 
- User stories already exist for displaying transcripts.

**Comment by JessWaggs** [comment]
In retrospect, there was pre-work, including group discussions, that need doing before the tasks outlined in the acceptance criteria in this ticket.
I've created a document with our basic user requirements, but there are some core decisions to make before we can do specific UI recommendations. 
[User Requirements doc](https://docs.google.com/document/d/1u7xIgZHLepEAJ5eVpG9Xu99iuoSKwzvJ1nTmXszs8N0/edit?usp=sharing)

**Comment by JessWaggs** [comment]
[A/V Object Wireframes](https://drive.google.com/drive/folders/1Ypcd3SdjRgZlzsiRzmwn3Kzc1kSxhK5O) (web and mobile)
[Search Results Wireframes](https://drive.google.com/drive/folders/1FYckWC-4nYeIQ976ZcYDAm6HRvOZtiRa)

**Comment by chesleyperry** [comment]
I think these look great!
2 comments: 
1. The "download" link should only show up when we have the rights to allow downloads.  We'll need to come up with criteria for when downloads are allowed, and how to signify that in the record(s).
2.  For the AV object and image set pages, we haven't spelled out what the page looks like if the user clicks on "more information".  I think the left column should expand vertically to show the other fields.

**Comment by kellyChex** [comment]
I have a couple of questions: 
1. Do search facets still need to be determined? 
2. Should a similar style be applied to non video and audio collections? If so, I’m wondering if it makes sense to do further styling work like that structural metadata ticket, https://github.com/UCSCLibrary/dams_project_mgmt/issues/106 if we’re just going to change all that soon.

**Comment by JessWaggs** [comment]
1) Yes - we haven't done any work around facet needs/requirements yet
2) I have a [wireframe for an Image Set page in web](https://drive.google.com/open?id=1pdlhtGHikVMwI19uW-PpzVOciS6Qbee-) (but not mobile)

**Comment by JessWaggs** [comment]
I think #106 still makes sense to do now/soon. The "collection" element (as described in the data dictionary) is supposed to appear alongside the other descriptive metadata.

**Comment by kellyChex** [comment]
Okay, https://github.com/UCSCLibrary/dams_project_mgmt/issues/123 so we can remember to determine the search facet requirements.
