### ISSUE TITLE
UA 50: Change relatedResource to staffNote

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#255]
### Descriptive Summary

The relatedResource metadata property in the UA 50 collection contains citation information.  It was observed that some of these citations contain broken link and links to objects in CONTENTdm.  As an interim solution, we would like to restrict the visibility of data in the relatedResource property to admin view only and relabel it "staff note."

Consider using the User Story format:

As an enduser, I don't want to click on links in the metadata that are broken or dead.
As a staff user, when I see that this citation data is in a field labeled "staff note," I feel confident that it is not visible to endusers.

### Background 

Eventually, we would want consider a review and clean-up of these links, but not now.

### Acceptance Criteria

This is what done looks like:

* [x] Data in the relatedResource property visible only to admin users
* [x] Data in relatedResource is relabled "staff note"

**Comment by rmjaffe** [comment]
@chesleyperry Just wanted to let you know that I've talked to Teresa and Ned about this and this is what we've come with as an interim solution.  Thanks again for surfacing the links!

**Comment by NedHenry** [comment]
In all works in UA50, I moved all metadata from the relatedResource field into the staffNote field, which is only visible to administrators. I still have to look through some of the records to make sure I didn't miss anything somehow.

**Comment by rmjaffe** [comment]
Thanks Ned, I'm going to look at a couple of these too.
