### ISSUE TITLE
(1) Enable flash messages on front-end pages

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#258]
As a user, I want to be able to see messages/alerts sent from the system. The flash message system enables this.

- [x] When a flash message is sent, it appears on screen to the end-user.

**Comment by rschwab** [comment]
This is a pre-requisite for [Share modal for Works](https://github.com/UCSCLibrary/dams_project_mgmt/issues/128)

**Comment by rschwab** [comment]
Pull request linked above.

Screenshots:
![Firefox_Screenshot_2020-05-01T19-11-59 754Z](https://user-images.githubusercontent.com/515412/80834588-da816800-8ba5-11ea-9321-53b3d4c4f77e.png)
![Firefox_Screenshot_2020-05-01T19-10-18 836Z](https://user-images.githubusercontent.com/515412/80834601-dfdeb280-8ba5-11ea-90a1-0707ad87273c.png)

@JessWaggs I think you'll agree the UX isn't great on this. Is it worth making a new ticket to refactor the email validation into javascript so that it happens before the user is able to click send?

**Comment by rschwab** [comment]
Ugh, I also only _just now_ realized the success message is a leftover from the contact form. Taking suggestions on better language for that, too. :)

**Comment by JessWaggs** [comment]
Yeah, checking for a valid email and giving an error before they hit submit is ideal : )

I picked up on that message too - makes it sound like the user sent us a message, so might confuse them. Maybe "Your email has been sent" ?

**Comment by rschwab** [comment]
Thanks Jess. I've updated this pull request with that improved message, and I'll open a new ticket for the validation next.
