### ISSUE TITLE
(2) DAMS Field Select Box Needs Description

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#261]
Description of this issue:
Drop down menus (select boxes or role="listbox") should always have a description that is explicitly associated with the field to make sure that users of assistive technologies will also know what the field is for.
How to fix it:

If the drop down menu (select box or role="listbox") has a visible description indicating the purpose of the menu, this description should be explicitly associated to the input drop down menu either as a HTML label or using the WAI-ARIA attribute 'aria-labelledby'.

If it is not possible to add a visible description, create an invisible label using the WAI-ARIA attribute 'aria-label'.

<img width="985" alt="Screen Shot 2020-04-14 at 9 56 30 AM" src="https://user-images.githubusercontent.com/6412857/79252415-6b321700-7e36-11ea-911a-c79b9a8be8f2.png">

**Comment by rschwab** [comment]
For the aria-label, as a first pass I'm going with "Select the field to search", but I can edit that if anyone wants to suggest something else.

**Comment by rschwab** [comment]
Pull request linked above as "Aria label added to search form field. #121".

No relevant screenshots, this is for screen readers.

**Comment by chesleyperry** [comment]
I'm not seeing this specific issue in the SiteImprove report for this page, so I think it's fixed. I think this can be pushed into production.

There are several other WAI-ARIA label errors but I'll submit separate tickets for those.
