### ISSUE TITLE
(5) Develop project documentation strategy

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#262]
### Descriptive Summary

Develop a plan or recommendations for managing our project documents:  getting a grip on existing documents, identifying gaps in documentation, and assembling them in some way that makes them easily accessible.

Consider using the User Story format:

- As a team member, I would like to be able to quickly link to key documents.
- As a team member, I would like to be able to easily refer to key decisions.
- As a team member, I would like to be certain that the document I am referencing is the most current and definitive version of a document.
- As a random person in Hyrax community, I would like to understand your structural metadata model.  Is there a document that explains this?

### Background 

In discussing possible improvements to our current project workflow, we identified a need for a documentation strategy that addresses the following:

- What categories of documentation to we need?
- Where do those documents go?
- How are they maintained?
- How can we make them (or those most heavily used) easily accessible?

### Acceptance Criteria

This is what done looks like:

* [ ] Determine where documentation is currently kept
* [ ] Determine what kinds of documents do we currently have
* [ ] Determine what kinds or categories of documents it would be helpful to have
* [ ] Determine what documents are missing and would be helpful
* [ ] Determine what the best strategy would be for making these documents accessible (e.g. TOC with links on a wiki page, etc.)
* [ ] Determine next steps and what additional tickets will need to be created (e.g. deprecating older documents, how are we going to maintain documents, creating a wiki page, etc.)

### Related Work 

This ticket stems from our Review/Retro meeting on April 21, 2020.

**Comment by JessWaggs** [comment]
I've added a folder for Mock Ups and another for Personas & Journey Maps. 
I think I'm done : )
