### ISSUE TITLE
(5) Detail User Needs for Child Works

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#263]
### Descriptive Summary

Describe user needs around parent and child items.

### Background 

To inform interaction design and navigation between parent and child

### Acceptance Criteria

This is what done looks like

* [x] User needs documented
* [x] Mock Ups for Item set page updated/modified (if/as needed)

### Related Work 

#94

**Comment by JessWaggs** [comment]
**User Needs:**

- As a user, I can view a set of related images
- As a user, I can understand that this is a set of individual images
- As a user, I can understand why these images are grouped together
- As a user, I can easily browse through the set of images
- As a user, I can select an item from the set to view its metadata
- As a user, I can select an item from the set to view a larger version of it
- As a user, I can copy the URL in the browser bar to easily navigate back to a specific image from a group
- As a user, I can easily access citation, download, and share options for a specific image within a set


**Changes in this Mock Up:**

- Transparency of language (adding “Image Set” as a prefix to the set’s title)
- Showing item titles on hover (analogous to search results behavior)
- Larger thumbnails (single row)

**Comment by JessWaggs** [comment]
<img width="984" alt="Screen Shot 2020-05-14 at 3 36 00 PM" src="https://user-images.githubusercontent.com/6412857/81992636-c9e6de00-95f8-11ea-90b1-37e8b85dac05.png">

See [video demonstrating interactions](https://drive.google.com/file/d/1UUq50a54KVYK3NfpXdHlguVM26a5O3dX/view?usp=sharing)

**Comment by chesleyperry** [comment]
I think this looks good - I don't have any suggestions for the changes to the mockup or the user needs.  I especially like the bigger thumbnails.
We should note this is just for image grouping in the UV, and not all works with child works.

**Comment by NedHenry** [comment]
During retrospective, we decided that the easiest way to implement this is not to load the Universal Viewer by default. We will implement the interface above outside UV, with the child thumbnails as links. When a user clicks on the primary image or on the zoom icon, the page reloads with an embedded universal viewer which displays only the current image. The thumbnail functionality and asynchronous image loading within Universal Viewer is not used here.
