### ISSUE TITLE
(5) First Round QA of CMF recordings

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#266]
### Descriptive Summary

DAMS team members do an initial check of the ingest of Cabrillo Music Festival Recordings to make sure the files and metadata elements were ingested.  After this initial check, the collection can be published to the UCSC IP range and a more thorough QA check of each record will be checked by Spec Coll and DI staff and students (issue #267 ).  In this round of QA, team members will also compile examples of issues to report for the second round.

Team members will use a spreadsheet (https://docs.google.com/spreadsheets/d/1qa-z830T7qBpOUg2A0aCrXBc47fx-toGQA8zEaRraLo/edit#gid=282589566) to track progress and record notes.  Issues and bugs will be added to github.

Notes on the spreadsheet:  
20 tracks to be checked.  Chosen randomly with a number generator.
Titles were copied from Rachel's spreadsheet so they should have correct spelling and special characters.  Testers should check to make sure accents and umlauts are displaying .
Testers should try a couple of different browsers and record issues in the listed columns.

### Acceptance Criteria

* [x] Metadata elements for parent works (concerts) and children (tracks) are fully ingested into the correct elements in the DAMS records
* [x] Metadata displays correctly for both concerts and tracks (i.e. metadata is showing up and labeled correctly, metadata inheritance is as expected)
* [x] Tracks display correctly and in the right order.
* [x] Tracks are playable using the embedded audio player
* [x] QA tasks for the second round with examples are fleshed out in ticket #267 

### Related Work 

Second phase of the published works will be tracked in a separate issue (#267 ).

**Comment by rmjaffe** [comment]
@chesleyperry @afrebert I'm not sure where to report this, but wanted to alert you both in case it's an issue that's observed among the 20 items on the round #1 spreadsheet.  The tracks on this [item](http://digitalcollections.library.ucsc.edu/records/s7526f84t) display out of order (Track 2, Track 3, Track 1).

**Comment by chesleyperry** [comment]
The item @rmjaffe is for the first round of CMF ingested items.  I've made a ticket (#274) to determine next steps for merging the two collections.  This should be resolved as part of the work on that ticket.

**Comment by rmjaffe** [comment]
Thanks, Sue!
