### ISSUE TITLE
(8) Second round of QA for published CMF records

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#267]
### Descriptive Summary
Spec Coll and DI staff and students will check the Cabrillo Music Festival recordings to assess whether recordings are playable, if metadata is consistent with announcements on recordings, and note issues with different web browsers.  Track QA tasks in spreadsheet: https://docs.google.com/spreadsheets/d/1P2e7-IVcseyduU7wGaEUgMEmbUED7M12AeKsQWFTfO8/edit#gid=282589566&fvid=518025687
URLS for concerts will be added after collection is published

Team members will use a spreadsheet (to be linked) to track progress and record notes. Issues and bugs will be added to github.

### Acceptance Criteria
* [ ]  Tracks are playable using the embedded audio player in the most-used web browser/OS combinations
* [ ]  Metadata displays correctly for both concerts and tracks
* [ ]  Tracks display correctly in the most-used web browser/OS combinations and in the right order.

### Related Work
This is the second phase of QA.  The first initial phase of the unpublished works is tracked in issue #266

**Comment by rmjaffe** [comment]
@chesleyperry Re: the acceptance criterion "Metadata displays correctly for both concerts and tracks."  Would it make sense to add some examples:  no obvious mislabeling, inaccuracies, typos, etc.?
