### ISSUE TITLE
(2) Team Drive Clean Up

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/dams_project_mgmt#269]
* [x] Create folder "Current Documents for Github Wiki" on Google Drive.
* [x]  Team members review their individual documents on Google Drive and determine which ones are currently relevant, i.e. which documents would we want to link to from the Github Wiki for direct access.
* [x]  Team members create individual folders within "Current Documents for Github Wiki" and move the selected documents into the individual folder.

**Comment by rmjaffe** [comment]
@afrebert I pretty aggressively weeded and reorganized the "legacy" contents of the Team Drive. There are two documents that remain floating out there.  I wasn't sure what to do with them.

- [Hycruz Permissions Table](https://docs.google.com/spreadsheets/d/1G5j2hNLassBmBO9tm4XEyL23GUgcR6yUqYR5_ZRq1Ec/edit?usp=drive_web&ouid=114117346070027385497). @NedHenry Is this current, should it be tagged as obsolete, or should it be removed?

- [Screenshot of Calisphere citation modal](https://docs.google.com/spreadsheets/d/1G5j2hNLassBmBO9tm4XEyL23GUgcR6yUqYR5_ZRq1Ec/edit?usp=drive_web&ouid=114117346070027385497) @chesleyperry Should we hang on to this or can it be removed?

**Comment by chesleyperry** [comment]
I think we can get rid of the Calisphere citation modal screenshot.

**Comment by rmjaffe** [comment]
@afrebert I think we're done with this one.
