### ISSUE TITLE
Investigate dateCreated issue with Hitchcock/Holmes

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#27]
### Descriptive Summary

dateCreated is not displaying correctly in the Hitchcock & Holmes collection metadata. Ned made the appropriate fixes. The Hitchcock & Holmes collection still needs to be re ingested so that we can confirm this is no longer an issue. Once re ingested, confirm whether or not this is still a bug.

### Expected behavior

For instance in this work, http://digitalcollections.library.ucsc.edu/records/5138jd86g:
dateCreated should match the value recorded on the ingest spreadsheet: 1978
dateDigitized should match the value recorded on the ingest spreadsheet: 2015

### Actual behavior

dateCreated shows 01/01/2015, not the value given on the ingest spreadsheet (1978)
dateDigitized shows date ingested? 07/31/2019 not the date given on the ingest spreadsheet (2015)

**Comment by rmjaffe** [comment]
I believe the issue with dateCreated has been resolved in the time since the Hitchcock & Holmes lectures were ingested.  I expect that when we replace and republish the metadata and files, both the dateCreated and dateDigitized values will ingest and display correctly.  Is this correct @NedHenry?

**Comment by kellyChex** [comment]
Metadata got overridden but future new ingests so shouldn’t be an issue. Not something the public can see so it's not seen as an issue that needs to be corrected.

**Comment by kellyChex** [comment]
Note: links are broken bc it's an old and does not exist anymore.
