### ISSUE TITLE
MS 20: Different Image in Viewer from Search Results

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#273]
### Expected Behavior 

Image in the search result thumbnail will match the image in the viewer on the item page.

### Actual Behavior

For the [Norman Steiner sub-series](http://digitalcollections.library.ucsc.edu/catalog?locale=en&q=Dr.+%26amp%3B+Mrs.+Norman+Steiner%26%2339%3Bs+children%2C+referral+by+Alice+Boyd+Adam&search_field=subseries), several (at least 4 I've tried) of the search results display a different image on the item page.

<img width="848" alt="SearchResults" src="https://user-images.githubusercontent.com/6412857/81986526-cf3e2b80-95ec-11ea-9f5d-b1413cc8f281.png">
<img width="1117" alt="ItemPage" src="https://user-images.githubusercontent.com/6412857/81986536-d402df80-95ec-11ea-8f75-5d539928e2b3.png">

### Steps to reproduce 

Click on the second result in the Norman Steiner sub-series search results page.

**Comment by rmjaffe** [comment]
If it's determined that this is more than a small fix, ticket can be relocated to the Planning queue.

**Comment by rmjaffe** [comment]
@chesleyperry @JessWaggs Is this related to or the same as #216 Fix image file and thumbnail mismatch?

**Comment by JessWaggs** [comment]
@rmjaffe @chesleyperry It does sound like the same problem as #216

**Comment by rmjaffe** [comment]
Thanks, @JessWaggs.  @chesleyperry If you can confirm this, let's close out this ticket with the note that it's duplicative of the other card.

**Comment by rmjaffe** [comment]
@NedHenry Can you confirm that this is the same issue/work as #216? If so, I'll close this ticket.
