### ISSUE TITLE
(5) Create Collection landing page for Cabrillo Music Festival - Deadline 10/15/20

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#275]
### Descriptive Summary

Using Jess's mockups (to be linked) as a guide, create a landing page for the Cabrillo Music Festival Collection

User Story:

As a researcher, I want to see a landing page that gives me context for the collection and easily allows me to navigate from the collections to the concert series, to the performances.  The concerts should be sorted by default in an easily understandable order, such as by date.  I should be able to understand the format of the works in the collection (audio recordings) by looking at the collection page.

### Acceptance Criteria

This is what done looks like

* [x] The CMF collection page matches the mockups in ticket #176 
* [x] The 3-D cube thumbnail is replaced with a more meaningful thumbnail that signfies audio recordings
* [ ] The default sort for the collection alphabetical or date

**Comment by rmjaffe** [comment]
We've decided to leave off the sorting as an acceptance criterion for this ticket.  This work will be done as part of or after #366 has been completed.
