### ISSUE TITLE
(5) Apply new Collection Landing page design: Mobile - Deadline 10/15/20

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#276]
### Descriptive Summary

As an end user, I want to view all items within a collection so that I can browse and search for items within that single collection on my mobile device.

Redesign collection pages on mobile to match:

<img width="332" alt="Screen Shot 2020-05-18 at 3 30 34 PM" src="https://user-images.githubusercontent.com/6412857/82265764-a5527500-991c-11ea-86b9-74a6b825db4a.png">
 
### Background 

Current Collection page on mobile:
<img width="423" alt="Screen Shot 2020-05-18 at 3 22 13 PM" src="https://user-images.githubusercontent.com/6412857/82265811-c2874380-991c-11ea-923e-0152596bb1e0.png">

### Acceptance Criteria

This is what done looks like

* [x] Include facets for collection level pages, but collapsed under "Show Filters" on mobile
* [x] Move collection search box to be collapsed with facets in "Show Filters"
* [x] Remove breadcrumbs, "Collection details" box, item count and update date below title
* [x]  Hide results and display option buttons
* [x] Restyle relevance button
* [x] Re-style pagination to match desktop mock up (img below)

Pagination style:
<img width="143" alt="Screen Shot 2020-05-18 at 3 36 46 PM" src="https://user-images.githubusercontent.com/6412857/82266034-6a047600-991d-11ea-94f2-0796d96021cf.png">

### Related Work 

Collection description box: #222 
Collection landing for desktop: #176 
[Mock up in Google Drive](https://drive.google.com/open?id=1G0pN__RJ4f6OPUYDLuqh2zlHhqplPtPU)

**Comment by rschwab** [comment]
Pull Request linked above. One change from the mockup is the filters toggle button has yet to be moved above the collection description. That can be done when the collection description box is added.
