### ISSUE TITLE
(5) QA on Cabrillo Music Festival Pilot 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#28]
### Descriptive Summary

Once Ned ingests the CMF Pilot, perform Quality Assurance testing to ensure the files match the correct metadata and that the audio files are playable. 

### Acceptance Criteria

This is what done looks like

* [x] Create or adapt a QA excel spreadsheet to confirm testing of each file in the different browsers. For an example, see Hyrax 3.0 QA sheet (attached)
[Hyrax 3.0 QA Testing.xlsx](https://github.com/UCSCLibrary/dams_project_mgmt/files/3704674/Hyrax.3.0.QA.Testing.xlsx)
Google Sheet: https://drive.google.com/a/ucsc.edu/file/d/1sMOmDk-lMkZGC6ZR7MPsDM3DXRPxSAd2/view?usp=sharing

* [ ] Include placeholder for metadata check in QA excel spreadsheet   
*  [x] Look into Browserstack or a similar tool where one can test across diff browsers and devices 
* [ ] The entire CMF Pilot collection has been checked 
* [ ] The the files needs to match the correct metadata records and the audio files need to be playable else issue tickets need to be created. 

- [ ] Files need to be playable in single work player view
- [ ] Files need to be playable in playlist player view

Browser/OS combinations to check:
- [ ] Chrome Windows
- [ ] Safari iOS
- [ ] Chrome Mac
- [ ] Safari Mac
- [ ] Firefox Windows
- [ ] Chrome Android
- [ ] Edge Windows
- [ ] IE Windows
- [ ] Chrome Chrome OS

### Related Work 

#7 Ingest Cabrillo Music Festival Pilot needs to be performed first

**Comment by kellyChex** [comment]
@rmjaffe To look over https://drive.google.com/a/ucsc.edu/file/d/1sMOmDk-lMkZGC6ZR7MPsDM3DXRPxSAd2/view?usp=sharing and let us know if have time to do QA

**Comment by rmjaffe** [comment]
Just looked over Sue's template -- it looks great!

@chesleyperry My only question is whether it would be good to broaden the last criterion, Metadata Match, from "Any announcements or verbal introduction matches the metadata title" to "Any announcements or verbal introduction matches the metadata," which could include title, dateCreated, the performers and others represented in contributor and the description.  I would want any to pay undue attention to the metadata, but if there are an egregious inaccuracies, it would be good to know!

@kellyChex I don't think I'll have time to be engaged in the QA work beyond a basic review of the metadata records (did things map correctly, everything there, everything labeled correctly, etc.).

**Comment by chesleyperry** [comment]
Spreadsheet updated to remove "title" from the metadata matching cells.  I also made it into a Google Sheet so it's easier to edit collaboratively:  https://docs.google.com/spreadsheets/d/1ngX1cMb7czuYY4c2XZ-5pNEdyGtu5B35XO0dSmG5ElY/edit#gid=282589566

**Comment by chesleyperry** [comment]
Browser specific issues are described in a [Google Doc:](https://docs.google.com/document/d/1ErhkbQiQcTrxujh988LC3POMCSQopS4XekjGZ2GJsvQ/edit#)

One bug reported #91 
Other failures are mostly issues with the display and style.  If we move forward with the 'playlist as paradigm' (in the [media player user requirements](https://docs.google.com/document/d/1u7xIgZHLepEAJ5eVpG9Xu99iuoSKwzvJ1nTmXszs8N0/edit).  Most of the issues can be resolved.
