### ISSUE TITLE
(4) Apply new homepage design: Mobile - Deadline 11/10

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#280]
### Descriptive Summary

As an end user, I want to know what I might find in a "Digital Collections," have a readily apparent way to search for items, and have the ability to browse collections on my mobile device.

Mobile homepage mock up: 
![Screen Shot 2020-03-06 at 2 44 59 PM](https://user-images.githubusercontent.com/6412857/76128446-35894b00-5fb9-11ea-8107-e0a17a32c0fa.png)

Colors used:
Med. Blue background: #02779E at 75% opacity
Dark gray background: #575757 at  75% opacity
Text over both: #FFFFFF

### Background

Current homepage on mobile:
<img width="436" alt="Screen Shot 2020-05-19 at 11 44 08 AM" src="https://user-images.githubusercontent.com/6412857/82365827-1863f600-99c6-11ea-93b6-18a4a7d43d1c.png">

### Acceptance Criteria

This is what done looks like

* [ ] Change header on homepage to only include top dark blue bar
* [ ] Display thumbnail image for 4 "featured" collections (top row on desktop version) that link out to the collection's landing page 
* [ ] "VIEW ALL COLLECTIONS" button links out to A-Z page of all collections

### Related Work 
Mock up ticket: #146 
Desktop ticket: #279 
[Mock up in Google Drive](https://drive.google.com/open?id=1jMHh-PiC9th5O2WSYMpUUb1cWWP5HYtE)

**Comment by rmjaffe** [comment]
During the current sprint, work on this ticket will focus on getting a better sense of contingencies as well as the actual scope of the work and time involved.  We may want to consider assigning a deadline for the remainder of the work once the investigation stage is complete.

**Comment by rschwab** [comment]
Contingencies/Dependencies:
1. Featured collections.
- This functionality does not yet exist. Use static content for now?
- Need to identify which collections we will start with.

2. View All Collections button.
- An A-Z collections page does not yet exist.
- Currently the homepage displays all public collections.
- This button could be a hide/show toggle to display the remaining collections while the A-Z page is being designed and built?

3. Mobile menu.
- Any links here besides "Browse collections" and "Contact us"?
- And presumably the "Browse collections" link should eventually go to the A-Z collections page?

**Comment by JessWaggs** [comment]
Decision: Create homepage using static elements

1) JW will create a Featured Collections ticket for a future sprint (will not be a dependency for this ticket)
SP will ask SCA to designate 4 collections for static homepage

2) Yes, use toggle to display to show all collections beyond the 4 featured

3) Maybe just "Contact Us" until we create the A-Z page makes sense

**Comment by rschwab** [comment]
Pull request linked above. Screenshots:
![Firefox_Screenshot_2020-10-29T17-25-13 364Z](https://user-images.githubusercontent.com/515412/97611446-706e4200-19d3-11eb-9b7c-4840120dac32.png)
![Firefox_Screenshot_2020-10-29T17-25-03 566Z](https://user-images.githubusercontent.com/515412/97611471-76642300-19d3-11eb-9237-07a6bbaf6eb5.png)

**Comment by rschwab** [comment]
New screenshot:
![Firefox_Screenshot_2020-10-30T20-53-41 258Z](https://user-images.githubusercontent.com/515412/97756561-50647e80-1ab8-11eb-852e-458cd8c813ae.png)
