### ISSUE TITLE
(1) Publish MS 427 Santa Cruz County History Photos

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#287]
### Descriptive Summary

This collection was ingested, but has not yet been published.

### Background 

We are working out a soft launch publication timeline with SC&A.

### Acceptance Criteria

This is what done looks like:

* [ ] Collection is published and visible to the public.

### Related Work 

#206 SC County Historic Photos Collection

**Comment by NedHenry** [comment]
This collection has been published and linked on the homepage.
