### ISSUE TITLE
(3) Post-Ingest Ansel Adams (MS 2)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#289]
### Communication

* [x] Spec Coll notified

### CONTENTdm collection removal 

* [x] Items deleted from CONTENTdm
* [x] "About the collections" description on CONTENTdm homepage updated with link to DAMS
* [x] Remove links from Library resources (catalog, finding aid, library website)
* [ ] Google search console report for links to CONTENTdm
* [x] Google Analytics search for most popular links
* [x] ARKS’s updated (if necessary)

### Related Work
#48 Pre-Ingest Adams
#284 Ingest of Adams
#120 Post-Ingest of Combined Campus History collections, UA 50 & Ansel Adams

**Comment by rmjaffe** [comment]
Removed sections of work having to do with Calisphere and Primo harvesting.  Will include this collection on the list of collections that will need to be (re)harvested post-ingest of the combined campus history collections.

**Comment by rmjaffe** [comment]
Given the traffic to this collection CONTENTdm following the Chronicle article, it probably doesn't make sense to take it down right now, even if it is republished in the new DAMS.  We (@rmjaffe & @chesleyperry) will want to consult with @tmariamora and SC&A before taking action on this.

**Comment by tmariamora** [comment]
What if we schedule for 1-2 months from now knowing that we will also put a redirect in place when it happens?

**Comment by rmjaffe** [comment]
I'm pulling this back in to Ready for Development and we can check back on it in a month or so.

**Comment by rmjaffe** [comment]
@chesleyperry We have a green light from SC&A to go forward on taking this collection down.

**Comment by chesleyperry** [comment]
OAC Finding Aid (https://oac.cdlib.org/findaid/ark:/13030/c8ns0z6m/) has no links to digital collection.  Could we add one?
ARK url for digital collection (in DAMS):  https://n2t.net/ark:/38305/f18051sb

URLs for CONTENTdm can't be removed from Google Webmaster Tools until the collection is unpublished.  Most popular URLs from Google Analytics to remove:
https://docs.google.com/spreadsheets/d/1yBapdEf6_3DLStdaXWbq_6VWwYWQKYR8lsPhHRhdlhY/edit?usp=sharing
Google form for removing the URLs: https://www.google.com/webmasters/tools/removals

**Comment by tmariamora** [comment]
I think that should be pretty straightforward. @katedundon can you add the link and report back when done? Thanks!

**Comment by katedundon** [comment]
I'll make the change. It will take a few days. This is an older finding aid that was encoded manually, so the EAD as it is won't validate with the addition of the encoding needed to make the "red eyeball" link at the top of the finding aid appear. I need to import this into ASpace, edit, and republish from that. I'll report back when it's done.

**Comment by katedundon** [comment]
@tmariamora @chesleyperry Finding aid is updated with link to digital collection. https://oac.cdlib.org/findaid/ark:/13030/c8ns0z6m/
