### ISSUE TITLE
(3) Re-ingest of Hitchcock & Holmes lectures

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#29]
### Descriptive Summary

This action should be taken after the ingest of the CMF pilot collection and related issues (e.g. #11 Thumbnails) have been resolved.  Team decided that it would be best to reingest instead of troubleshooting what is in Hyrax now.

### Acceptance Criteria

This is what done looks like

* [x] Lectures have been successfully ingested
* [x] Additional tickets will be created to capture any discovered issues
* [ ] Un-publish old records and redirect to new links (Sue to compile a list of records that will need this redirection)

**Comment by chesleyperry** [comment]
Files and metadata are ready to ingest:  
Spreadsheet: 
//artifacts.library.ucsc.edu/dams_ingest/hitchcock_holmes/Holmes_Hitchcock_Metadata_20191025.xls
Files:
//artifacts.library.ucsc.edu/dams_ingest/hitchcock_holmes/

**Comment by NedHenry** [comment]
I'm sorry it took me so long to get to this. Looking at it now, I notice that some of the lecture files on the ingest server are broken. Five of the files have zero filesize, no data, only filenames. This sometimes happens if a file transfer is interrupted partway through.
The problematic files are:
lcd12372_48.aif
lcd12372_49.aif
lcd12372_50.aif
lcd12372_51.aif
lcd12372_52.aif
lcd12372_54.aif

**Comment by chesleyperry** [comment]
I've re-copied over those six files, plus lcd12372_47.aif.  It looked like that one was only copied partially.

**Comment by NedHenry** [comment]
The issues with this ingest have been almost all resolved, and these works are now ready for QA.

There was a problem with the ingest software failing to recognize parent/child relationships, which also interrupted the metadata inheritance. I implemented the parent/child relationships manually, but we still need to address whatever issue caused the ingest software to fail to recognize these fields. There is a ticket in the backlog to address this (#112) which should be handled before the next complex object ingest. 

There was another problem in which it appeared that many of the audio files failed to ingest properly. In fact, all of the files except one were processed successfully. However, my customization to make Hyrax recognize AIF files as audio files broke on an update to Hyrax, so newly the ingested AIF filesets were not indexed in solr the audio files should be, which broke their display. I was able to fix the issue without re-ingesting any of the files, which all played correctly as soon as Hyrax recognized them as audio (except one).

There is one file that seems to have an irregularity in its encoding (lcd12374_13.wav - "Lecture delivered on November 9, 1976"). This file has a strange mime type associate with Microsoft Excel, and our standard codec simply hangs forever when trying to process it. This file needs to be transcoded outside the system before it can be interpreted correctly. None of the other files have this mime type, and all of them process and play back without any problems. Let me know whether you would like me to transcode this file myself or if you would like to create a new one on your end.

**Comment by chesleyperry** [comment]
I've re-transcoded lcd12374_13.wav and replaced the old file in the dams-ingest/hitchcock_holmes folder.  Let me know if you still the encoding issues and I'll look into it.
All of the audio should be 24bit wav files, with 96000Hz sampling rate.

**Comment by NedHenry** [comment]
I re-ingested that file and it worked fine. Our theory is that the file was corrupted during transfer because of the power outage.

**Comment by chesleyperry** [comment]
QA work finished on [1970-71 lectures](http://digitalcollections.library.ucsc.edu/concern/works/m613n0790?locale=en) finished.  No problems!  Yay!

**Comment by chesleyperry** [comment]
QA work finished on[ History of Western Civ 76-77](https://digitalcollections.library.ucsc.edu/concern/works/q237hv503?locale=en) finished - no problems
QA work finished on [Oriental Art](https://digitalcollections.library.ucsc.edu/collections/m039k7287) - no problems

**Comment by kellyChex** [comment]
@chesleyperry @NedHenry Are we ready to move this to Done?

**Comment by chesleyperry** [comment]
We need to create tickets to unpublish (or delete?) the old collections.  Then I'd consider this done.

**Comment by kellyChex** [comment]
Which one is the old collection?

**Comment by chesleyperry** [comment]
Sorry!  that would be helpful right?  [UCSC Campus Archive](http://digitalcollections.library.ucsc.edu/collections/cj82k733h?locale=en)

**Comment by kellyChex** [comment]
@chesleyperry Created ticket https://github.com/UCSCLibrary/dams_project_mgmt/issues/122 

Please add to it if necessary.
