### ISSUE TITLE
(3) Post-Ingest Alexander Lowry (MS 188), Vester Dick (MS 235); Chuck and Esther Abbott (MS 39)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#294]
### Communication

* [x] Spec Coll notified that collection has been published

### CONTENTdm collection removal 

* [x] Redirect CONTENTdm homepage link to DAMS
* [x] Remove or update links from Library resources (catalog, finding aid, library website, digital collections LibGuide)
* [ ] Google search console report for links to CONTENTdm, submit link removal to Google
* [ ] Google Analytics search for most popular links, send update to external linkers
* [x] ARKS’s updated.  Notify Kate Dundon of new ARK.

**Comment by chesleyperry** [comment]
@NedHenry It looks like these three collections need to be made public.  When I was doing the QA work and declaring these collections done, I was logged in so I didn't realize that one last step needed to be taken.  Could you switch them to public?
