### ISSUE TITLE
Determine tickets for Aeon integration

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#3]
# Supporting Documents:

**UCSD Reading Room Demo Meeting Notes:** 
https://docs.google.com/document/d/1ku1A-yQ4NQPWyg_QOB4TSbIBdDvBq-GR7rhlC6PNwrk/edit#

**Comment by rmjaffe** [comment]
Closing this ticket out -- review and redrafting of tickets and creation of new tickets will carry forward as part of #245.
