### ISSUE TITLE
(2) Review/update Hitchcock & Holmes metadata ingest spreadsheet

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#30]
### Descriptive Summary

Sue observed that the dates recorded on the metadata ingest spreadsheet do not match the dates spoken in the recordings.

### Tasks
- [x] Need to match the different elements with the file names. Need to determine which ones weren’t cataloged. 
- [x] Rachel then to bring the metadata up to standard 

### Related Work 

This needs to be completed before #29 Reingest of Hitchcock & Holmes.

**Comment by chesleyperry** [comment]
Files QA'd and spreadsheet updated.  Rachel remediated edited spreadsheet.  Sue copied files and spreadsheet to dams_ingest.  Now ready for ingest (#29
