### ISSUE TITLE
(3) Re-ingest Ansel Adams (MS 2)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#309]
### Descriptive Summary

Given the volume of changes to image files and to the metadata, as well as update to the collection-work inheritance rules, we've decided that it will be best to remove the images and metadata that have already been ingested and to re-ingest this collection.

### Acceptance Criteria

This is what done looks like:

* [ ] Collection (images and metadata) currently in the DAMS have been removed
* [ ] Collection has been successfully re-ingested

### Related Work 
Will need to have been completed first: #308 Apply parent-child inheritance rules to collection-works 

Will be followed by: 
#310 QA of re-ingested Ansel Adams
#289 Post-Ingest Ansel Adams

**Comment by NedHenry** [comment]
I tried re-ingesting the collection with the new images several times, and was confused to find that some of the processed images were still rotated incorrectly, even though their originals seemed to have the correct orientation. After further examination, I found that the edited original images display with the correct orientation when viewed using Preview, but with the incorrect orientation when viewed using GIMP. It seems that the edited files retain some metadata in their TIF headers about their original orientation. I verified that the system is processing the updated files, but using their old orientation.

**Comment by NedHenry** [comment]
I found a way to automatically re-orient the images according the their EXIF metadata during the automated ingest process. Imagemagick has an "auto-orient" option that is disabled by default. We can turn this flag on, then set Hyrax to pre-process every image in ImageMagick before processing them in Kakadu. 
That means that in the future, images like this should ingest correctly with no added image preparation work.
I still have to apply this change to a few more images from Ansel Adams, and then manually delete all their (incorrect) cached derivative files on the image server. I'll be sure to get that done this afternoon.
