### ISSUE TITLE
(2) QA of Re-ingested Ansel Adams (MS 2)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#310]
### Descriptive Summary

After the collection has been re-ingested, it will need to be QA'd again before the collection is published.

### Acceptance Criteria

This is what done looks like:

* [x] DI checks for file and image quality issues
* [x] RJ checks for metadata issues

### Related Work 

#309 Re-ingest of Ansel Adams
#289 Post-ingest of Ansel Adams

**Comment by chesleyperry** [comment]
The images and UI displays all look like they're ready to go.  @rmjaffe - if you could take one last look at the metadata and give your approval, I think this can be published.
