### ISSUE TITLE
Morton Marcus KUSP (Priority 1)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#312]
### Collection Information

Formal collection title: Morton Marcus, “The Poetry Show” Recordings
Collection number: MS 198?
If a collection is being processed by series, formal series titles and numbering (recorded in the order in which the series will be processed):

### Objects

Type/format and dimensions of objects (within each collection or series) & quantity: 218 audio recordings
Special requirements for each:

### Rights Information

Copyright statement: Property rights reside with the University of California. Literary rights are retained by the creators of the records and their heirs. For permission to publish or to reproduce the material, please contact the Head of Special Collections and Archives.
Rights holder: Donna Mekis
Access rights: Educational use only (Public)
Processing archivist(s):
Section completed by: T. Mora

## Section 2: Metadata Assessment

**Metadata properties to be included:**

**Collection level**
Collection Title (793)
Description: something describing the collection
Description (500s [removing “Compact disc. ”])
Rights Statement
Rights Holder
Access Rights (506)
Rights Status
Digital Publisher
Digital Publisher Homepage
Extent

**Item level**
Title (245)
Alt Title (246)
Date Created (008 - Bytes 11-14)
Description (518, 511, 520)
Donor/Provenance (541)
Subjects (6xx)
Contributor (7xx)
Genre (655)
Physical Format: Cassette tape
Resource Type: Sound
Item Call Number (099)
Extent (300$a [removing “1 audio disc ”])
Publication Date (264c)

Which elements will be added at which points in the workflow and by whom: RJ
Metadata specialist(s): RJ
Section completed by: RJ

## Section 3: Digitization/Technical Processing Assessment

File format(s) for preservation masters: wav
File format(s) for derivatives: streaming mp3, generated on ingest to DAMS
File naming conventions: LCDxxxx. Named for "other call number" assigned to CDs.
File directory: diginit2/ms0198_morton_marcus/MS 198 Morton Marcus Cassettes/MOD for DAMS
Digitization specialist(s): Charles Hanson originally, Scott Campbell doing re-assessment and reprocessing
Link to digitization initial assessment worksheet: https://docs.google.com/spreadsheets/d/1-x_o_7t0gW7mKsbCdgRvpwE3Yk8grYrHAGcBaA9Ln-0/edit#gid=1861278319
Section completed by: SCP

## Section 3b: Audio reprocessing and transcription

- [ ] Master files located on artifacts or Merritt
- [ ] Files Assessed and standards documented
- [ ] Files combined if needed
- [ ] Archival files saved on artifacts2/diginit2 and dams_ingest
- [ ] MP3 files loaded to Otter
- [ ] Transcripts checked
- [ ] Transcripts corrected
- [ ] Transcripts saved to artifacts2/diginit

## Section 4: DAMS Development Assessment

Development work required?: Y/N   (if Y →)
    Brief description of new feature:
    Subject Matter Expert(s):
    Developer(s):
Section completed by:

## Section 5: Display Assessment

Homepage:
Thumbnail Image:
Brief Description:
Customizations, e.g. new format icons:
Digital Initiatives librarian(s):
Section completed by:

## Section 6: Metadata & File Locations

Metadata spreadsheet: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/Morton_Marcus_20210413.xlsx
Files:

## Actions & Acceptance Criteria 
_(specific to each collection & the steps required to prepare it for ingest)_

- [x]  MOU/Collection Information completed
- [x]  Initial project meeting
- [x]  Requested & received MARC records
- [x]  Metadata exported and reformatted as spreadsheet
- [x]  Metadata correction, enhancement, authority control
- [ ]  Assessment of digital files
...

**Comment by tmariamora** [comment]
June 23, 2020 Meeting Notes

DI has saved audio files by LCD number. SCP has compared to inventory of 218 recordings.

Will need to decide if we have multiple tracks or merge (many recordings have A/B designators)

Some discrepancies between spreadsheet and files on server.

**Comment by tmariamora** [comment]
@rmjaffe In talking w/ Kate we realized that we may need to be using this copyright statement from Digital Objects Metadata Best Practices:
Copyright Statement: Property rights for this work reside with the University of California. Literary rights, including copyright, are retained by the creators and their heirs. The digital copy of this work is intended to support research, teaching, and private study. The publication or use of any work protected by copyright beyond that allowed by fair use for research or educational purposes requires written permission from the copyright owner. Responsibility for obtaining permissions, and for any use rests exclusively with the user. For more information on copyright or to order an image, please visit guides.library.ucsc.edu/speccoll/reproduction-publication.

**Comment by rmjaffe** [comment]
**July 30, 2020 Meeting Notes**

There are multiple directories on Diginit for Morton Marcus containing single files, multiple files that need to stitched together, etc.  Files are named by LCD number.

About 50 recordings on the server that are not on the spreadsheet; and about 40 on the spreadsheet that are not on the server.

**Comment by chesleyperry** [comment]
@tmariamora - These are the LCD numbers with files in the Morton Marcus folder on diginit2 that are not on the spreadsheet.  It looks like they might not be KUSP. 
Could you note if there are any recordings you'd like to add to the current project?  
If there are any you that you can't find in the Search, let me know.  That might help me track down some of the files that are on the spreadsheet but not on diginit2.

Recordings on the server that are not on the spreadsheet:

LCD11368
LCD11369
LCD11646
LCD11652
LCD11671
LCD11672
LCD11674
LCD11690
LCD11691
LCD11692
LCD11729
LCD11730
LCD11735
LCD11740
LCD11742
LCD11743
LCD11744
LCD11745
LCD11756
LCD11789
LCD12194
LCD12195
LCD12196
LCD12197
LCD12198
LCD12199
LCD12200
LCD12201
LCD12202
LCD12203
LCD12204
LCD12205
LCD12206
LCD12207
LCD12208
LCD12209
LCD12210
LCD12211
LCD12212
LCD12213
LCD12214
LCD12215
LCD12216
LCD12217
LCD12218
LCD12219
LCD12220
LCD12337
LCD12338

**Comment by rmjaffe** [comment]
Teresa's Marcus discrepancies tracking sheet: https://docs.google.com/spreadsheets/d/1uIhHofMh--PybI_H5dQZComqJ-l49TwmC5GO6wFvdSs/edit#gid=0

**Comment by rmjaffe** [comment]
**August 13, 2020 Meeting Notes**

Decision:  Update filenames to match convention for digitized archival material.

**Comment by rmjaffe** [comment]
Metadata is ingest-ready and is located in the DOMTP Pre-ingest folder.
