### ISSUE TITLE
Find existing plugins for MediaElement.js

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#32]
Note from Ned:  I know we will want some look-and-feel changes needed for the player, which will likely require some styling and scripting work on the front end. I think we need to set out clear goals for this before I can dig into it. We're using MediaElement.js, which has been the leading open source A/V player online for many years. Probably customizing this software will be the focus of near term future A/V work.

### Related Work 

This ticket will be determined once we understand the UI/UX requirements from #25 Create user experience requirements for the media player

**Comment by NedHenry** [comment]
As far as I understand it, there is some UI work that needs doing on the player, but I don't know what the nature or scope of that work is. When I hear what the plan is for this player, I may be able to use existing packages to implement some of desired features (depending on what they are).

**Comment by chesleyperry** [comment]
Both the audio and video files will need to be able to display transcripts.  In my limited research on mediaelement, it looks like there is no transcript solution for audio.  Developers recommend treating all files and video and then displaying static image instead of video.  Then video player can display the transcript.  If this is not acceptable or too difficult, we could look into [AblePlayer](https://ableplayer.github.io/ableplayer/), another open source player specifically designed for accessibility.

**Comment by NedHenry** [comment]
AblePlayer does look good. Unfortunately it looks like it doesn't natively support HLS streaming, which is challenge but not necessarily a deal breaker. Most browsers play HLS on their own, but some important ones don't. To get around this, we would have to stream the files in two different formats if we used AblePlayer, which means creating and hosting two sets of derivative files and streaming solutions. MediaElement.js has a plugin that handles hls streaming itself, regardless of browser, which lets us use HLS for everything (and thereby simplifies our streaming solutions a ton). We couldn't do that with AblePlayer, but we could use it anyway if we don't mind creating more derivatives and doing more work on streaming.
The other options are plugins for MediaElement.js to provide synchronized transcripts. MedieElement does have support for closed captions on videos based on time-coded transcript files, which is a similar enough feature that it should be relatively easy to hack for audio. There are no officially supported plugins for this, but there is at least [one lightweight solution suggested on github](https://gist.github.com/nfreear/905453fb86124bcd3f38). I think we should set aside a day or two of my time to check how hard this would be to implement before committing to swapping players.

**Comment by chesleyperry** [comment]
Agree with Ned.  It looks like mediaelement.js can be made to do what we want.  I think once we've got more user requirements from Jess for the player, this could be worked into a mini-project.

**Comment by kellyChex** [comment]
After the mocks ups for the player were created, https://drive.google.com/drive/u/1/folders/1Ypcd3SdjRgZlzsiRzmwn3Kzc1kSxhK5O, we agreed this ticket is no longer relevant. The biggest changes will be around the layout.
