### ISSUE TITLE
(5) Add dateCreated sorting to collection landing and other results pages

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#324]
As a user, I want to be able to sort search results and collections alphabetically.

Currently sorts are available for relevance, date uploaded, and date modified. This adds dateCreated sorting to the list of options.

### Acceptance Criteria

- [x] Conduct background research to better determine or understand what is involved in this work.
- [x] A-Z sort functionality is viewable and usable to end users.

### Related Work

Add a sort property to the metadata config file #366
Add A-Z sorting to collection landing and other results pages #454 
This ticket is also a prerequisite for #277 and #278

**Comment by rschwab** [comment]
Parent ticket: [Add a sort property to the metadata config file](https://github.com/UCSCLibrary/dams_project_mgmt/issues/366)

**Comment by JessWaggs** [comment]
Will also need capability to sort collections alphabetically: UCSCLibrary/dams_project_mgmt#277 and UCSCLibrary/ucsc-library-digital-collections#375

**Comment by katedundon** [comment]
Adding to this: As a user, I want to be able to sort search results and collections by date created, both in the order of date newest and date oldest.

**Comment by NedHenry** [comment]
I looked into this issue today. I would probably assign 5 points to finishing this task, mostly just because of having to re-index the whole collection. This is mostly a task that will run in the background while I do other things, but it may take some babysitting.

- The config file needs to updated to mark which fields need to be sortable
- The entire collection needs to be re-indexed to reflect the sortability of these fields
- There is a bug related to setting a default for ascending or descending sort order when sorting by title (shouldn't be too hard)

**Comment by NedHenry** [comment]
I believe that the coding part of this is complete, though it has not been thoroughly tested in every relevant situation. It requires re-indexing our entire collection with these sorting properties, which takes a couple of days. This re-indexing is currently in progress.

**Comment by NedHenry** [comment]
This brought up a few issues. 
First, some works were not re-indexing properly. That problem still needs to be debugged and fixed.
Second, after re-indexing, the title property sorting is not working as expected. I think the title is being broken into separate words before sorting, while it ought to be considered as a single string. This needs further work.

**Comment by rmjaffe** [comment]
@NedHenry Is going to split up this ticket into two tickets:  one focused on date sorting which will be flagged as a priority and one focused on alpha sorting which will be on hold.

**Comment by snehagunduraoUL** [comment]
Sort by Date created is available on prod. @rmjaffe This ticket can be closed.
<img width="1499" alt="Screen Shot 2021-12-08 at 12 17 11 PM" src="https://user-images.githubusercontent.com/92340457/145278156-25c6f868-2eaf-448d-91d5-63fbdbd659b4.png">

**Comment by rmjaffe** [comment]
Thanks for the heads up @snehagunduraoUL!  @JessWaggs, would you mind taking a quick look?  Also, it's not recorded in the ticket, but I recall that we had discussed removing date uploaded and date modified from the sorting options.  Is that something we still want to do?
