### ISSUE TITLE
Gather collection-level metadata source/sensitivity notes for already published collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#341]
### Descriptive Summary

We would like to add collection-level metadata for collections ingested/published before collection-level metadata was introduced.  This ticket has been created to collect **metadata source notes** for these collections so that it can be added once we have determined our strategy for how to best "add" and display it.

Metadata source notes will be used to describe where the descriptive information originated, who contributed to it, and/or what issues may exist within it.

### Collection Level metadataSource Values

**Harry Mayo**
metadataSource:

**MS 20:  RMB-PJ**
metadataSource:

Some image titles in this collection contain offensive terms that identify subjects by race, ethnicity, or physical appearance. These titles were supplied by the artist(s) or were derived from inventories provided by the donor. In publishing this metadata, we recognize that these terms do not align with current terminology and practice; we chose to retain them to reflect and preserve the context in which these images were created and named. Some photographs also contain nudity.

**UA 50: Campus History Photographs**
metadataSource:

**Porter College**
metadataSource:

**UCSC Faculty Lectures**
metadataSource:

**Shakespeare SC Posters**
metadataSource:

**SC Co. History Collection**
metadataSource:

Some image titles in this collection contain offensive terms that identify subjects by race, ethnicity, or physical appearance. These titles were supplied by the artist(s) or were derived from inventories provided by the donor. In publishing this metadata, we recognize that these terms do not align with current terminology and practice; we chose to retain them to reflect and preserve the context in which these images were created and named.

**Cabrillo Music Festival**
metadataSource:

**Ansel Adams**
metadataSource:

### Acceptance Criteria

This is what done looks like:

* [ ] Collection level metadata source notes for each of the collections listed above have been added to this card

### Related Work 

#285 Determine strategy for retroactively adding collection-level information for collections that have already been published
#342 Add metadataSource property to metadata schema

**Comment by rmjaffe** [comment]
@tmariamora Here's a ticket for the metadata source notes.

**Comment by rmjaffe** [comment]
@tmariamora @katedundon:  Are we done?  Can I close this ticket?

**Comment by tmariamora** [comment]
Yes, I believe we are good to go.
