### ISSUE TITLE
(3) Determine display details for complex image objects

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#345]
### Descriptive Summary
We need a clear plan on how we want to display complex image objects. 
Some vague potential plans are outlined in the Background section below. This ticket mainly involves choosing between them (or creating a new and better option) and then filling out the details of the implementation in new issues. 

### Background 

- Concerns: 
The Universal Viewer is a useful and high-quality tool both for displaying images and navigating through thumbnails, but it is not very flexible. It may be difficult to make our document structure and metadata levels clear when displaying complex items through the Universal viewer. 

- Options (Ned's Ideas):
1. Simplest option: thumbnails and links only for child & sibling images
The parent work page shows the parent work metadata, one large image from a "featured" child work, and the images from all the other child works as thumbnails. Each image from a child work links to that child work's individual page. Child works can each be loaded in the Universal Viewer from their own pages if the users want to zoom in. No Universal Viewer is available on the parent work page. The Universal Viewer on the child work page does not display the child work's siblings. Thumbnails of sibling images (with links to the sibling page) can be displayed outside of the Universal Viewer.
Pros: 
-- minimal programming necessary to set it up
-- clear which metadata should be displayed at all times
Cons:
-- slow if the user wants to scroll through many images

2. Custom Javascript Option 
This option starts off a lot like option 1. However, we add custom javascript to allow users to interact with the child work (and/or sibling work) thumbnails, to see larger versions of these images and child work metadata clearly without leaving the parent work page.
For example, when viewing the page for a parent work with several child image works, we might see thumbnails and titles initially visible for each child image. Clicking on any child image could cause that thumbnail to grow into a larger display of that child image, with any extra metadata from the child work right next to it (and clearly separate from the parent work metadata, which is displayed elsewhere on the page). This would happen without leaving the parent page, and without loading the Universal Viewer. Just like in option 1 above, the Universal Viewer would only be loaded for single-image works when a user specifically asks to zoom in. 
Pros:
-- User can quickly scroll through child works & metadata
-- No need to try reconcile our data structure with Universal Viewer's displays
-- Relatively easy to make it clear which metadata is attached to the parent vs child work
Cons:
-- Moderate programming required (~2 wks)
-- Custom solution may require ongoing maintenance
-- Downplays the fancy zoomability supported by our IIIF server & viewer

3. Universal Viewer Option
The parent work's page displays a Universal Viewer by default. This Universal Viewer contains a collapsible panel with thumbnails and titles of child image works. When a user clicks on the child work thumbnail or title, the child work image is displayed in the main UV panel, allowing zoom functions. Key elements from child work's metadata may also be displayed in an extra collapsible panel with in the UV. The parent work's metadata would still be displayed prominently underneath the UV. 
Pros:
-- features our fancy IIIF image functionality front and center
-- fast for users to scroll through images and zoom into them
Cons:
-- moderate to heavy programming load (unpredictable)
-- customizing Universal Viewer functionality has been a huge pain in the past
-- unclear how to display sibling relationships clearly
-- not sure the distinction between parent and child metadata would be clear
-- difficult for the team to make good decisions within the ambiguous constraints of Universal Viewer while Ned is simultaneously learning about those constraints. 

### Acceptance Criteria

* [x] We have chosen which display approach to use from those outlined above
* [x] We have created one or more issues for implementing the chosen approach
* [x] We have talked through all predictable questions about how to implement the chosen approach and documented our answers (or ideas) in the newly created issues

**Comment by JessWaggs** [comment]
Related tickets:
#263
