### ISSUE TITLE
(1) Conversation: Documenting data model and object types

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#346]
### Descriptive Summary

Meet to discuss next steps for better documenting our data model, its complexities, and our decision making around how we're choosing to handle different types of objects.

This would also be a good opportunity to review how child and sibling images should look/work in the Universal Viewer, both at present and down the road.  The team has already had some conversation around this, but it would be helpful to check in on decisions made as well as future directions.

### Background 

From Ned's 8/6 update on Slack: I think I’ve figured out how we can customize the IIIF manifests for these works so that they will display nicely in the Universal Viewer. We should discuss the details how this should work/look for child and sibling image works. For now, I think it makes sense for me to disable the Universal Viewer for complex image works and simply display a list of child works and thumbnails with links to each child work’s page (which can each display a Universal Viewer for its single image). Perhaps we had already decided on this as an interim solution, and I just forgot about this decision as I made other upgrades.

### Acceptance Criteria

This is what done looks like

* [ ] Discussion had
* [ ] Past decisions revisited/reaffirmed
* [ ] Plan for producing relevant documentation

### Related Work 
Universal Viewer not loading for compound images #335
Detail user needs for child works #263

**Comment by chesleyperry** [comment]
Jess, Ned and Sue met 9/3/20 to begin the conversation.  
Notes:
Two types of compound objects: 
1. Multiple page albums or scrapbooks.  One work with a fileset attached.  Viewable in Universal Viewer.
2. Nested works.  Objects with multiple works in sibling and parent/child relationships.  Examples are Cabrillo Music Festival concerts and the series groups in RMB/PJ.

Documentation needed for type 2.
Action Item: Jess will put together a Google Doc with links to decisions, tickets, and mockups for the various displays, including updating #263. 
Further conversation needed:
In the ingest process - how to signify the "representative image" for a grouping?  Probably the easiest way is a column in the ingest spreadsheet but we need more detail.
How to treat and display parents and children in the search and retrieval process.

**Comment by rmjaffe** [comment]
@chesleyperry Thank you for sharing these notes!  Let's address the "further conversation" items in the 9/17 meeting.

**Comment by chesleyperry** [comment]
JW - Documentation for different viewers for different format types.
RJ - 2 page data model explanation
Configuration file:  Aim for consistent display, across formats.

Further conversation needed:
In the ingest process - how to signify the "representative image" for a grouping? Probably the easiest way is a column in the ingest spreadsheet but we need more detail.
Use cases: 
thumbnails for home page
thumbnails for collection of collections

Suggested solution:
Add a column to the spreadsheet for "representative image" and "thumbnail image" include the filename for those images
Minimal work:  update the config file to accept the images.  Ideally, we staff could choose the image from the staff interface.  The idea situation could be developed in the longterm.

Search and retrieval, when to display siblings, parents, and children:
See Jess's doc: https://docs.google.com/document/d/1dJ2zSbro2FZnfyOsOt-MZOgLuCG29yZJfhnN1eJirfE/edit
Jess will update the document and confirm it still captures our plan see #359 

Retroactively updating published collections: 
Once Ryan's finished collection landing page and collection info (using CMF).
Rachel can create a spreadsheet that includes the collection ID (from the URL) with collection level metadata. She'll create a ticket for this.
To retroactively update preferred or representative images, we'll work on developing the functionality in a browser through the dashboard.
RAchel will create a ticket to diagram the data model (object types: fileset, complex objects, image sets).  Jess will start with a user interaction diagram and ask Rachel and Ned to flesh it out.
