### ISSUE TITLE
(1) 2nd round of Broken Links for CMF

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#349]
### Descriptive Summary

QA found the following links are broken in the CAbrillo FEstival Recordings collection:

1982 Cabrillo Music Festival: Concert 10
https://digitalcollections.library.ucsc.edu/concern/works/mp48sg193?locale=en

1982 Cabrillo Music Festival: Concert 13
https://digitalcollections.library.ucsc.edu/concern/works/gf06g472p?locale=en

1982 Cabrillo Music Festival: Concert 2
https://digitalcollections.library.ucsc.edu/concern/works/np193b91d?locale=en

1982 Cabrillo Music Festival: Concert 6
https://digitalcollections.library.ucsc.edu/concern/works/s1784p10r?locale=en

1982 Cabrillo Music Festival: Concert 7
https://digitalcollections.library.ucsc.edu/concern/works/qj72p936h?locale=en

1982 Cabrillo Music Festival: Concert 9
https://digitalcollections.library.ucsc.edu/concern/works/5q47rq86q?locale=en

### Actual Behavior

DAMS displays error message:
"The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

Problem is most likely similar to problem in last CMF broken link report (#268 )

**Comment by NedHenry** [comment]
Fixed. When I deleted the old collection that had the pilot concerts, these works did not re-index properly. The Solr index still thought that these works were part of the old collection, which had been deleted, causing an error. All I had to do was re-index these works and the problem was resolved.
