### ISSUE TITLE
(5) Implement nested collection display

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#350]
### Descriptive Summary

Some front-end development work will be necessary to ensure that the nested collection relationships display the way we want. A bit of back-end development may also be necessary to ensure that search results include the right objects. We may need to:
- customize the work show page to include grandparent collection info
- customize the parent collection landing page to make it clear that it contains other collections
- customize the child collection landing page to include information about its parent
- customize search results to account for object hierarchies in an intuitive way for the user.
 
The details of the work will be decided in issue #348.

### Acceptance Criteria

* [ ] The test nested collections that we ingested into the sandbox site in #347 can be viewed in that site
* [ ] The display of the test nested collection matches all the decisions we made in #348 

### Related Work 

#347 #348

**Comment by JessWaggs** [comment]
Related tickets:
#199 & #147 Mock up for search results page (desktop and mobile)
#223 & #225 Apply new search results styling (desktop and mobile)
