### ISSUE TITLE
(3) Child Work Page Mock Up for Mobile

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#358]
### Descriptive Summary

Mock up display of child works within a parent, including interactions, for mobile.

### Acceptance Criteria

This is what done looks like

* [x] Mock up for mobile
* [x] Create card for Apply new child work page (Mobile) as a sister card to Apply new child work page (Desktop) #357 

### Related Work 

#263 Detail User Needs for Child Works
#357 Apply new child work page (Desktop)

**Comment by rschwab** [comment]
@JessWaggs the mockup is still needed for this, right?

**Comment by JessWaggs** [comment]
@rschwab Here is my first draft:
![Screen Shot 2021-02-03 at 3 45 55 PM](https://user-images.githubusercontent.com/6412857/106824257-5332ba80-6637-11eb-8bc1-add9a376a594.png)

Biggest difference from desktop is that the thumbnails for the sibling images appear below the main image and I think the scroll bar can be hidden (scrolling is just more intuitive on mobile so it seemed unnecessary, particularly if we can show a small segment of thumbnail on the far right of the row).

Is it possible to also reduce the font size for item titles for mobile screens? Some of the titles are quite lengthy and push the image far down the screen at their desktop size.

**Comment by rschwab** [comment]
This looks great, in my opinion. Are the Download, Share, and Cite buttons below "more information", or hidden altogether? Same with the About the Collection box?

**Comment by JessWaggs** [comment]
I like what we do now with the single images, where the buttons appear below more info and the about the collection box is even below that. So no change there, I think : )

![Screen Shot 2021-02-08 at 3 01 06 PM](https://user-images.githubusercontent.com/6412857/107292399-a5505300-6a1e-11eb-827e-1928127adcfa.png)
