### ISSUE TITLE
Create data model diagram & document object types

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#362]
### Descriptive Summary

Following some discussion the team has decided that it is a good idea for us to create a diagram of our data model (nested collections and nested works) and to document types of objects that we're ingesting (simple objects, complex object w/fileset, complex object w/child works).

### Acceptance Criteria

This is what done looks like:

* [x] Data model diagram created
* [x] Object types documented

### Related Work 

#346 Conversation: Document data model and object types

**Comment by rmjaffe** [comment]
@chesleyperry @JessWaggs I think we decided that the diagrams from the [DAMS walk thorough](https://drive.google.com/drive/folders/0AF4_Eo0RrYugUk9PVA) were sufficient enough to call this done?  I can also peel them out into a separate doc so that we can link to it from the project wiki.

**Comment by JessWaggs** [comment]
Yes - I think the diagrams from the slides meet the needs!
