### ISSUE TITLE
Broken links for multi-file sets in Combined Campus History Ingest

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#367]
### Descriptive Summary

The links for the multiple file works (brochures and scrapbooks) from the Combined Campus History Ingest are not working.  Each one results in an error page: 

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Following is the list of individual titles and links:

https://digitalcollections.library.ucsc.edu/concern/works/q524jr713?locale=en
Campus geology, University of California, Santa Cruz [1993]

https://digitalcollections.library.ucsc.edu/concern/works/cn69m732c?locale=en
UC Santa Cruz Campus Natural Reserve [1988]

https://digitalcollections.library.ucsc.edu/concern/works/th83m247h?locale=en
Long Range Development Plan University of California Santa Cruz Campus [1990]

https://digitalcollections.library.ucsc.edu/concern/works/9306t228k?locale=en
University of California, Santa Cruz map guide 1972-73

https://digitalcollections.library.ucsc.edu/concern/works/76537462m?locale=en
University of California Santa Cruz : 1988 Long Range Development Plan

https://digitalcollections.library.ucsc.edu/concern/works/db78tg238?locale=en
Self guided walking tours of the University of California, Santa Cruz campus [1971]

https://digitalcollections.library.ucsc.edu/concern/works/zk51vk74d?locale=en
University of California Santa Cruz : map guide [1971]

https://digitalcollections.library.ucsc.edu/concern/works/js956j908?locale=en
F. Louis Fackler scrapbooks, Box 3: 1970-1977

https://digitalcollections.library.ucsc.edu/concern/works/kk91fp55s?locale=en
F. Louis Fackler scrapbooks, Box 5: Fackler's retirement party, 8/29/1992

https://digitalcollections.library.ucsc.edu/concern/works/sn00b2075?locale=en
F. Louis Fackler scrapbooks, Box 2: 1966-1969

https://digitalcollections.library.ucsc.edu/concern/works/hq37vr577?locale=en
F. Louis Fackler scrapbooks, Box 4: 1976-1995

https://digitalcollections.library.ucsc.edu/concern/works/k35697268?locale=en
F. Louis Fackler scrapbooks, Box 1: 1963-1966

https://digitalcollections.library.ucsc.edu/concern/works/d791sj85j?locale=en
Cowell College Culture Break, January 29-31, 1970: brochure
  |  

### Acceptance Criteria

This is what done looks like

* [ ] Each items should open up the object in the universal viewer, with all pages listed.

### Related Work 

This bug part of the ingest for the Combined Campus History Collections #271 and the QA for that ingest #364 .

**Comment by NedHenry** [comment]
The links are no longer broken, but the files that make up these compound objects were ingested as individual works (instead of multiple filesets within the same work).

**Comment by NedHenry** [comment]
I fixed the object structure, so the files are now filesets instead of individual works.
