### ISSUE TITLE
Remove thumbnail view options ('grid' view only)

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#371]
### Descriptive Summary

We no longer want to offer multiple layout options for search results and lists of objects. We have only customized one of these views, and the others are not fully functional and do not add anything. 

### Acceptance Criteria

* [ ] The buttons to swap views are not included in the html in search results pages or collection landing pages
* [ ] The URL parameter "view" cannot override the default layout (view=list does nothing)

**Comment by NedHenry** [comment]
Duplicate of #380

**Comment by rschwab** [comment]
Pull request above resolves the display issue, but does not prevent URL parameters from altering the view. So half of this issue is still open.

**Comment by NedHenry** [comment]
I am altering this ticket to represent the portion of the work NOT covered by Ryan's pull request, which distinguishes it from #380. We can use #380 to track the deployment of Ryan's pull request (which fully hides these alternate view options) and keep this ticket to represent the remaining work required to fully disable these options.
