### ISSUE TITLE
Hide list, masonry and slideshow browse views

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#380]
### Descriptive Summary

Hide the option to toggle between browse views.  Present the gallery/grid view as the default.

![Screen Shot 2020-10-15 at 4 07 14 PM](https://user-images.githubusercontent.com/32003407/96195024-8cb4ae00-0f00-11eb-8208-33f4e924fe5a.png)

### Background 

There are issues/concerns with some of the view options, for example the display of the full metadata record vs. selected properties in the list view, but we don't want to expend developer effort on improving or refining these views at present.

### Acceptance Criteria

This is what done looks like:

* [x] The buttons that allow users to switch views are hidden
* [x] Gallery/grid view is the default view

**Comment by rmjaffe** [comment]
This is a dupe of #371

**Comment by rschwab** [comment]
Here's the pull request with code info and screenshot: https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/133

**Comment by chesleyperry** [comment]
I've checked this on staging - http://digitalcollections-staging.library.ucsc.edu/collections/jd472x03h?locale=en and it looks good to me.  Both of the acceptance criteria are met,
