### ISSUE TITLE
(2) SC Co. History: image/metadata mismatch corrections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#381]
### Descriptive Summary

Nine image files were matched to the wrong metadata records on the spreadsheet during physical processing of the collection.  We want to update the metadata for each of these files in the DAMS with the correct descriptive information.

Spreadsheet with corrected metadata is in the DAMS Team Drive: https://drive.google.com/file/d/1a6XfG116n8kGVoywjZcj-KBPkgOo09CP/view?usp=sharing

### Acceptance Criteria

This is what done looks like

* [x] Create spreadsheet with correct metadata
* [x] Overlay metadata records for effected files in DAMS with correct metadata

**Comment by NedHenry** [comment]
I switched the images and metadata. All of the images now match the corresponding metadata.

**Comment by rmjaffe** [comment]
@tmariamora Has offered to QA these.

**Comment by tmariamora** [comment]
Looks great. Thanks all!!
