### ISSUE TITLE
(1) Include UA 50 & Porter College collections in Campus History collection group

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#382]
### Descriptive Summary

The UCSC Photography Services Collection (UA 50) and Porter College (UA 133) need to be included as a collections within the larger UC Santa Cruz Campus History collection of collections.

### Acceptance Criteria

* [x] UA 50 appears on UC Santa Cruz campus history collections c-of-c landing page
* [x] UA 133 appears on UC Santa Cruz campus history collections c-of-c landing page

### Related Work 

#231 create collection of collection landing pages, #350 Implement nested collection display

**Comment by rmjaffe** [comment]
@NedHenry I overlooked Porter College; it also needs to be added to the UC Santa Cruz Campus History Collections c-of-c.  I updated the ticket to include this collection.

**Comment by NedHenry** [comment]
This part is done; the porter college and photography services collections appear in the campus history collection-of-collection page. That page is currently ugly, and will be restyled very soon.
