### ISSUE TITLE
(2) Display metadata source notes below collection descriptions on collection landing pages

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#384]
### Descriptive Summary

Metadata source notes (metadataSource) have been created for two collections, RMB-PJ and SC Co. History (#341). We'd like these notes (added to the collection records as part of #285) to display under the collection description(s) in the About the Collection box. 

### Acceptance Criteria

This is what done looks like:

* [x] Metadata source notes are visible to users in the about the collection box on the collection landing pages

### Related Work 

#341 Gather metadata source notes from SCA
#285 Apply collection-level metadata for older collections

**Comment by rmjaffe** [comment]
@NedHenry I'm probably calling that box the wrong thing, but yes, apply the change to the collection landing pages.  The text of the metadata source note can go right under the collection description.  Does that box containing the collection descriptions have a name?

<img width="645" alt="Screen Shot 2020-11-18 at 4 30 27 PM" src="https://user-images.githubusercontent.com/32003407/99604979-962bad00-29bb-11eb-8714-e8891f35a521.png">

**Comment by chesleyperry** [comment]
It looks like the text is truncated and repeating.  See the image as example.  I think we want the whole paragraph to display once, with no truncation.
![Screen Shot 2020-12-01 at 12 31 23 PM](https://user-images.githubusercontent.com/18403313/100793614-41cbf880-33d1-11eb-8592-c4d84249d237.png)

**Comment by rmjaffe** [comment]
Source notes look good on the collection landing pages for the collections that have them, i.e. SC Co. History Photos and RMB-PJ.
