### ISSUE TITLE
(3) Enabling non-affiliate users to view child metadata for restricted AV content

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#387]
### Descriptive Summary

At present non-affiliate users are unable to view child or track-level metadata records for concerts within the Cabrillo Music Festival collection.  We want to enable these users to view and click between child metadata records without also enabling them to play tracks.

In our 10/28 email thread, Ned describes of the work needed to make this possible:

It isn't hard at all to have the metadata below change when you click on the track name, even when the tracks are restricted. We decided to have those tracks link to the child page URLs instead of affecting the embedded player directly. The audio player embedded in each page only displays a single track; it isn't really a playlist, it just looks like one. The links to the other tracks are normal html links, not part of the player at all - so they should work the same way regardless of whether the player is restricted.

This setup makes it slower for the users to load each track and to skip through tracks than if we used a real playlist, but this way it is also easier for us to display the correct metadata and URL for the work being viewed. There are ways to get the best of both worlds using fancy javascript, and we should do those in the more distant future when we have spare development time.

### Background 

When implementing first pass VRR/restricted access, we failed to note during our QA process that the interface and functionality available to non-affiliate users did not conform to the [mockups](https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit), which show links for each of the tracks.

This issue is not an error as much as was an oversight.

### Acceptance Criteria

This is what done looks like:

* [ ] Track list is visible to non-affiliate users as shown on [mockup](https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit)
* [ ] Non-affiliate users are able to view child or track-level metadata records
* [ ] Non-affiliate users are not able to play tracks
* [ ] Create work ticket(s) for developing a 'real' playlist in the future vs. our current list of links

**Comment by NedHenry** [comment]
This is now deployed on staging for QA
<img width="1805" alt="Screen Shot 2020-12-02 at 12 14 54 PM" src="https://user-images.githubusercontent.com/6326776/100926730-bd44ad00-3498-11eb-9b16-208028eadddf.png">

**Comment by rmjaffe** [comment]
@chesleyperry @JessWaggs @tmariamora Would you mind taking a look at this on staging to confirm that it looks good and meets your expectations?

**Comment by chesleyperry** [comment]
I think the staging server is limited to the campus IP range and we have to be logged into the VPN to see it.  So - we can't see what an unauthenticated non-affiliate would see when we're looking into staging.  @NedHenry - can you think of a different way of doing QA for this function?

**Comment by tmariamora** [comment]
I've logged out of everything (vpn/ DAMS) and am seeing the metadata (screenshot attached) so maybe it's actually up in production? Regardless it looks good to me!
![Screen Shot 2020-12-03 at 8 22 39 AM](https://user-images.githubusercontent.com/60992369/101057371-d30dad00-3540-11eb-8798-ff5daa06c855.png)

**Comment by rmjaffe** [comment]
Yay!  I can confirm that I'm seeing the same in production.

**Comment by JessWaggs** [comment]
I had the same question/concern about QAing as Sue - but I can also see this in prod : )

The only "issue" I see is that the track list is below the yellow alert rather than to the right of it. But that's purely aesthetic. The track list click-thru worked as expected.

**Comment by NedHenry** [comment]
As you have all noticed, the metadata display is already on production. There is also a styling change on staging that makes the track list display beside the yellow box as shown in the image above (and mock up). 

Sorry it is difficult to do QA on these in staging. I can set up a special authentication backdoor for you to view the staging site from off campus for this kind of QA. I have done this before but it will take me an hour or two to remember how to do it again. Let me know if this becomes a priority for you.
