### ISSUE TITLE
(3) Publish combined campus history collections

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#389]
### Descriptive Summary

The combined campus history collections have been ingested but not published. We need to publish them. The collections should not be featured on the homepage until the "collection of collections" homepage work is complete.

### Acceptance Criteria

This is what done looks like:

* [x] All works and collections within the combined campus history collection are accessible to the public
* [x] After the collection-of-collection page styling is deployed
* [x] Feature the combined campus history collection (but not the subcollections) on the homepage, i.e. swap out UCSC Photography Services Photos collection with representative image for and link to combined campus history landing page.

**Comment by NedHenry** [comment]
All of the individual works and filesets in these collections are now accessible to the public. The collection landing pages are still hidden. Once the collection-of-collection pages are finalized, this will be added to the homepage.

**Comment by NedHenry** [comment]
The last part of this ticket - the updated homepage - is ready for QA on staging: 
https://digitalcollections-staging.library.ucsc.edu/
<img width="1686" alt="Screen Shot 2020-12-02 at 11 42 53 AM" src="https://user-images.githubusercontent.com/6326776/100926950-0694fc80-3499-11eb-816c-3c7cde7c2f79.png">

**Comment by chesleyperry** [comment]
I'm having a difficult time viewing the collections on staging dashboard (https://digitalcollections-staging.library.ucsc.edu/dashboard/collections?locale=en).  it gives the error message - "we're sorry but something went wrong."

Here's the direct link to the staging combined collections page: https://digitalcollections-staging.library.ucsc.edu/collections/3x816q48g?locale=en

Issues:
1. I think Jess had commented that the line spacing between the fields and lines could be bigger, but I'm not sure which ticket that's on.  Here's a screenshot: 
<img width="307" alt="Screen Shot 2020-12-15 at 11 03 41 AM" src="https://user-images.githubusercontent.com/18403313/102260470-55915780-3ec5-11eb-9000-b2599777bffe.png">
2. Once you go to the [collection page for PIO](https://digitalcollections-staging.library.ucsc.edu/collections/t722hc79t), some of the thumbnails are squished.  See example.  This isn't the case with all collection, and it isn't a problem on production, so maybe it's not a real issue?
<img width="184" alt="Screen Shot 2020-12-15 at 11 06 17 AM" src="https://user-images.githubusercontent.com/18403313/102260897-c9cbfb00-3ec5-11eb-97c5-3f0f37cef811.png">

**Comment by rmjaffe** [comment]
@chesleyperry & @JessWaggs before publishing this [combined campus history landing page](https://digitalcollections.library.ucsc.edu/collections/3x816q48g?locale=en), are there any display/styling issues that need to be resolved first?  I remember the line spacing being an issue (see Sue's comment above). If so, have fix tickets been created for each of these?

**Comment by NedHenry** [comment]
@chesleyperry fixed

**Comment by chesleyperry** [comment]
@NedHenry I checked the featured collection link on staging - functions and looks good.  I think this is ready to deploy to production.
