### ISSUE TITLE
(8) Ingest UA36 Lick Collection - Complex Objects

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#390]
### Descriptive Summary

Large image collection which contains one series of simple objects as well as a series of complex objects (albums and front/backs).  This ticket is for the ingest of the complex objects; following the ingest of the simple objects, the complex objects metadata sheet will need to updated.

### Background 

This is a legacy collection currently up in CONTENTdm.

### Acceptance Criteria

This is what done looks like:

* [x] Collection has been successfully ingested
* [x] Images display properly
* [ ] Metadata displays properly

### Related Work 

Lick pre-/post-ingest card #169
Lick simple ingest card #56

**Comment by NedHenry** [comment]
A known issue with certain complex objects (e.g. [this album](https://digitalcollections.library.ucsc.edu/concern/works/b8515r794)) was fixed today. This record now loads successfully, although the coverpage exhibits the unrelated issue #336.

There is still the issue of collection level descriptions being inherited by works with no descriptions present. Descriptions should be inherited from parent work to child work, but not from collection to work.

**Comment by chesleyperry** [comment]
For astronomer portraits that have accents in the names, an underline is displaying instead of the accented character. Example: https://digitalcollections.library.ucsc.edu/records/vh53wz85d
Hugo Gyld__n should be Hugo Gyldén
