### ISSUE TITLE
(2) Environmental scan for aeon integration

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#399]
### Descriptive Summary

Review other DAMS sites, including our legacy Cdm site, to find examples of integration with Aeon.

### Acceptance Criteria

This is what done looks like

* [x] Discuss SCA needs for Aeon/DAMS integration with Kate & Luisa
* [x] Evaluate 3-5 sites that provide users with image or reproduction purchases/orders
* [x] Mock up Aeon request button
* [x] Sign off from SCA on proposed dev work

**Comment by JessWaggs** [comment]
Have been unable to find other DAMS with Aeon request buttons. JW will check in with Kate.

**Comment by JessWaggs** [comment]
My student worker evaluated 7 other DAMS sites and could not find one with a Request button for reading room or reproduction requests. 

I have reached out to our Aeon rep to ask if they can point us to some Aeon/DAMS site integrations.

**Comment by JessWaggs** [comment]
I was unable to find other Aeon sites so I evaluated the NYPL digital collections and several enterprise sites that sell digital images.

I found that all used clear language and iconography to indicate to users that both 1) the button would allow them to procure a high resolution version of the image and 2) they would need to pay for the image

SCA indicated that they do not need to include the option to access objects in the reading room via Aeon request, only initiating a reproduction requests is needed.

**Comment by JessWaggs** [comment]
Proposed button based on SCA needs and mini-scan:

![Screen Shot 2021-02-22 at 4 27 18 PM](https://user-images.githubusercontent.com/6412857/108787863-80ce9d80-752b-11eb-9f37-ba648617753c.png)

**Comment by JessWaggs** [comment]
@katedundon  @tmariamora 
What are your thoughts on the proposed "Order a Scan" button that would point only to the reproduction request form (not including the reading room form option)?

**Comment by katedundon** [comment]
I like this Jess. I think the order button pointing only to the repro request form works. I don't see much use in building functionality for reading room requests as this would be so rare as to not be worth your time (in my opinion). 

I like the download option for collections from which we can allow direct downloading (I know Mayo is one exception). I'm thinking that we need to explain somewhere that the free downloadable file is a certain low resolution, and that a high resolution file is available for purchase. Maybe this can be accomplished in an About page that is linked below or to the side of these buttons somewhere? Or would "Order a High Res Scan" fit in this button?

**Comment by JessWaggs** [comment]
@katedundon  That's a great idea!

Currently the Download button opens a pop up with rights info and options. We could definitely put a note at the bottom with something like, "For higher resolution files you will need to order a scan" or some such wording.

**Comment by tmariamora** [comment]
I agree whole heartedly with what Kate said. I think the order button will do the job 98% of the time. And yes, some explanatory text about higher res would be nice.

Thanks!
