### ISSUE TITLE
(3) Apply new breadcrumb style 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#40]
### Descriptive Summary: 

As a user, when I navigate to a Collection or a Work, I should see the full titles of Collections and Works in the breadcrumbs. 

### Actual Behavior:

Currently if the title is long, it does not show in full in the breadcrumbs. 

### Mock Up:
![Screen Shot 2019-11-20 at 5 35 57 PM](https://user-images.githubusercontent.com/9621070/69292956-3f2ea480-0bbc-11ea-92d2-b8c41f50b778.png)

### Style Guide:
Font: 
Color:

**Comment by kellyChex** [comment]
Holding off on adjusting breadcrumbs as we've decided About the Collection section may be more helpful. This work done in https://github.com/UCSCLibrary/dams_project_mgmt/issues/131. 

We may even decide to remove the breadcrumbs. TBD.

**Comment by rmjaffe** [comment]
@rschwab @JessWaggs Is this ticket something that can be taken on or resolved as part of the work on #131?  If not, should it remain in the Icebox, or would it make sense to bring it forward into planning?

**Comment by rschwab** [comment]
@rmjaffe I'd be happy to work on this during this or next sprint. I could go either way on whether to merge the tickets or not. The work for this will be in different files than 131, but they will both utilize some of the same metadata.  I would lean slightly towards keeping it separate, just to minimize ticket-wrangling and ease of pointing more granular work.

**Comment by JessWaggs** [comment]
I think we decided to remove the breadcrumbs? But maybe it would be good to get consensus on that : )

If that's the case, we could rewrite the ticket as a removal rather than a restyling.

**Comment by rmjaffe** [comment]
@rschwab Whatever works best for you, so let's keep them separate.  I'll bring this over into planning. Thanks!

**Comment by rmjaffe** [comment]
@JessWaggs Shoot, it looks like we responded at the same time.  What if we leave it as it is and where it is for now (planning), and we can discuss in our next planning meeting?

**Comment by rschwab** [comment]
@JessWaggs I should've asked in planning, but I hadn't noticed that there was some ambiguity on this ticket. Is the goal to remove breadcrumbs, or to show the full titles instead of a truncated version?

**Comment by rschwab** [comment]
Pull request linked above.

Screenshot:
![Firefox_Screenshot_2020-12-15T22-54-09 039Z](https://user-images.githubusercontent.com/515412/102282506-8ed9bf80-3ee5-11eb-996c-4da427a3deb0.png)

**Comment by chesleyperry** [comment]
This looks good to me on staging.  @JessWaggs can you take a look?  Then I think it can be put into production.

**Comment by JessWaggs** [comment]
@chesleyperry Displayed and behaved as expected - looks ready for prod to me!
