### ISSUE TITLE
(3) Needs Assessment & Environmental scan for Tier #2 VRR

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#400]
### Descriptive Summary

Review other DAMS sites, including reviewing work we've done/tickets we've already created while looking at UCSD's site, to find examples of virtual reading rooms.

### Acceptance Criteria

This is what done looks like

* [x] Conduct Needs Assessment (work w/SCA)
* [x] Evaluate UCSD Special Collections VRR front end experience
* [x] Outline desired front end user flow for our next VRR phase

**Comment by JessWaggs** [comment]
User Flow of UCSD VRR Experience: https://drive.google.com/file/d/1x6vTiipH_KFYnOrVfr_rra7zyGyTXEcW/view?usp=sharing

**Comment by JessWaggs** [comment]
Updated "Second Tier" of VRR Request Needs document: https://docs.google.com/document/d/1Y-jevhML30_m8aHEd8joPib5T3r4FL8HkZ2cB1QTg-c/edit
