### ISSUE TITLE
(3) Pre-Ingest Combined Campus History Collections

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#41]
### Descriptive Summary

As an end user, I want to be able to access the campus history collections in the DAMS.

### Objects

* Type of content (images, audio, albums, etc.): images
* Single objects / compound: mostly single; small handful of complex (a few albums; one brochure)
* Special requirements / issues:  All these collections are united in a single Cdm bucket along with UA 50; it would be easier to complete post-publication work on all the collections at once.  For that reason, a separate ticket has been created for the takedown of the combined campus history collections and UA 50 (#120).

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Spreadsheet filename: Combined Campus History sheet is in dams_ingest
* Special requirements / issues: Image grouping, ingest spreadsheet remodel, re-ingest/re-publication in DAMS will be a future project.

### File Assessment / Technical Processing 

* [x] Files assessed for readiness to move
* [x] Files moved to dams_ingest

* Directory name:dams_ingest/Combined_Campus_History
* Special requirements / issues:None

### Pre-Ingest

* [ ] Metadata spreadsheet(s) moved to dams_ingest
* [ ] Ned notified; tickets created for collection ingest, QA work, and publication

### Related Work
Before ingest, the UCSC campus maps metadata will need to be added to the ingest spreadsheet and the files added to DAMS ingest (#190).

**Comment by rmjaffe** [comment]
We've decided not to do any image grouping at this time. Metadata for the campus maps (#190) needs to be added before we ingest this collection.

**Comment by kellyChex** [comment]
@rmjaffe Does this need to be move to the icebox if it's something you want to remember to do in the future?

**Comment by rmjaffe** [comment]
@kellyChex No, it belongs in planning.  It is the next collection we'll ingest following the introduction of the collection-level and collection-of-collections-level metadata and likely after the VRR/CLIR grant work.

**Comment by chesleyperry** [comment]
All files are moved to dams_ingest.

**Comment by rmjaffe** [comment]
I'm going to hold off on moving the metadata spreadsheet until the maps are wrapped up, then I'm going to but the two sheets together.  That said, @chesleyperry, do we want to close out this ticket and note that combining the spreadsheets and moving the metadata to dams_ingest will be done as part of the pre-ingest campus maps ticket #190?

**Comment by chesleyperry** [comment]
@rmjaffe - that sounds like a good plan.  Just to clarify, the photo images for the campus history collection are in dams_ingest/Combined_Campus_History.  I should move the campus maps files into the same directory. You will combine the spreadsheets into one and put that spreadsheet into the dams_ingest/Combined_Campus_History directory too.  Let me know if I got anything wrong.

**Comment by rmjaffe** [comment]
@chesleyperry Yes, you outlined it perfectly.  I'm going to copy your last note into the maps ticket and close this one.  Thanks!
