### ISSUE TITLE
(2) Update representative images for each collection and collection of collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#411]
### Descriptive Summary

Special Collections is working on selecting representative images for each of our collection and collections of collections.  Once their selections have been finalized, we will want to make these updates in the DAMS.  In the future, after work on Add thumbnails and representative images to ingest spec #361 is completed, we can indicate these selections on the ingest spreadsheets.

Consider using the User Story format:

As a collection curator, I would like to be able to select the representative images for each collection in the DAMS.

### Acceptance Criteria

This is what done looks like

* [x] SC&A has produced a list of preferred representative images for each collection and collection of collections (estimated 12/4).  SC&A's DAMS collections representative image choices: https://docs.google.com/document/d/141fZ2udVF-9Nxg3AZTdvoFDwIvu5mXgiPe7d93bak_Y/edit?ts=5fb598df
* [x] DAMS has been updated to reflect SC&A's selections
* [x] Thumbnail images display at an appropriate dpi, and are not pixelated

### Related Work 

Add thumbnails and representative images to ingest spec #361

**Comment by rmjaffe** [comment]
Image selections doc on Drive: https://docs.google.com/document/d/141fZ2udVF-9Nxg3AZTdvoFDwIvu5mXgiPe7d93bak_Y/edit

**Comment by NedHenry** [comment]
I updated the collection thumbnails according to the document provided, and altered the homepage thumbnail display to always use higher-res thumbnails from the image server. This issue should be ready to close, but can be QA-ed first if anyone is interested.
