### ISSUE TITLE
(3) Some dashboard collection pages broken

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#413]
### Descriptive Summary

In the admin dashboard, when and admin views a list of collections and one of the collections in the list is restricted to on-campus access only (e.g. CMF), an error page is displayed.

### Background 

This problem used to be addressed by a patch to Hyrax::CollectionPresenter. However, this patch didn't always load properly and caused intermittent errors in some environments for unknown reasons. The interim solution was to remove the patch. 

### Acceptance Criteria

This is what done looks like

* [x] The admin dashboard collection index and collection show pages work for all collections
* [x] There is no chance of repeating the intermittent failures introduced by my previous patch.

**Comment by rmjaffe** [comment]
This is functionality if back for me -- I'm able to page through the collections in the dashboard's 'all collections' area without issue.

**Comment by chesleyperry** [comment]
Works for me too.  Moving it to done.
