### ISSUE TITLE
Lick Images not Displaying Properly

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#419]
### Descriptive Summary

Some images in the Lick Observatory collection are not displaying properly.  3 images are displaying with the wrong orientation and the others are displaying broken icon images or the generic compound object icon.
The link for the work display page is listed below along with the filename and the issue.  I've checked to make sure the files are correctly named and located on dams_ingest.

https://digitalcollections.library.ucsc.edu/records/xw42nc174
Image displaying sideways | ua0036_pho_0058
ua0036_pho_0058.tif and ua0036_pho_0058a.tif both files on dams_ingest
No filename in metadata. 

https://digitalcollections.library.ucsc.edu/records/tb09j870v
Image displaying sideways | ua0036_pho_0045
ua0036_pho_0045.tif  and ua0036_pho_0045a.tif - Complex object - both files on dams_ingest
No filename in the metadata.

https://digitalcollections.library.ucsc.edu/records/cc08hk192
Image displaying sideways | ua0036_pho_0041
Complex object - both files on dams_ingest (ua0036_pho_0041.tif and ua0036_pho_0041a.tif)
No filename in metadata. 

https://digitalcollections.library.ucsc.edu/concern/works/12579w776
No image displays
ua0036_pho_1284.tif  
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/sb397c685
No image displays
ua0036_pho_0909.tif 
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/cv43p1067?locale=en
No image displays
ua0036_pho_0612.tif 
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/9593tz52p
No image display
ua0036_glp_0953.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/x346d7172
No image displays | ua0036_glp_0785.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/xd07gx096
Generic Compound Object icon displays
ua0036_glp_0662.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/7m01bq08w
Generic Compound Object icon displays
ua0036_glp_0658.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/n009w5347
No image displays
ua0036_glp_0574.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/fj236505m
Generic Compound Object icon displays
ua0036_glp_0541.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/2801pk70d?locale=en
Generic Compound Object icon displays
ua0036_glp_0518.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/gq67jv241?locale=en
Generic Compound Object icon displays
ua0036_glp_0506.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/3j333551z
Generic Compound Object icon displays
ua0036_glp_0480
No filename in metadata, no file on dams_ingest.

https://digitalcollections.library.ucsc.edu/concern/works/dr26z1396
No image displays | ua0036_glp_0411.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/0k225f36k
Generic Compound Object icon displays
ua0036_glp_0278.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/pn89d960f
No image displays
ua0036_glp_0135.tif
on dams_ingest

https://digitalcollections.library.ucsc.edu/concern/works/zs25xc809?locale=en
Side 1 of the compound object doesn't display (with the actual portrait
ua0036_pho_0484.tif
on dams_ingest

### Acceptance Criteria

This is what done looks like

* [x] All images display with the proper orientation

### Related Work 

#390
#56

**Comment by NedHenry** [comment]
I triaged these issues. Except for the three images with rotation issues, all of the problems look like unexpected file ingest issues that aren't part of any particular pattern. It should be straightforward for me to fix these files manually, and then add this type of issue to the post-ingest automatic verification scripts (which I'm working on some this week).

**Comment by afrebert** [comment]
Rotated 
ua0036_pho_0058.tif and ua0036_pho_0058a.tif
ua0036_pho_0045.tif and ua0036_pho_0045a.tif
Image displaying sideways | ua0036_pho_0041
I also checked the first image that doesn't display (ua0036_pho_1284.tif), but it doesn't look like there's anything wrong with the image

**Comment by NedHenry** [comment]
I found and fixed the mysterious issue that was making some of these file ingests fail, and I re-ingested the rotated images. Now I believe that all of these images display correctly except the one that had no filename included in the metadata (ua0036_glp_0480)

The fixed problem was caused by restricted permissions on some of the files in the Fedora repository. I reset the permissions of all files to the correct values, but I'm still not sure how or why some of our files got different permissions than others. My hope is that it has to do with the switch Daniel did in our physical storage hardware. If this recurs, we should dig deeper to find the root cause of the incorrect permissions.

**Comment by chesleyperry** [comment]
@afrebert - I don't see that last missing image in any of the _MOD folders for Lick but there is a copy in the _ORIG folder.  Could you take a look at that image (/diginit2/ua0036_lick_obsv/ua0036_glp/ua0036_glp_ORIG/ua0036_glp_0401-0500/ua0036_glp_0480.tif) and create a modified version?  Then copy it to dams_ingest/ua0036?

**Comment by chesleyperry** [comment]
All images are checked and display correctly now.  One issue:

https://digitalcollections.library.ucsc.edu/concern/works/0k225f36k is the same metadata  as https://digitalcollections.library.ucsc.edu/concern/works/fq977x57q but the first link displays the generic icon in search results and no image on the work display.  Can we just delete the first record (https://digitalcollections.library.ucsc.edu/concern/works/0k225f36k)?

**Comment by afrebert** [comment]
Sure, no problem!
~Angelika
–––––––––––––––––––––––––––––––
Angelika Frebert
Technical Project Manager, Digital Imaging Specialist
Digital Initiatives, UCSC Library
afrebert@ucsc.edu

**Comment by chesleyperry** [comment]
@NedHenry 
It looks like all the problems are fixed except 
https://digitalcollections.library.ucsc.edu/concern/works/3j333551z
ua0036_glp_0480

Angelika has added a new image to dams_ingest - ua0036_glp_0480.tif

Once that image gets ingested, I think this ticket is done.
