### ISSUE TITLE
(1) Collection Description Box Styling Issues

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#420]
### Descriptive Summary

In QAing the Lick and aerials/maps test ingests, we've notes a couple issues with the collection description box:

1. Text overrunning image: When my browser viewport is at a smaller width, the text of the collection description box overruns the image.
2. Metadata source text overlapping with collection guide link: When my browser viewport is at a smaller width, the text of the collection description box overruns the collection guide link.

### Acceptance Criteria

This is what done looks like:

* [x] Text no longer overruns the image at any viewport size
* [x] Text of metadata source notes or collection descriptions does not overlap with the collection guide link.

### Expected Behavior 

Padding between image and text is maintained.
The Padding between the metadata source note/collection description text and the collection guide link is maintained.

### Actual Behavior

![Screen Shot 2020-12-10 at 11 04 32 AM](https://user-images.githubusercontent.com/6412857/101817872-eb00a600-3ad7-11eb-9c8b-0bca1e7941ff.png)
<img width="1350" alt="Screen Shot 2020-12-15 at 6 15 01 PM" src="https://user-images.githubusercontent.com/32003407/102383601-97330880-3f80-11eb-81df-9e63624d181e.png">

### Steps to reproduce 

For both:  I reduced my viewport size to about half the width of my monitor.

**Comment by rmjaffe** [comment]
@JessWaggs Thanks for creating this card!  I noticed this too and failed to remember to ask about it.
