### ISSUE TITLE
Degree symbol appearing as underscore

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#422]
### Descriptive Summary

In the metadata records for the sheets ingested into the staging server as part of the Aerials/Maps Test Ingest #417 where the degree symbol appears within the coordinate data it is not displaying properly.  Instead of the degree symbol (e.g. (W 122°20'00"--W 121°53'28"/N 37°13'45"--N 36°56'10") included in the ingest metadata, it displays as a long underscore, e.g. https://digitalcollections-staging.library.ucsc.edu/records/0c483n452

![Screen Shot 2020-12-15 at 4 52 51 PM](https://user-images.githubusercontent.com/32003407/102290726-7625d580-3ef6-11eb-8fbb-2c42e33d39d5.png)

### Background 

On Slack, Ned noted that this is like an occurrence of the same issue noted in #418 and that "the “long term” fix for that in the ingest just pushed forward, so it didn’t apply to the test ingest I just finished."

### Acceptance Criteria

This is what done looks like:

* [ ] Coordinate values appearing in the aerials/map test sets display as they were entered in ingest metadata, i.e. degree symbol is a degree symbol not an underscore

### Related Work 

This issue is likely related to Lick Work Titles with accented characters not displaying #418

**Comment by NedHenry** [comment]
Fixed!
