### ISSUE TITLE
(1) Create Santa Cruz County History Collection of Collections & c-of-c landing page

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#426]
### Descriptive Summary

We would like to create new collection of collections for the Santa Cruz County History Collections.  Collections to be included in this collection group are:

Santa Cruz County History Photographs (MS 427) -- already ingested
Alexander Lowry (MS 188)
Vester Dick (MS 235)
Chuck and Esther Abbott (MS 39) 

*MS 188, MS 235 & MS 39 will all be ingested on a single spreadsheet.

### Acceptance Criteria

This is what done looks like:

* [x] Santa Cruz County History Collections collection group has been created
* [ ] Landing page for the collection of collections has been created and is visible to users

### Related Work 

Ingest Alexander Lowry (MS 188), Vester Dick (MS 235); Chuck and Esther Abbott (MS 39) #62

**Comment by rmjaffe** [comment]
This should be used as the representative image for the county history collection of collections: http://digitalcollections.ucsc.edu/digital/collection/p265101coll23/id/156/rec/41

**Comment by NedHenry** [comment]
I just set the county history collection's thumbnail to the correct image linked by Rachel above
