### ISSUE TITLE
(-) Shakespeare Santa Cruz landing page broken icon links for images

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#427]
### Descriptive Summary

Shakespeare Santa Cruz Collection landing page displays broken icon links for many images.
See screenshot
![Screen Shot 2021-01-12 at 12 15 10 PM](https://user-images.githubusercontent.com/18403313/104367638-f462a100-54cf-11eb-83a4-25e336774f21.png)

The work pages don't seem to be affected.

### Acceptance Criteria

* [ ] Landing page images display as expected.

### Expected Behavior 

Grid with square thumbnail images and work titles should display

### Actual Behavior

broken icon links with titles.

### Steps to reproduce 

Go to https://digitalcollections.library.ucsc.edu/collections/05741s23v?locale=en

**Comment by NedHenry** [comment]
This seems to have been an ingest issue when these items were ingested. The height of the files was not properly save along with the fileset, so the code to find the dimensions of a square thumbnail was failing. While the original issue was present all along, it did not cause any noticeable problems until the square thumbnails were implemented a few months ago (when we overhauled collection landing pages). 
I fixed the issue. Now all the heights are properly saved, and the square thumbnail code works.
