### ISSUE TITLE
(2) Create Readme or documentation for development set up

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#43]
### Descriptive Summary

As a developer, I can read a readme on Github so that I can build a local instance of the DAMS application

**Comment by NedHenry** [comment]
I think this is going to take a little time, and probably won't be ready before the weekend.

**Comment by NedHenry** [comment]
I wrote an instruction file that explains how I set up my dev environment. However, I wrote this from memory, and it is pretty unlikely it will be easy to follow and work perfectly. 
I see two possible next steps. I could remove the development set entirely from my laptop and try re-installing it from scratch with these instructions, taking detailed notes as I go. Alternatively, Kelly could try installing a dev environment based on these instructions and let me know when there are issues. I'm not sure which is better.
