### ISSUE TITLE
(8) Reach 50% test coverage

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#432]
### Descriptive Summary

Our code is currently at 30% test coverage (meaning our test suite executes 30% of the lines of our code. Errors in the other 70% would not be found in the test coverage). 
We want as much of our code covered as possible. It should be possible to get to at least 50% without too much work. 

### Background 

Our automated tests run whenever we deploy new code. If any of the tests fails, the code is not deployed to the server. We are using coverall.io to automatically monitor test coverage.

### Acceptance Criteria

* [ ] Coveralls shows at least 50% test coverage
* [ ] All tests pass

### Related Work 

#372 - completed
#76

**Comment by afrebert** [comment]
Satisfied with less than 50%
