### ISSUE TITLE
(3) Pre-Ingest Dorothea Lange (MS 20)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#439]
## Collection Information

* Formal collection title: Ruth-Marion Baruch and Pirkle Jones Photographs
* Collection number: MS 20

### Objects

* Type of content (images, audio, albums, etc.): Images
* Single objects / compound: Complex
* Special requirements / issues: N/A

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Spreadsheet filename: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/MS_20_Berryessa_Lange_20201215.xlsx

### File Assessment / Technical Processing 

* [x] Locate modified TIFFs and consolidate in one directory
* [x] Check files against metadata spreadsheet and reconcile discrepancies
* [x] Create Exif spreadsheet
* [x] Evaluate metadata embedded in files
* [x] Evaluate files by spot-checking
* [x] Implement necessary corrections
* [x] Document if files meet FADGI guidelines in ticket and read-me file in folder on diginit2
* [x] Copy files to dams_ingest

* Directory name: dams_ingest/ms0020
* Special requirements / issues:

### Pre-Ingest

* [x] Metadata spreadsheet(s) moved to dams_ingest: //dams.library.ucsc.edu/dams_ingest/ms0020/MS_20_Berryessa_Lange_20210212.xlsx
* [x] Ned notified; tickets created for collection ingest, QA work, and publication

**Comment by rmjaffe** [comment]
@chesleyperry @afrebert Just looked over the metadata for Lange and I think it's good to go.

**Comment by chesleyperry** [comment]
@rmjaffe I just finished the file assessment and had to change the spreadsheet with the correct filename for one file:
ms0020_trn_56-96.tif - changed to ms0020_neg_56-96.tif
I renamed the spreadsheet with today's date and put a copy in the DOMTP pre-ingest folder.  It's good to go from our end.

**Comment by chesleyperry** [comment]
@NedHenry The files and spreadsheet are ready to go for this ingest.  Files are in: //dams.library.ucsc.edu/dams_ingest/ms0020 and the spreadsheet is:
//dams.library.ucsc.edu/dams_ingest/ms0020/MS_20_Berryessa_Lange_20210212.xlsx
