### ISSUE TITLE
Pre-Ingest of Aerial Photos 1928-1948 (Q1)

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/dams_project_mgmt#444]
## Collection Information

* Formal collection title: UC Santa Cruz Aerial Photographs Collection
* Collection number: n/a
* Ingest contains flights:
- 1928-A California Coastline Flight
- 1928-B California Coastline Flight
- 1928-C California Coastline Flight
- 1928-D California Coastline Flight
- 1928-E California Coastline Flight
- 1928-F California Coastline Flight
- 1928-G California Coastline Flight
- 1928-H California Coastline Flight
- 1931-A Santa Cruz County Flight C-1437
- 1931-B Santa Cruz County Flight C-1437
- 1931-C Santa Cruz County Flight C-1437
- 1931-D Santa Cruz County Flight C-1550
- 1935 Santa Cruz County Flight C-3300
- 1937 Santa Cruz County and Monterey County Flight 13-ABG
- 1939-A Santa Cruz County Flight CJA
- 1939-E Santa Clara County Flight CIV
- 1939-F Santa Clara County Flight CIV
- 1940 Santa Cruz County Flight C-6472
- 1940-A Santa Cruz County Flight San Lorenzo River
- 1941 City of Santa Cruz and Vicinity Flight C-7054
- 1943 Santa Cruz County Flight CJA
- 1943-A San Mateo County Flight DDB
- 1948 U.S. Forest Service Flight CDF-5

### Objects

* Type of content: images; digitized aerial photos
* Single objects / compound: complex - flights and sheets
* Special requirements / issues: 

During pre-work done by Metadata Services and Special Collections, some sheets are missing from digitized flights.  Some indexes are also missing digitized sheets.  DI may look into adding digital images or editing sheets to the geo-rectified indexes.

Work has been done to remediate the metadata, add geonames, replace index files with newly created geo-rectified indexes, and reconcile filenames with the metadata.  This card brings those projects together.

Project Board tracking file reconciliation, file quality assessment, and index file replacement: https://github.com/UCSCLibrary/Aerial_Flight_Checking/projects/1

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Spreadsheet filename: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/Aerials_1_1928_1948_20210212.xlsx

### File Assessment / Technical Processing 

* [x] Locate modified TIFFs and consolidate in one directory
* [x] Check files against metadata spreadsheet and reconcile discrepancies
* [x] Create Exif spreadsheet
* [x] Evaluate metadata embedded in files
* [x] Evaluate files by spot-checking
* [x] Implement necessary corrections
* [x] Document if files meet FADGI guidelines in ticket and read-me file in folder on diginit2
* [x] Copy files to dams_ingest

* Directory name: //dams.library.ucsc.edu/dams_ingest/aerials1928-1948/Aerials_1_1928_1948_20210301.xlsx
* Special requirements / issues:

### Pre-Ingest

* [x] Metadata spreadsheet(s) moved to dams_ingest
* [x] Ned notified; tickets created for collection ingest, QA work, and publication

**Comment by rmjaffe** [comment]
@chesleyperry The Q1 spreadsheet is in the Pre-Ingest folder on the DOMTP share.  Filepath is in the ticket desc above.  It's ready to go on my end.

**Comment by rmjaffe** [comment]
@chesleyperry I'm going to pull back the aerials Q1 spreadsheet.  I just noticed an issue with the Geonames.

**Comment by rmjaffe** [comment]
@chesleyperry All cleaned up.  New spreadsheet is in DOMTP: smb://artifacts2.library.ucsc.edu/DOMTP/Pre-ingest/Aerials_1_1928_1948_20210216.xlsx

**Comment by chesleyperry** [comment]
Filechecking completed.
@NedHenry, @rmjaffe, @afrebert: I've moved the spreadsheet into dams_ingest: //dams.library.ucsc.edu/dams_ingest/aerials1928-1948/Aerials_1_1928_1948_20210301.xlsx
I edited it so I'll also put a copy of the latest version on DOMTP and move this ticket to done.
