### ISSUE TITLE
(2) Come up with strategy for light weight grouping 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#45]
### Descriptive Summary

Rachel made a copy of the UA50 metadata and is looking for shared qualities to get a sense of what works can be grouped together for a better student research experience. As there are many files she will work with Teresa in Special Collections and determine a strategy for light weight grouping. For instance, if there are available student hours a student can look at the pioneer class and can say whether groups are likely or not. Rachel then can double check their work.

**Comment by kellyChex** [comment]
@rmjaffe decided to publish UA50 as there's not immediate concern about needing to bundle the images.

**Comment by kellyChex** [comment]
Rachel estimates she will get to this in the Summary after Santa Cruz County History Collection.

**Comment by rmjaffe** [comment]
We've decided to leave UA 50 as is for the foreseeable future; closing this ticket.
