### ISSUE TITLE
(5) Add A-Z sorting to collection landing and other results pages

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#454]
As a user, I want to be able to sort search results and collections alphabetically.

Currently sorts are available for relevance, date uploaded, and date modified. This adds alpha sorting to the list of options.

### Background
This ticket was split off UCSCLibrary/dams_project_mgmt#324 (Add dateCreated sorting to collection landing and other results pages); testing of UCSCLibrary/dams_project_mgmt#324 turned up some bugs with re-indexing and with the current sorting functionality (i.e. how titles are being parsed and sorted) that are needing to be resolved.  Details are documented on UCSCLibrary/dams_project_mgmt#324.

### Acceptance Criteria

- [x] Conduct background research to better determine or understand what is involved in this work.
- [ ] A-Z sort functionality is viewable and usable to end users.

### Related Work

Add a sort property to the metadata config file UCSCLibrary/dams_project_mgmt#366
Add dateCreated sorting to collection landing and other results pages UCSCLibrary/dams_project_mgmt#324 
This ticket is also a prerequisite for UCSCLibrary/dams_project_mgmt#277 and UCSCLibrary/ucsc-library-digital-collections#375

**Comment by snehagunduraoUL** [comment]
Sort by Title has been added and is working on production. This ticket can be closed
<img width="1544" alt="Screen Shot 2021-12-08 at 1 44 13 PM" src="https://user-images.githubusercontent.com/92340457/145289391-aeb22f1c-845e-4ace-8780-9ddadd1d29a7.png">
.

**Comment by rmjaffe** [comment]
@JessWaggs Could you please take a look to confirm that the title sorting is working as expected?  It appears to be doing so on my end.

**Comment by JessWaggs** [comment]
Looks like it works to me!
