### ISSUE TITLE
External controlled vocabularies not loading when editing metadata records

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#462]
### Descriptive Summary

Something seems to be up with Questioning Authority.  I just went into update a [metadata record for an object](https://digitalcollections.library.ucsc.edu/records/q811km536) in MS 427 and wanted to add a control name to the record; however, when I selected LOC or ULAN from the dropdown in the DAMS and searched for "Hihn, F" in either, I received notice that the vocabulary failed to load.  I'm wonder if this is also the cause of the issues noted on [(8) Ingest Lange (MS 20) #440](https://github.com/UCSCLibrary/dams_project_mgmt/issues/440) in which the DAMS failed to use pull in the labels for controlled terms in the Creator property and instead published the URIs.

<img width="691" alt="Screen Shot 2021-06-30 at 9 39 56 AM" src="https://user-images.githubusercontent.com/32003407/124021627-76178f80-d987-11eb-9426-26a85100f18b.png">

Upon further inspection, none of our external vocabularies (LOC/LCNAF, ULAN, AAT, Geonames, etc.) are loading in any of the metadata properties that use values from those sources.

### Steps to Reproduce

1. Select a work in the DAMS

![Screen Shot 2021-11-15 at 1 05 05 PM](https://user-images.githubusercontent.com/32003407/141853814-91ff19a0-d557-4ebe-8c85-87b6721dc6de.png)

2. Click edit to access the metadata workform for the work

![Screen Shot 2021-11-15 at 1 07 13 PM](https://user-images.githubusercontent.com/32003407/141853926-0f7d2596-7234-4f74-b322-a8edea645d8d.png)

3. Go to Subject (People); click the plus sign to add another Subject (People); and using the toggle menu, select 'Loc Names'

![Screen Shot 2021-11-15 at 1 12 22 PM](https://user-images.githubusercontent.com/32003407/141854492-60396988-5032-4d0c-ba61-b3764b8c8f0a.png)

4.  Try entering any name and a pink box will appear that reads 'loading failed.'

![Screen Shot 2021-11-15 at 1 13 05 PM](https://user-images.githubusercontent.com/32003407/141854638-f4324394-0913-483e-b882-3a7b50c38488.png)

This error message presents when entering names that are: 1) Verified to be in the Library of Congress Name Authority File; 2) verified NOT to be in the Library of Congress Name Authority File; 3) present in other metadata records; or 4) NOT present in other metadata records.

### Acceptance Criteria

This is what done looks like:

* [ ] Able to access, select and add terms from controlled vocabularies when editing metadata records

**Comment by snehagunduraoUL** [comment]
@rmjaffe could you please add the steps to reproduce the issue?

**Comment by rmjaffe** [comment]
@snehagunduraoUL Just did.  Realizing now how little detail was on this card; I hope this helps!  Also check out the comment on #440 (https://github.com/UCSCLibrary/dams_project_mgmt/issues/440#issuecomment-867848277).  I strongly suspect that these are related.  I'll work on creating a card for the issue documented in that comment.

**Comment by DiemBTran** [comment]
This passes Notch8 QA. In the following screen recording, I demonstrate:
- external controlled vocabularies load for `Loc Names`
- external controlled vocabularies load for `Getty Ulan`
- searching for a term NOT found in the Library of Congress Name Authority File will display `No matches found`, rather than the bugged `Loading failed`

https://user-images.githubusercontent.com/29311858/144142931-fb15e40b-a48f-47d3-9471-1ec7000933b8.mp4

**Comment by rmjaffe** [comment]
@DiemBTran This looks good to me.  @snehagunduraoUL @rschwab Thoughts?

**Comment by rschwab** [comment]
I don't see the code anywhere yet. Maybe a new pull request is in the works?

**Comment by DiemBTran** [comment]
Upon further review, while the external vocabularies now load when searching in the edit form, it seems like saving `Getty Ulan` terms is bugged.

As seen in this screen recording, after saving a term for `Loc Names` (Seuss, Dr.) and a term for `Getty Ulan` (Geisel, Theodore Seuss (American author and illustrator, 1904-1991)) , the term for `Getty Ulan` does not actually show on the work show page. Going back to the edit form shows that the `Getty Ulan` search has an error: `Unable to fetch label for…`.

https://user-images.githubusercontent.com/29311858/144144648-d9fd70aa-4ad2-4de1-a2e9-25bf3242150d.mp4

**Comment by rmjaffe** [comment]
Thank you for catching this.  Your eye is better than mine!

**Comment by DiemBTran** [comment]
If anything, my apologies for speaking too soon! 😮‍💨

**Comment by rschwab** [comment]
We may not need Ulan as an authority.

**Comment by rmjaffe** [comment]
@rschwab I was wrong.  I was thinking about forthcoming collections, not the ones that are already in the DAMS.  The DeCou collections contains some ULAN URIs, but they are displaying correctly (e.g. https://digitalcollections.library.ucsc.edu/records/kw52jc45j) and I don't expect that we'll be doing any editing/updating of those values.

**Comment by snehagunduraoUL** [comment]
@rmjaffe So can we move this to staging/QA?

**Comment by rmjaffe** [comment]
@snehagunduraoUL @rschwab Before moving this forward:  a couple questions re: ULAN.   

1. If ULAN is not working (i.e. we're not able to connect to the vocabulary so as to add terms manually or via spreadsheet ingest) will that have any impact on the display of the ULAN terms/URIs that are already in the DAMS beyond lack of authority maintenance (labels being refreshed as they are updated by the Getty)?
2. If the LC vocabs are working correctly, should the ULAN related fix be put on another ticket so that this part can move forward?

**Comment by rmjaffe** [comment]
I'm closing this -- I'm able to search and add controlled name headings from LC, ULAN and our local name file in production.
