### ISSUE TITLE
Dibblee Map CONTENTdm Takedown

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#47]
### Descriptive Summary

These maps need to be removed from CONTENTdm and will not be migrating/republished in the DAMS.  Users will be able to access the digitized maps from the catalog records in Alma.  This is not a priority.

### Background 

We are using as similar strategy to provide access to another set of materials, i.e. Frog Peak.

### Acceptance Criteria

This is what done looks like:

* [ ] Image files relocated to the web server that is hosting the Frog Peak stuff
* [ ] Spreadsheet created with map title, call number, and new URIs
* [ ] Metadata in CONTENTdm exported and stored
* [ ] Metadata Services notified
* [ ] Links in Alma records updated
* [ ] Dibblee Map collection removed from CONTENTdm

**Comment by kellyChex** [comment]
Sue needs to connect with Daniel about moving the image files. As well as document the new URIs in a spreadsheet, hand that off to meta data services, and update the catalog records. Currently links pointing at CONTENTdm and instead it needs to point to the web server.
