### ISSUE TITLE
Pre-Ingest Ansel Adams (MS 2)

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#48]
## Collection Information

* Formal collection title: Ansel Adams Photographs
* Collection number: MS 2

### Objects

* Type of content (images, audio, albums, etc.): Images
* Single objects / compound: Single

### Metadata Preparation

* [x] Object-level metadata created / remediated
* [x] Object-level metadata formatted per ingest spreadsheet specification
* [x] Spreadsheet available on DOMTP
* [x] DI notified

* Special requirements / issues:

### File Assessment / Technical Processing 

* [x] Files assessed for readiness to move
* [x] Files moved to dams_ingest

* Directory name:
* Special requirements / issues:

### Pre-Ingest

* [x] Metadata spreadsheet(s) moved to dams_ingest
* [x] Ned notified

### Related Work

#284 Ingest of Adams
#289 Post-Ingest Adams

**Comment by crisr15** [comment]
Ingest alone was pointed at 3.
