### ISSUE TITLE
Not able to search on the word 'test'

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#490]
### Descriptive Summary

Not able to successfully search for the word 'test' using the search box on the DAMS homepage.  When entering 'test' the site redirects to an error message.  When entering other words that are a known not to appear in any of the metadata, e.g. 'ufo', the site redirects to a blank results/failed search page which gives users the option to try searching for something else.

### Background 

I'm guessing that the reason for the error message is because any results might include non-public facing test works and collections we have in the DAMS (titled 'test')?  That said, I expect that there are non-test works whose metadata might contain the word test.

### Acceptance Criteria

This is what done looks like:

* [ ] User searches on the word 'test' and either results appear or they are redirected to the failed search page

### Expected Behavior 

DAMS redirects to an error message.

### Actual Behavior

DAMS redirects to the failed search page.

### Steps to reproduce 

1. Enter the word 'test' in the search box on the DAMS homepage
![Screen Shot 2021-12-07 at 2 02 58 PM](https://user-images.githubusercontent.com/32003407/145115257-5530f9ad-cbb4-4669-87de-2e3dbfc04a83.png)

2. Press enter
![Screen Shot 2021-12-07 at 2 03 05 PM](https://user-images.githubusercontent.com/32003407/145115279-b3a89c76-bb27-4e03-ada0-1210e3d155ee.png)

For comparison:  

1. Enter the abbreviation 'ufo' in the search box on the DAMS homepage
![Screen Shot 2021-12-07 at 2 10 24 PM](https://user-images.githubusercontent.com/32003407/145115374-7896b8c6-d3f2-47ec-b7cb-757f9abce2d1.png)

2. Press enter
![Screen Shot 2021-12-07 at 2 10 33 PM](https://user-images.githubusercontent.com/32003407/145115404-ab5b7aab-134c-4209-98fb-f095f931b4a9.png)

**Comment by snehagunduraoUL** [comment]
This is working fine on staging. Should be fixed when we deploy from staging to prod.

**Comment by rmjaffe** [comment]
Seems to be working fine.
