### ISSUE TITLE
Update masterFilename to primaryFilename

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#491]
### Descriptive Summary

Rename masterFilename metadata property primaryFilename.

### Background 

(https://www.nytimes.com/2021/04/13/technology/racist-computer-engineering-terms-ietf.html)

### Acceptance Criteria

This is what done looks like:

* [ ] Ideally, this metadata property would be renamed on every level 
* [ ] Or, for expediency, the public labeling for this property is updated to Primary Filename
* [ ] Property displays for all works that have this property.

**Comment by snehagunduraoUL** [comment]
I have a Merge Request ready for this one. Let me know if you want it to be merged now or wait for bulkrax.

**Comment by rmjaffe** [comment]
@bkiahstroud Do you have an opinion on this?

**Comment by bkiahstroud** [comment]
Merging now shouldn't be a problem as far as Bulkrax is concerned. I can update the mapping for it

**Comment by rmjaffe** [comment]
Cool, thank you.  @snehagunduraoUL, go for it!

**Comment by snehagunduraoUL** [comment]
Thanks Kiah and Rachel!
@rschwab could you please review it?

**Comment by snehagunduraoUL** [comment]
This is working on sandbox.
<img width="1235" alt="Screen Shot 2022-02-22 at 3 12 04 PM" src="https://user-images.githubusercontent.com/92340457/155235341-285c9ccb-62de-4db7-9787-b992e89f2dea.png">

**Comment by rschwab** [comment]
Property does not display on front-end for at least some works. This could be due to the work being ingested with the old property name.

**Comment by rmjaffe** [comment]
As noted in the comments on Duplication of metadata fields: "Master Filename" and "Master File Name" UCSCLibrary/ucsc-library-digital-collections#417, neither a field labeled Master Filename or Primary Filename is displaying on the records in production.  Apart from that related bug, I'm assuming this ticket is close? @rschwab @snehagunduraoUL
