### ISSUE TITLE
Evaluate if the Bulkrax exporter is ready to be used for the production db backup

### ISSUE THREAD

**Issue by crisr15** [UCSCLibrary/dams_project_mgmt#497]
Verify / fix the following: 

- [x] Controlled fields export URIs (as opposed to labels) 
- [x] All mapped fields get exported (using [this spreadsheet](https://docs.google.com/spreadsheets/d/1q2xrxULg6whSHYxXeirz7KnghEb_xCMPvW6x_wdo9aU/edit#gid=1359124498)) 
- [x] Works get exported 
- [x] Collections get exported 
- [x] FileSets get exported

**Comment by bkiahstroud** [comment]
Regarding "All mapped fields get exported (using [this spreadsheet](https://docs.google.com/spreadsheets/d/1q2xrxULg6whSHYxXeirz7KnghEb_xCMPvW6x_wdo9aU/edit#gid=1359124498))" -- 

All properties specified in column F ("Property Label") are mapped in `config/initializers/bulkrax.rb` as of Feb. 14 2022. 

**NOTE:** the property `primaryFilename` currently exists in the application as `masterFilename`, but the switch to the new property name has not happened yet, so the `masterFilename` mapping is still being used
