### ISSUE TITLE
[2] RightsStatement field is not required and not inherited if empty

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#499]
**Summary**
As an admin user, I want to be able to ingest works without a RightsStatement URI. Some works are intentionally left without this field, and so empty values should be allowed and not automatically inherit a default value from the importer.

**Acceptance Criteria**
- [x] Works can be imported a blank RightsStatement field
- [x] Spreadsheets can be imported without a RightsStatement column
- [x] When RightsStatement is not declared on an import, it goes into the repository with an empty value and is not inherited from the importer default, the collection, or a parent work.
- [x] When records with blank rightsStatements are exported, they are not assigned a rightsStatement

**Comment by bkiahstroud** [comment]
> We decided that our usage of rightsStatement and rightsStatus would be switched:  the [rightsStatements.org](http://rightsstatements.org/) values will now go in rightsStatement, and the descriptive text will go in rightsStatus. 
>
> \- Rachel ([Slack](https://notch8.slack.com/archives/CNUNTSCBH/p1646340644896099?thread_ts=1646340229.552699&cid=CNUNTSCBH))
