### ISSUE TITLE
Parent-child relationships are not getting exported

### ISSUE THREAD

**Issue by bkiahstroud** [UCSCLibrary/dams_project_mgmt#501]
Mirror ticket in Bulkrax: https://github.com/samvera-labs/bulkrax/issues/424 

# Testing Instructions 

1. Login as an admin 
2. Navigate to Dashboard > Importers > New 
3. Fill out required fields and upload a CSV that fulfills the Acceptance Criteria 
5. Click "Create and Import" 
6. Navigate to the importer's show page. After a couple minutes, refresh the page and ensure the entries succeeded 
7. Navigate to Dashboard > Exporters > New 
8. Select "Export From" > "Importer". Select the importer under "Importer". Fill out required fields. Click "Create and Export" 
9. After a couple minutes, refresh the page and click the download icon next to the exporter 
10. Open the downloaded CSV. Verify that all relationships successfully get exported in the "parent" column 

# Acceptance Criteria 

The application-generated IDs of the following relationship types get exported in the "parent" column: 

- [ ] Collection in Collection 
- [ ] Work in Collection 
- [ ] Work in Work 
- [ ] FileSet in Work

**Comment by rschwab** [comment]
Does this work include: automatically export parent collection ID's to the parent column for children of collections?

**Comment by bkiahstroud** [comment]
> Does this work include: automatically export parent collection ID's to the parent column for children of collections?

@rschwab Yes it does
