### ISSUE TITLE
Bulkrax - If a Collection entry fails during Import, it halts the processing of all following Collection entries

### ISSUE THREAD

**Issue by bkiahstroud** [UCSCLibrary/dams_project_mgmt#502]
# Testing Instructions 

1. Login as an admin 
2. Navigate to Dashboard > Importers > New 
3. Upload a CSV that has at least two Collections. The first Collection should be invalid, and the second should be valid (see example below) 
4. Click "Create and Import" 
5. Give the importer a couple minutes to process. Then click into the importer's show page 
6. Verify that: 
  a. Both Collection entries were created and processed 
  b. The valid Collection was created successfully 

Example CSV: 

| workType | title | description |
| --- | --- | --- |
| Collection | | Invalid (missing title) |
| Collection | Valid Collection | Lorem ipsum |

# Acceptance Criteria 

- [ ] Failed Collection entries do not prevent subsequent Collection entries from processing

**Comment by snehagunduraoUL** [comment]
This is working as expected. Thanks Kiah.

<img width="1001" alt="Screen Shot 2022-03-03 at 10 01 49 AM" src="https://user-images.githubusercontent.com/92340457/156624396-b6721a4f-9c61-4e54-b8e9-c33eff03c1aa.png">
