### ISSUE TITLE
Bulkrax Metadata Ingest Specification document

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/dams_project_mgmt#506]
Current version of the document
https://docs.google.com/document/d/1qblKPY6-9tX6q2BSskoiJ3-sl7jT19Qx/edit#

**Comment by rschwab** [comment]
Define bulkrax specific terms like ‘importer’
Step-by-step instructions would be helpful
Examples/use cases (especially for round tripping) would be helpful
Sample ingest spreadsheet that conforms to Bulkrax ingest specifications
Sample export spreadsheet
Explanation of common error types or error messages would be helpful
