### ISSUE TITLE
Export multi-valued fields into single columns

### ISSUE THREAD

**Issue by bkiahstroud** [UCSCLibrary/dams_project_mgmt#512]
# Summary 

Multi-valued fields should be exported into single columns instead of split into numerated ones 

**Before:**

| title_1 | title_2 |
| --- | --- |
| First Title | Second Title |

**After:**

| title |
| --- |
| First Title; Second Title |

# Testing Instructions 

1. Login as an admin 
2. Navigate to Dashboard > Importers > New 
3. Fill out required fields. Upload a CSV that has multiple values for all properties that accept multiple values  
5. Click "Create and Import" 
6. Navigate to the importer's show page. After a couple minutes, refresh the page and ensure the entries succeeded 
7. Navigate to Dashboard > Exporters > New 
8. Select "Export From" > "Importer". Select the importer under "Importer". Fill out required fields. Click "Create and Export" 
9. After a couple minutes, refresh the page and click the download icon next to the exporter 
10. Open the downloaded CSV. Verify that the exported CSV satisfies the Acceptance Criteria 

# Acceptance Criteria 

- [ ] All properties that accept multiple values should export their values in a single column 
- [ ] Multiple values are joined by the pipe (`|`) character (requires https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/267)

**Comment by snehagunduraoUL** [comment]
<img width="165" alt="Screen Shot 2022-05-13 at 1 17 34 PM" src="https://user-images.githubusercontent.com/92340457/168383429-ee28b4d0-9544-412d-a4ae-e4c500e43ddc.png">

This works as expected. This ticket can be closed.
