### ISSUE TITLE
Fix RecordNotUnique error when minting local authorities

### ISSUE THREAD

**Issue by bkiahstroud** [UCSCLibrary/dams_project_mgmt#513]
# Summary 

Prevents this error from happening on Bulkrax entries when creating local authority entries: 

![Show Entry Digital Collections Online 2022-03-28 at 5 42 58 PM](https://user-images.githubusercontent.com/32469930/160510175-16d76173-d5be-417e-a4d1-15783484d913.jpg)

# Testing Instructions 

1. Login as an admin 
2. Navigate to Dashboard > Importers > New 
3. Fill out the required fields. Upload a CSV that has the same value in multiple controlled fields (refer to example below) 
4. Click "Create and Import" 
5. Navigate to the importer's show page. After a couple minutes, refresh the page 
6. Verify that no records threw an `ActiveRecord::RecordNotUnique` error 

### Example CSV (partial)

| subjectName | subjectTitle | subjectTopic |
| --- | --- | --- |
| ScoobySnacks | ScoobySnacks | ScoobySnacks |

**Comment by snehagunduraoUL** [comment]
<img width="1042" alt="Screen Shot 2022-05-13 at 12 45 10 PM" src="https://user-images.githubusercontent.com/92340457/168379094-4be42b07-1a2c-4bb3-9fde-64bcf6c456a9.png">

Importer succeeded with the above csv. This ticket can be closed.
