### ISSUE TITLE
Document env changes on sandbox and staging

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/dams_project_mgmt#516]
There were a few environment changes on sandbox and staging servers. We need that documented to help production deploy and reduce deploy downtime.

**Comment by rschwab** [comment]
[Software updates on Sandbox and Staging](https://docs.google.com/document/d/1lRmIZRIBX7yrj0co07HAgzPBNbY29Oot6t_ABZfEEVQ/edit)
