### ISSUE TITLE
[5] Local authority should mint on exact match only

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#519]
Currently local authority minting and linking is using phrase matching, or fuzzy matching, or some other method. It should use exact match only. When an exact match _(case-insensitive, remove white space and special characters)_ is not found it should mint a new local term. If the ingested value is a URI it should not create a new authority term, even if the lookup fails, in other words it should not create a local term that is a URI string.

Examples: 
- [This work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/h702q641c?locale=en) was ingested with a subjectTitle value of "California", which erroneously became "San Francisco-Oakland Bay Bridge (Oakland and San Francisco, Calif.)".
- [This work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/8k71nh141?locale=en) was ingested with a deprecated term for Genre, and it erroneously used the URI as the term.

**Comment by bkiahstroud** [comment]
>[This work](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/8k71nh141?locale=en) was ingested with a deprecated term for Genre, and it erroneously used the URI as the term.

@rschwab is this something that was handled by BulkOps? If so, how? I'm not seeing any data in the search results that could be used to determine whether a term is deprecated or not

**Comment by rschwab** [comment]
I don't know if BulkOps handled it. I only discovered its deprecated by clicking the URL, so I'm not sure if there's something returned from LC or Getty when a term is deprecated.

**Comment by rschwab** [comment]
Yay matching is working... exactly.

Genre is still broken when importing a deprecated term, but I can appreciate that is perhaps out of scope here. I'll move this to deploy, and have noted this issue in our documentation with the workaround of using an updated term and round-tripping.

Thanks Kiah!
