### ISSUE TITLE
[5] Deleting values using Bulkrax on import isn’t working

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#521]
### Descriptive Summary

As an admin user, I want to be able to use Bulkrax to delete values from fields.

### Acceptance Criteria

This is what done looks like

* [x] Importing with a blank value using numerated column headers for multi valued fields removes the value from the work.
* [x] Other values are left in-tact on multi-valued fields
* [x] Document functionality in Bulkrax Wiki 

### Expected Behavior 

When using numerated columns in an import, if the cell is blank the value should be deleted.

**Comment by bkiahstroud** [comment]
@rschwab the acceptance criteria includes criteria for single valued fields, but I'm not actually seeing any single valued fields in the metadata schema. Do you have any recommendations for testing this?

**Comment by rschwab** [comment]
Wow you're right. Publisher was single valued but that's been commented out. I guess we'll skip this requirement for now, since there's no great way to test it.

**Comment by bkiahstroud** [comment]
Documentation for this has been added to the Bulkrax Wiki: [link](https://github.com/samvera-labs/bulkrax/wiki/Interacting-with-Metadata)

**Comment by bkiahstroud** [comment]
@rschwab All my testing with this revealed no bugs, so I've gone ahead and pushed this back to Sandbox QA. Using the [new documentation in the Bulkrax Wiki](https://github.com/samvera-labs/bulkrax/wiki/Interacting-with-Metadata), can you test this when you get the chance?

**Comment by rschwab** [comment]
I just tested and this is still an issue. Imported using numerated columns with one value for genre deleted (see screenshot). After running this import, the two values are still present on the work, and present in the exporter created from the importer.

![delete-bug](https://user-images.githubusercontent.com/515412/165826535-335b8f6b-66b1-4463-91eb-a171c5448676.png)

**Comment by snehagunduraoUL** [comment]
This works on sandbox now.
Test data attached.
[test_521.csv](https://github.com/UCSCLibrary/dams_project_mgmt/files/8657331/test_521.csv)
Removed the value for genre_1 and the metadata on the importer has been updated successfully (the value is deleted).
Exported csv also does not have the deleted value.
importer : http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/120?locale=en
exporter : http://digitalcollections-staging-sandbox.library.ucsc.edu/exporters/8?locale=en
@rschwab We can close this if the above QA desc makes sense to you. Thanks.

**Comment by bkiahstroud** [comment]
> I just tested and this is still an issue. Imported using numerated columns with one value for genre deleted (see screenshot). After running this import, the two values are still present on the work, and present in the exporter created from the importer.
> 
> ![delete-bug](https://user-images.githubusercontent.com/515412/165826535-335b8f6b-66b1-4463-91eb-a171c5448676.png)

This ended up being an issue with controlled fields specifically due to special behavior coming from ScoobySnacks. With the changes from [this PR](https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/286), all controlled fields should now behave the same when importing/exporting as other non-controlled fields
