### ISSUE TITLE
[5] RightsStatement doesn't import/export

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#524]
### Descriptive Summary

As an admin user, I want to be able to import rights statements using Bulkrax. Currently these don't appear to be imported when defined on an import spreadsheet.

### Acceptance Criteria

This is what done looks like

* [x] Rights statement can be imported without error.
* [x] Rights statement can be exported without error.

**Comment by bkiahstroud** [comment]
Related PR: https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/280

**Comment by snehagunduraoUL** [comment]
Rights statement is being imported.
<img width="541" alt="Screen Shot 2022-05-10 at 9 59 55 AM" src="https://user-images.githubusercontent.com/92340457/167682976-a5a256e7-53b6-4f0e-95cf-79ae8ae7d74a.png">
Rights statement is being exported too.
<img width="882" alt="Screen Shot 2022-05-10 at 10 04 39 AM" src="https://user-images.githubusercontent.com/92340457/167683693-7e1dcc11-6982-4383-b654-3a21b149ce43.png">

@rschwab we can close this ticket.
