### ISSUE TITLE
404 error on catalog page for admin users

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/dams_project_mgmt#531]
The admin users are facing a 404 error when trying to access the [catalog](https://digitalcollections.library.ucsc.edu/catalog) page.
Steps to reproduce:
1. Enter the url https://digitalcollections.library.ucsc.edu/catalog
2. Login with admin credentials
3. Reload the page.

**Comment by rmjaffe** [comment]
@snehagunduraoUL Just tried to reproduce this.  I'm not getting an error, rather when I'm on the catalog page and then login, after submitting my credentials I'm redirected to the Dashboard.
