### ISSUE TITLE
[3] Exporter created from importer didn't match works on importer

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#533]
I created an importer (importer X) with a single work on it for testing. Then created an exporter based on it. 

That single work had originally been imported with many other works some weeks prior (importer Y). 

The exporter included extra works - it seemed to be pulling all the works from importer Y, rather than importer X.

[Exporter](http://digitalcollections-staging-sandbox.library.ucsc.edu/exporters/6?locale=en)
[Importer X (one work)](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/116?locale=en)
[Importer Y (many works)](http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/79?locale=en)

**Comment by rschwab** [comment]
Here's an exporter with a large, unexpected list of works+collections: http://digitalcollections-staging-sandbox.library.ucsc.edu/exporters/7?locale=en

**Comment by rschwab** [comment]
One concern that's been raised that may be related is the order of objects on the export list. When an export is created from an importer, is it possible to export using the same order as found on the ingest spreadsheet?

**Comment by bkiahstroud** [comment]
> One concern that's been raised that may be related is the order of objects on the export list. When an export is created from an importer, is it possible to export using the same order as found on the ingest spreadsheet?

Not currently, no. On export, [objects are grouped together by type](https://github.com/samvera-labs/bulkrax/blob/main/app/parsers/bulkrax/csv_parser.rb#L202) (Works first, Collections second, and FileSets third)

**Comment by rschwab** [comment]
This appears to have been resolved. Thank you!
