### ISSUE TITLE
Importer creation page has incorrect help statement

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#534]
When creating a new importer, under the **Add Files to Import** section the help text reads "Choose files to upload. The filenames must be unique, and the filenames must be referenced in a column called '**file**' in the accompanying CSV file." But it seems the column needs to be '**filename**'.
![Firefox_Screenshot_2022-04-29T22-12-03 845Z](https://user-images.githubusercontent.com/515412/166075598-25f97509-fe06-428f-9f01-32604502d738.png)

**Comment by rschwab** [comment]
Or does it work with either column name?

**Comment by bkiahstroud** [comment]
> Or does it work with either column name?

@rschwab it works with either column name ([link to code](https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/sandbox/config/initializers/bulkrax.rb#L41))
