### ISSUE TITLE
ActiveJob::SerializationError

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/dams_project_mgmt#542]
Error message: ActiveJob::SerializationError - Only string and symbol hash keys may be serialized as job arguments, but 0 is a Integer

Editing an existing bulkrax import with a new spreadsheet produced this error.

Importer: http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/139?locale=en#work-entries
Sheet used for the import: https://docs.google.com/spreadsheets/d/1Nb_yfwjSxDFRwIlVKlFLb5noA-8slAqPjG3HbdNBQ2c/edit#gid=0

**Comment by bkiahstroud** [comment]
@rschwab I'm having trouble reproducing this locally. Is this something that happens consistently? If so, can you add details of how to reproduce the error?

**Comment by rschwab** [comment]
Interesting, it seems to work on staging now as well. I should have grabbed the error log when I saw it. I'll close this for now and  keep an eye out for this error in case I can grab a log.

**Comment by rschwab** [comment]
Another example:
When importing with bulkrax using cloud file attachments from the server, works throw this error.

Example importer: http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/180

Copy of the importer spreadsheet: https://docs.google.com/spreadsheets/d/11k4hAg7PXiyrJ2KKQB2SUqMjjdHJxthv1AI2VE0QbPw/edit#gid=0

**Comment by bkiahstroud** [comment]
This error occurs when importing a work using Bulkrax that meets the following criteria: 

- Imports at least one controlled field 
- Has a filename in the `filename` column

**Comment by rschwab** [comment]
Thank you, Kiah!
