### ISSUE TITLE
Work showpage errors out for works with filesets

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/dams_project_mgmt#555]
Steps to recreate:
1. Create an importer with filesets. I used this
workType,bulkrax_identifier,parent,access_rights,title,filename
Work,i0,,public,title_of_parentwork1
Fileset,j0,i0,,child__work1,sample.tif

2. Create and Import
3.  When the import is complete, click on the work which takes you to work showpage.

**Comment by bkiahstroud** [comment]
@snehagunduraoUL so far I haven't been able to reproduce this locally. Did you 1) upload a CSV and select the `sample.tif` using the Cloud Files button, or 2) upload a zip with the CSV and the TIF? 

Also, could you please include the logs from the error on the sandbox server? That would help a ton

**Comment by rschwab** [comment]
Potentially related to #540
