### ISSUE TITLE
(5) Ingest MS38 DeCou Collection 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#57]
### Descriptive Summary

Large collection of simple image objects.

### Background 

This is a legacy collection currently up in CONTENTdm.

### Acceptance Criteria

This is what done looks like:

* [x] Collection has been successfully ingested
* [x] Images display properly
* [x] Metadata displays properly

### Related Work 

DeCou pre-ingest card #158.

**Comment by chesleyperry** [comment]
**QA:**

Only issue of note is that the collection landing page needs a representative image.  Should be ready to publish after that is added.

### Details

- All images briefly checked in authenticated[ list display](https://digitalcollections.library.ucsc.edu/dashboard/works?f%5Bmember_of_collections_ssim%5D%5B%5D=Branson+DeCou+Archive&locale=en&page=32&per_page=100) for broken image links and orientation problems.  **No Issues!**

### Thorough work display checks - Checked 5 images from each series (Cuba, Ireland, Russia, Italy, U.S. Germany)

- Links on work display page: accurate links and functionality. **No issues!**
- Metadata matches: descriptive records match image. **No issues!**
- Metadata labels: accurate and in English. **No issues!**
- Download, share and embed links function in work display.  **No issues.**

### Landing Page:
- Images display correctly in grid - **no issues**
- Collection Description and representative image - **no main rep image listed.**

### Facet display (browse) Page:

- Accurate display and linking. **No issues!**

### Image Viewer:

- Zoom, full screen, share and embed links function.  **No issues.**


@rmjaffe : I'm not sure if this is an issue or just something to note.  There are two series title listed:
Dream Pictures and Travelogues, Branson DeCou
American Travelogues, Branson DeCou
![Screen Shot 2021-01-06 at 10 18 33 AM](https://user-images.githubusercontent.com/18403313/103805580-a1d54080-5008-11eb-81cb-59e5c4929e13.png)

**Comment by rmjaffe** [comment]
@chesleyperry This falls in the 'something to note' category.  Series/sub-series, especially in connection with the facets, is something that has been on my mental back-burner as topic for future discussion.  In the case of DeCou, it would probably be better for the sub-series values (Cuba, California, etc.) to be used in place of the series values for the 'series' facet.

As far as the representative image, one has been selected for DeCou:  dc1_750_0246.tif

All the representative images chosen by SC&A are on the following list attached to Update representative images for each collection and collection of collections #411 (which I'd like to bring into the next sprint): https://docs.google.com/document/d/141fZ2udVF-9Nxg3AZTdvoFDwIvu5mXgiPe7d93bak_Y/edit?ts=5fb598df

Currently only links to the selected images are given on that list.  I've asked Luisa to have one of the students supply the filenames.
