### ISSUE TITLE
(5) Ingest MS 312 Kofsky Collection 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#59]
### Descriptive Summary

Small collection of simple images.

### Background 

This is a legacy collection currently up in CONTENTdm.

### Acceptance Criteria

This is what done looks like:

* [x] Collection has been successfully ingested
* [x] Images display properly
* [x] Metadata displays properly

### Related Work 

Kofsky Images pre-/post-ingest card #201.

**Comment by rmjaffe** [comment]
@afrebert I pulled this card out of the current sprint following the DAMS stakeholders meeting.

**Comment by rmjaffe** [comment]
QA: Looked at Kofsky.  Images and metadata are all accounted for.  Everything looks good to save for the lack of info in the collection description box on the collection landing page:  collection description, link to the finding aid in OAC, and thumbnail. I overlooked this.  When we're all back, I'll follow up with SC&A and plug that stuff into the metadata.

**Comment by rmjaffe** [comment]
Update:  Collection description has been added.  @chesleyperry Did you want to do any additional QA?  I paged through the entire collection and opened up many of the item pages.  Did you want to do any additional QA before we publish?

**Comment by chesleyperry** [comment]
Checked all images for orientation and display issues - no problems.
Checked all links and facets for display or linking issues - no problems.
This is ready to publish and add to the home page.
