### ISSUE TITLE
Revisit/take stock of collection priorities and collection readiness

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#6]
Confirm this is the content to take stock of: 

Other Minds/Cabrillo Music Festival recordings

- Pilot collection (almost ready for ingest)
- New collection

### Descriptive Summary

A short description of the feature, including wireframes, screenshots, or videos if available

### Background

What problem is this feature going to solve? 

### Relationships

Are there any other issues or merge requests that are related to this feature (use # to generate a quick link). In particular, is this part of a larger epic, or does it depend on any other tickets being resolved first? 

### Acceptance Criteria

This is what done looks like

* [ ] I see these views
* [ ] When a user does this, that happens

### Implementation Tasks

It should:

* [ ] Do
* [ ] These
* [ ] Things

### Further information

Edit in any later issues or merge requests that are connected to this issue, for future reference

**Comment by kellyChex** [comment]
Sue and Rachel to have a conversation about the spreadsheet Rachel shared.

**Comment by rmjaffe** [comment]
Closing this ticket -- @chesleyperry and I have talked about this, and SC&A has weighed in.
