### ISSUE TITLE
Ingest MS 39 Chuck & Ester Abbott Collection 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#61]
### Descriptive Summary

Small collection of simple images.

### Background 

This is a legacy collection currently up in CONTENTdm.

### Acceptance Criteria

This is what done looks like:

* [ ] Collection has been successfully ingested
* [ ] Images display properly
* [ ] Metadata displays properly

### Related Work 

Pre-/post-ingest card #61.

**Comment by rmjaffe** [comment]
Combined into a single ingest #62.
