### ISSUE TITLE
(5) Ingest Alexander Lowry (MS 188), Vester Dick (MS 235); Chuck and Esther Abbott (MS 39)

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#62]
### Descriptive Summary

Small collection simple images.

### Background 

These are legacy collections currently up in CONTENTdm.

### Acceptance Criteria

This is what done looks like:

* [x] Collection has been successfully ingested
* [x] Images display properly
* [x] Metadata displays properly
* [ ] Collection has been published and is available to users on DAMS homepage
* [ ] Santa Cruz County History Collections Collection of Collections Page created, includes the previously ingested "Santa Cruz County Historic Photograph Collection"

### Related Work 

Pre-ingest card #204

**Comment by chesleyperry** [comment]
Collections all ingested and look great.

On the pre-ingest ticket, Rachell noted the representative image for the county history collection of collections: https://digitalcollections.library.ucsc.edu/concern/works/1r66j483b

**Comment by rmjaffe** [comment]
Metadata looks great and it looks like the Lowry photos were mapped correctly to their respective grandparent collections, i.e. campus collections and county history collections.
