### ISSUE TITLE
Ingest Dorothea Lange (MS 20)

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#67]
### Descriptive Summary

Collection of simple images.

### Background 

This is a new collection.

### Acceptance Criteria

This is what done looks like:

* [ ] Collection has been successfully ingested
* [ ] Images display properly
* [ ] Metadata displays properly

### Related Work 

Lange pre-/post-ingest card #68.

**Comment by rmjaffe** [comment]
Duplicative card.
