### ISSUE TITLE
(2) Determine metadata to display on frontend 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#8]
### Descriptive Summary:

Need to determine if the right Work metadata is showing above the Show More section

What metadata is hidden that we need to reveal 

Reference Data Dictionary to see all metadata fields 

Try to create a standard list of what metadata fields to display vs per collection 

![Screen Shot 2019-10-09 at 8 14 58 AM](https://user-images.githubusercontent.com/9621070/66494675-e7edce00-ea6c-11e9-800a-b9b952166daf.png)

**Comment by JessWaggs** [comment]
Described some next steps for verifying we are complying with the data dictionary designations: https://docs.google.com/document/d/1ZJcuYAmck7fPsSN2XfOhF18guJ2Eiqt0Vlc9voaPyHI/edit?usp=sharing

**Comment by kellyChex** [comment]
@JessWaggs Where is the Data Dictionary?

**Comment by JessWaggs** [comment]
This is the current [Data Dictionary](https://docs.google.com/spreadsheets/d/1q2xrxULg6whSHYxXeirz7KnghEb_xCMPvW6x_wdo9aU/edit#gid=1359124498)

The "Public Display Setting in Hyrax" indicates whether a field should be "Brief" (shown above Show More), "See More" (revealed after Show More is clicked), "Staff View" (hidden in public display, but shown to logged in admin users)

The only potential issue with capturing this info in the Data Dictionary is that it does not include system metadata, like the ones I recommend we hide in that next steps doc.

**Comment by NedHenry** [comment]
Here is the configuration file that determines pretty much everything about our metadata schema in Hyrax, including the metadata display. I haven't made sure that the configuration file matches the data dictionary recently, and there may be discrepancies. If there are other hyrax-generated fields that are also getting displayed, we can easily hide them (but it'd be super helpful for me if you point them out specifically if that's the request).
https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/config/metadata.yml

**Comment by JessWaggs** [comment]
@NedHenry I'm actually a little confused about the collection name. 
In [this example](http://digitalcollections.library.ucsc.edu/concern/works/zw12z5442?locale=en), is the "In Collection: Harry Mayo Surfing Photography Collection" the display of the Collection property as described in the Data Dictionary?

**Comment by JessWaggs** [comment]
@NedHenry I don't see the "In Administrative Set" field in the page you listed. Is it safe to assume that is only displayed to Admin/Authenticated users? (as I don't see it in the public display)

**Comment by JessWaggs** [comment]
@kellyChex I outline some recommended next steps for this in the Google Doc I created.
Is there a better place to capture these potential next steps/needs?

**Comment by JessWaggs** [comment]
Update from 10/24 mtg: Ned clarified this was structural metadata.
The Collection is pulled from ingest spreadsheet collection property.
In Admin Set is only shown to admin/authenticated users.
Would be good to think about where to document the display of structural metadata.

**Comment by NedHenry** [comment]
Summarizing what we said on the call today: membership in collections and admin sets (as well as membership in other works) is structural metadata instead of descriptive metadata. These fields are handled differently by Hyrax, and are displayed separately in the system. Our data dictionary and metadata configuration file do not fully reflect the ways that structural metadata is indexed and displayed.

**Comment by kellyChex** [comment]
Created #95 as per discussion with @JessWaggs
