### ISSUE TITLE
(1) Ingest UA133 Porter College Collection on Production 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#80]
### Descriptive Summary

Porter College is currently ingested on staging and production. We need to do QA to determine what if any corrections need to be made. 

# Acceptance Criteria 
1. QA for Production and list any found issues here.

**Comment by chesleyperry** [comment]
QA: Mac browsers checked: Safari, Firefox, Chrome 
Single image: Success!
Compound object in universal viewer: success!
Copy url for share link for a single image in the UV: success!

QA for Windows browsers

QA for mobile browsers
