### ISSUE TITLE
Discuss icons/thumbnails for A/V collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#84]
### Descriptive Summary

We need to have some conversation around what we want to use as icons for the A/V material.  We need to determine what the default graphic should be.  Also want to discuss the feasibility of using image thumbnails instead that are unique to an A/V collection or to individual A/V works.

### Background 

When the vendor digitized the CMF pilot recordings, they also took photos of the original reels.  We could use one of those photos as the thumbnail/icon for the recordings within the collection.

### Acceptance Criteria

This is what done looks like

* [ ] Determine default icon
* [ ] Come up with recommendation for using thumbnail images

### Related Work 

Follows #7 Ingest of CMF pilot

**Comment by kellyChex** [comment]
We're going to use a generic A/V thumbnail image instead of using work's images 

@JessWaggs Is there anything you can add to this such as what default image we decided to use for the thumbnail?

**Comment by rmjaffe** [comment]
@JessWaggs Are we OK with closing this ticket and moving it to done?

**Comment by JessWaggs** [comment]
Yes! : )
