### ISSUE TITLE
Update CMF pilot titles

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#85]
### Descriptive Summary

Sue observed that the titles supplied in the parent metadata records for the complex audio objects do not provide a lot of context, e.g. "Concert 2."

![Screen Shot 2019-10-17 at 11 00 35 AM](https://user-images.githubusercontent.com/32003407/67034886-64b42400-f0cd-11e9-9aac-fb7c68a1eaa1.png)

As a user, I want more context:  Concert 2 of what?  Concert 2 when?

### Acceptance Criteria

This is what done looks like

* [ ] Manually update parent metadata title values in DAMS to conform to following formula: Concert 2 --> 1982 Cabrillo Music Festival: Concert 2

### Expected Behavior 

Titles give context.

### Actual Behavior

Titles provide zero context.

### Related Work 

#7 Ingest of CMF pilot

**Comment by kellyChex** [comment]
This has been done: 
![Screen Shot 2020-01-23 at 4 19 41 PM](https://user-images.githubusercontent.com/9621070/73035213-2fba1a80-3dfc-11ea-9704-5825f37608ab.png)
