### ISSUE TITLE
() Update name of collection on CMF pilot collection landing page

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#86]
### Descriptive Summary

As an archivist, I would expect to see the formal name of the collection on the collection landing page.

### Acceptance Criteria

This is what done looks like

* [ ] Collection name updated to: Cabrillo Music Festival of Contemporary Music Recordings Collection

### Expected Behavior 

Collection name on collecting landing page is "Cabrillo Music Festival of Contemporary Music Recordings Collection"

### Actual Behavior

Appears as "Cabrillo Music Festival Recordings"

![Screen Shot 2019-10-17 at 11 10 08 AM](https://user-images.githubusercontent.com/32003407/67035858-5961f800-f0cf-11e9-80d9-aab10509204f.png)

https://digitalcollections.library.ucsc.edu/collections/st74cs35g

### Implementation Notes: 
This task will involve altering data in our system rather than making changes to our application’s front-end. The display labels are handled by ScoobySnacks, so two of those tickets just involve editing the metadata configuration file (https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/config/metadata.yml)

### Related Work 

#7 Ingest CMF pilot

**Comment by kellyChex** [comment]
@chesleyperry Do you remember if we moved this into Planning because it's not a priority? Or was this supposed to go into the Small Fixes column?

**Comment by rmjaffe** [comment]
Closed.  This will be resolved with UI/UX around CMF and collection level metadata.
