### ISSUE TITLE
(1) Update display label for physicalFormat metadata property

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#87]
### Descriptive Summary

As a user, I want to know that the format given in the metadata is the format of the original object.

### Acceptance Criteria

This is what done looks like

* [x] Update label "Format" for physicalFormat to "Source Format"

### Expected Behavior 

Label reads Source Format

### Actual Behavior

Label reads Format

![Screen Shot 2019-10-17 at 11 12 27 AM](https://user-images.githubusercontent.com/32003407/67035736-12740280-f0cf-11e9-8f60-7397e9f0be54.png)

### Implementation Notes: 
This task will involve altering data in our system rather than making changes to our application’s front-end. The display labels are handled by ScoobySnacks, so two of those tickets just involve editing the metadata configuration file (https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/config/metadata.yml)

**Comment by kellyChex** [comment]
This may be resolved with updates to the configuration file or @NedHenry let us know if this got fixed in the mix of doing other things.
