### ISSUE TITLE
(1) Update display label for metadata property publisherHomepage

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#88]
### Descriptive Summary

As a user, I don't want to be confused about whether the Publisher Homepage link is for the Original Publisher or the Digital Publisher.

### Acceptance Criteria

This is what done looks like

* [ ] Display label "Publisher Homepage" is updated to "Digital Publisher Homepage"

### Expected Behavior 

Label reads Digital Publisher Homepage

### Actual Behavior

Label reads Publisher Homepage

![Screen Shot 2019-10-17 at 11 17 41 AM](https://user-images.githubusercontent.com/32003407/67036085-cffef580-f0cf-11e9-9f95-97565e62ce9c.png)

# Implementation Notes: 
This task will involve altering data in our system rather than making changes to our application’s front-end. The display labels are handled by ScoobySnacks, so two of those tickets just involve editing the metadata configuration file (https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/master/config/metadata.yml)

**Comment by kellyChex** [comment]
This may be resolved with updates to the configuration file or @NedHenry let us know if this got fixed in the mix of doing other things.
