### ISSUE TITLE
(2) Investigate dateDigitized values incorrect in metadata records

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#89]
### Descriptive Summary

As the metadata person, I want the dateDigitized values entered on the ingest spreadsheet to display in the metadata records within the DAMS.

### Background
In looking at the metadata records for all the objects in the DAMS, it appears that:
1. A "Date Digitized" appears in every metadata record, whether or not the dateDigitized property had been included on the metadata ingest spreadsheet.

Example:  Shakespeare Santa Cruz ingest spreadsheet does not contain dateDigitized property, but a metadata value labeled Date Digitized displays in the DAMS.

![Screen Shot 2019-10-17 at 12 44 03 PM](https://user-images.githubusercontent.com/32003407/67042031-d2ffe300-f0db-11e9-8fa9-a3771c6875de.png)

2. The values that display in the metadata field labeled Date Digitized appear to be the dates that the objects were ingested.

Example:  Harry Mayo ingest spreadsheet did contain a DateDigitized property but the metadata values label Date Digitized in the DAMS do not match the values on the spreadsheet.

![Screen Shot 2019-10-17 at 12 47 14 PM](https://user-images.githubusercontent.com/32003407/67042217-473a8680-f0dc-11e9-8b68-81b975340027.png)
![Screen Shot 2019-10-17 at 12 42 01 PM](https://user-images.githubusercontent.com/32003407/67042240-5588a280-f0dc-11e9-84d9-23df32c0b40d.png)

### Acceptance Criteria

This is what done looks like

- [ ] Investigate what the issue is and assess if it's currently causing any harm (overriding the metadata). Ned to create another ticket from this investigation. 

### Potential Acceptance Criteria for the next ticket:

* [ ] dateDigitized values supplied in the ingest spreadsheet appear in the records within the DAMS
* [ ] dateDigitized values supplied in the ingest spreadsheet appear with the display label Date Digitized
* [ ] The ingest date either 1) does not appear or 2) appears/is captured within the metadata a in property other than dateDigitized and displays with a label other than Date Digitized.

### Expected Behavior 

If metadata ingest sheet does not contain dateDigitized, a Date Digitized will not appear in the DAMS.  If metadata ingest sheet does contain dateDigitized, a the values in the spreadsheet will appear in the DAMS.

### Actual Behavior

All records contain a metadata property labeled Date Digitized the contains (presumably) the ingest date.

### Related Work

Where dateDigitized and the ingest date appear in the record  (and whether they appear only in the staff view) will be determined as part of  #8 Determine metadata display on frontend

**Comment by kellyChex** [comment]
@NedHenry https://github.com/UCSCLibrary/dams_project_mgmt/issues/27 is related to this ticket. We may want to expand the investigation to look at dateCreated in addition to dateDigitized. 

@rmjaffe This ticket's scope is for Ned to investigate that the dateDigitized values are not being overridden. Another ticket to address the discovered issue will be created.

**Comment by NedHenry** [comment]
On further investigation, this is happening because the Hyrax core metadata property date_modified (which automatically stores the most recent time a record is edited by the Hyrax application) is automatically configured to use the RDF predicated DublinCore/modified, which we also use for our dateDigitized metadata property. I found that it is straightforward to redefine the date_modified property to use a different predicate, which solves the problem in my development environment. When I roll this change out into the production environment, future records will not have their dateDigitized metadata overwritten.
However, all of the records currently in the system have had their dateDigitized metadata overwritten with the date they were ingested into Hyrax. We should create a new ticket to decide how to proceed with that metadata element (eliminate the automatically generated date? Update the records with the overwritten metadata?).

**Comment by rmjaffe** [comment]
Thanks, Ned for looking into this.  I was thinking that this might be the issue -- as it was for type/resourceType.  I have no problem with swapping out the dc:modified predicate for dateDigitized -- what did you replace it with?

As far as the objects that have already been ingested, I don't think it's anywhere near a priority at this point (or ever) to update or remove those dateDigitized values.  If I remember correctly, we've already determined that the dateDigitized metadata property will only be visible staff in the staff user view.

**Comment by kellyChex** [comment]
Moving forward dateDigitized will not use the RDF predicated DublinCore/modified but will ready from the ingest spreadsheet. 

To be thorough, shouldn't we update the records so they're not showing incorrect information?

**Comment by rmjaffe** [comment]
I agree.  If the metadata are going to contain dates digitized, those dates should be accurate.  But if there's agreement that the values in this metadata property will not be public, I think updating/overlaying the metadata is definitely not a priority.

**Comment by kellyChex** [comment]
Ok, given that there is so much work in the backlog if we don’t complete this now and instead categorize as tech debt to do later we need to be comfortable with the likely possibility that this may never get done. If that's the case, I can create a ticket for the backlog.

**Comment by rmjaffe** [comment]
Ned, Sue, Jess and I talked about this in yesterday's stand up and I think we're OK with this being tech debt.

**Comment by JessWaggs** [comment]
Unless there is some compelling reason (eg. around fair use?) for displaying this to end-users, I would advocate against displaying it even if it were accurate.

I'll defer on the question of its inclusion for administrative users.

**Comment by kellyChex** [comment]
@chesleyperry You mentioned you wanted to be able to access this date in the future?

**Comment by kellyChex** [comment]
Created ticket to update the current DateDigitized values and make it so only Admin staff can see this field: https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/401
