### ISSUE TITLE
(5) Ability to click through child Works from parent Work Page 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#94]
### User Story: 

As a User, when I click on a different image (go back and forth between the different child Works) the metadata beneath the UV updates to display that selected image's metadata ( do not have to refresh the parent Work's page). 

Note: Image works 

### Mock Up:

<img width="801" alt="Screen Shot 2019-11-27 at 1 09 10 PM" src="https://user-images.githubusercontent.com/9621070/69765275-6125ab00-1117-11ea-861c-2fe576557096.png">

### Additional Notes:

- This is for the MS20 Collection and other complex collections 

### Related
This is loosely related to work in #128 Share model for works

**Comment by kellyChex** [comment]
This may soon to be solved in UCSCLibrary/dams_project_mgmt#93 so holding off on this for now.

**Comment by crisr15** [comment]
Need new mockups.  
Needs technical discussion on how to accomplish.  
Will want to include links to child works showing next the universal viewer.  
May also update the section below the Universal Viewer for the child metadata.  

Concerns around users being confused between what item they are looking at and what the URL will be for referencing.  Also, what should the title of the page be, and how do we show the Title of the child work and Metadata clearly (along with the URI for the child work) to make it easy for researchers to understand what they are looking at.

**Comment by JessWaggs** [comment]
@rmjaffe I think this card has been superseded by UCSCLibrary/ucsc-library-digital-collections#396 and UCSCLibrary/ucsc-library-digital-collections#397

**Comment by rmjaffe** [comment]
@JessWaggs Thanks for pointing this out.  I remember having been curious about this at one point, but clearly never followed up on asking about it!  I'll add a note and close it out.

**Comment by rmjaffe** [comment]
Work defined in this card now addressed by UCSCLibrary/ucsc-library-digital-collections#396 and UCSCLibrary/ucsc-library-digital-collections#397 per Jess's message above.
