### ISSUE TITLE
(2) Discuss Cabrillo and Media Player Improvements 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#98]
### Descriptive Summary

Go over findings from https://github.com/UCSCLibrary/dams_project_mgmt/issues/28 and https://github.com/UCSCLibrary/dams_project_mgmt/issues/25 and create necessary tix

**Comment by JessWaggs** [comment]
Here is the [A/V Scan](https://docs.google.com/document/d/18tAzqyN4CYyohBml8ab-beiakPdEbSVEeRQBSbjv_b8/edit?usp=sharing) for some samples/ideas of A/V objects in similar institutions and commercial sites.

**Comment by JessWaggs** [comment]
Hi all - also wanted to re-up my [Media Player User Requirements](https://docs.google.com/document/d/1u7xIgZHLepEAJ5eVpG9Xu99iuoSKwzvJ1nTmXszs8N0/edit) doc for this convo

I've added the Cornell experience as a playlist-as-paradigm example
